### ISSUE TITLE
Documentation for custom handler aside default controls

### ISSUE THREAD

**Issue by dropfen** [quilljs/quill#1005]
To add a custom Handler aside the default controls, I had to look into the code.

I found it, this is how it could be done:

```
const modules = {
  toolbar: {
    container: ["bold", "italic", "underline", "my-control"],
    handlers: { "my-control": function() { /** this.quill **/ } }
  }
}
```

I am done and happy :)

But, I am also suggesting, to add this to the documentation, because there is no example currently how you can mix the controls-array  with custom `handlers`.. It's not clear that you have to go the path, I went.. with controls inner `container`

However, it took me about 15 min to find the solution by reading the code. So this component is pretty well done!

Thank you!

**Comment by jackmu95** [comment]
The custom handler configuration is pretty well documented.
Please take a look at [this](http://quilljs.com/docs/modules/toolbar/#handlers).

**Comment by dropfen** [comment]
@jackmu95 Yes, as a standalone option, but not how you can combine it with http://quilljs.com/docs/modules/toolbar/#container 

The container example shows only the simple array approach:

`var toolbarOptions = ['bold', 'italic', 'underline', 'strike'];` 

And for handles its an object:

`var toolbarOptions = { handlers: {foo: function() {} }};`

its not clear, that you can do this:
```
var toolbarOptions = { 
  container: ["bold", "italic"],
  handlers: {foo: function() {} }
};
```

**Comment by jhchen** [comment]
The very first code example on http://quilljs.com/docs/modules/toolbar/ has both `container` and `handlers` fields set.

**Comment by gianmarcotoso** [comment]
I agree with @dropfen , the documentation is not clear on the matter. It's true that the first example has both `container` and `handlers` set, but `container` is valorised as a selector, and it's not clear that it can also by an array of default controls. A single line saying "The `container` can be either a selector or a simple array of format names, as in the examples below" would be more than enough to avoid any confusion.

**Comment by negamaxi** [comment]
Same here. Not clear.

**Comment by kylesezhi** [comment]
I would recommend adding the example from @dropfen in this section of the docs:
https://quilljs.com/docs/modules/toolbar/#handlers

(That is where I would have expected it. Googling about this issue brought me here.)

**Comment by AceBeing** [comment]
The document does not clarify how to combine the controls array with custom handlers, again. I stuck on this for a while until I saw this issue.

**Comment by jhchen** [comment]
Okay I have added a clarification to the effect of what @gianmarcotoso suggested in https://github.com/quilljs/quill/commit/9cb5732f413fd43b39856de07c3fece16cc3ff38.

I did not go with the exact phrasing because it is also true you can specify a DOM element as stated later in that page "For use cases requiring even more customization, you can manually create a toolbar in HTML, and pass the DOM element or selector into Quill."

**Comment by toramanlis** [comment]
> The very first code example on http://quilljs.com/docs/modules/toolbar/ has both `container` and `handlers` fields set.

Don't you just love when the developers just refuse without reading the suggestion :) You are obviously smart enough to understand what was being suggested unless you just don't care enough to pay attention. It's amazing that it took this many comments and this much explaining.

**Comment by toramanlis** [comment]
> Okay I have added a clarification to the effect of what @gianmarcotoso suggested in [9cb5732](https://github.com/quilljs/quill/commit/9cb5732f413fd43b39856de07c3fece16cc3ff38).
> 
> I did not go with the exact phrasing because it is also true you can specify a DOM element as stated later in that page "For use cases requiring even more customization, you can manually create a toolbar in HTML, and pass the DOM element or selector into Quill."

I don't think it's nowhere near being clear enough yet. The examples now shows that `toolbar` can be an array, an object or a selector and `toolbar.container` can be a selector. At no point the docs say `toolbar.container` could be an array. Because only then the client can deduce that the `container` property will be where the controls array goes when defining handlers.

The way it is now, it looks like `toolbar.container` is reserved for specifying the selector (hence the name "container") and the controls go directly to the `toolbar` property. This commit tells that we can just populate the whole `toolbar` property with the selector. However at no point the documentation tells us where the controls array may go other than the `toolbar` property.

I think the communication issue lies under the fact that in your mind you already know that the word "container" also refers the controls array as it replaces the need to use a selector, rather than just defining controls. You know, only after reading this thread I realized there's no way to provide a selector and add extra controls to it programmatically via a controls array. For all I knew, providing a selector was independent from providing a controls array.

**Comment by brexis** [comment]
+1.
Still not documented. I just came here by searching on google.

**Comment by mrigdon** [comment]
same

**Comment by raphael-bresson** [comment]
+1

**Comment by evnp** [comment]
Still not documented. Got here after reading through https://quilljs.com/docs/modules/toolbar and not finding clarity on this. These are the examples included in that doc; none of them combine format array and handlers:
```
toolbar: { container: '#toolbar', handlers: { ... } }
toolbar: { container: '#toolbar' }
toolbar: [ ... ]
toolbar: { handlers: { ... } }
```
A single example in that doc would completely clarify this for future readers.

**Comment by chocking** [comment]
What about combining dom-selector and array config..

**Comment by jmnsf** [comment]
5 years later, this issue still going strong 🙃

**Comment by ruimcf** [comment]
The issue in the first post is still ongoing after 6 years.
I had to come to this issue to figure out I could specify default formats + my own handlers without having an external toolbar id.

In the Container section https://quilljs.com/docs/modules/toolbar/#container there is not a single mention to `toolbar: { container: ...stuff }`, only `toolbar: ...stuff`
