### ISSUE TITLE
Applying a Delta can throw

### ISSUE THREAD

**Issue by w00fz** [quilljs/quill#1050]
It looks like when reducing the ops in the `applyDelta` in some cases it might throw, for instance when an op has `0` value or if an `insert` op is missing.
I think the length of the op should be set in a more robust way rather than via the `OR` concatenation check that is happening in 
https://github.com/quilljs/quill/blob/develop/core/editor.js#L29.

I can go ahead and open a PR but I wanted to first discuss this in case I am missing something or there are other reasons for it.

**Steps for Reproduction**

1. Visit http://codepen.io/w00fz/pen/JRBGYO?editors=0010
2. Open the browser console
3. Click on the image toolbar and you will see the error.

**Comment by jackmu95** [comment]
The Delta format is designed to be [compact](http://quilljs.com/guides/designing-the-delta-format/#compact). So the following Delta is invalid:

```javascript
var delta = [
  { retain: 5 },
  { delete: 0 }, // Not compact. Length should be greater than zero.
  { insert: { image: 'https://avatars0.githubusercontent.com/u/7089101?v=3&s=200' } }
];
```

**Anyway...**
> I think the length of the op should be set in a more robust way rather than via the OR concatenation check that is happening in https://github.com/quilljs/quill/blob/develop/core/editor.js#L29.

@w00fz I'am with you here.

**Comment by jhchen** [comment]
Is the complaint that the line is too clever? I'm not sure I see a difference in robustness. I would say A is more robust than B, if there exists a case C where A succeeds but B fails. What is the real world C here? The given example is not a valid Delta as @jackmu95 already pointed out.

**Comment by jackmu95** [comment]
After taking another look at [the line](https://github.com/quilljs/quill/blob/develop/core/editor.js#L25) I have to agree that it covers all **valid** length options in a clever and short way.

The problem I have is that it throws a exception when the Delta isn't valid because there is no check if `op.insert` is defined before trying to access its `length` property.

@jhchen What do you think about this sightly modified version?
```javascript
let length = op.retain || op.delete || (op.insert ? op.insert.length : false) || 1;
```
or even
```javascript
let length = op.retain || op.delete || (op.insert ? op.insert.length : 1);
```

**Comment by w00fz** [comment]
That is pretty much the only weakness I saw, with the insert.
I had it throwing because there was no `insert` and all previous values were `0`. So it basically skipped all (because of `0`), reached insert which wasn't there and threw because of the missing check that @jackmu95 pointed out.

I take `0` is not a valid retain or delete value?

**Comment by w00fz** [comment]
Just to be clear, my use case was this:

```
const range = this.quill.getSelection(true);
this.quill.updateContents({
    ops: [{
        retain: range.index
    }, {
        delete: range.length
    }, {
        insert: { image: event.target.src },
        attributes: { 'data-src': 'test-data-src' }
    }]
}, 'user');
```

So I wasn't directly setting anything to `0`, I am blindly relying on the range. I had assumed that a `delete: 0`, if invalid, would just get ignored, otherwise it would imply that one has to add checks around all ranges values that get passed to.

Unless I'm doing something completely wrong in here!

**Comment by jackmu95** [comment]
'0' is not a valid value for delete and retain.
IMHO a invalid delta should just be ignored and shoudn't throw a exception.

**Comment by jhchen** [comment]
Actually it is not recommended to create Deltas by hand at all since some of its constraints are a bit tricky to keep up with (for example inserts need to go before deletes as well so the example delta is not valid for this reason too). I thought this was stated in the docs but that must have gotten lost over the various versions. The recommended way is to use the `insert()`, `retain()` and `delete()` functions:

```js
const range = this.quill.getSelection(true);
this.quill.updateContents(
  new Delta()
    .retain(range.index)
    .delete(range.length)
    .insert({ image: event.target.src }, { 'data-src': 'test-data-src' })
, 'user');
```

Deltas can represent large documents and are constructed very often (text-change can happen on each keystroke) so they have to be very performant so it only makes sense to do its checks upon creation, rather than every function involving Deltas.

**Comment by tkefauver** [comment]
> Is the complaint that the line is too clever? I'm not sure I see a difference in robustness. I would say A is more robust than B, if there exists a case C where A succeeds but B fails. What is the real world C here? The given example is not a valid Delta as @jackmu95 already pointed out.

C in my case is the `format` op which has `index` and `length` properties like in this `Delta`:
```
{
	"ops": [
		{
			"attributes": {
				"link": "https://www.google.com/",
				"linkType": "url"
			},
			"format": {
				"index": 16,
				"length": 12
			}
		}
}
```

Based on [this example](https://quilljs.com/guides/designing-the-delta-format/#format) I should be able to use the `updateContents` function but it fails in `applyDelta` at line #41 (using quill 2.0.3). 

Further even if I try to create a delta like `new Delta().format` is not defined either so I must be confused about its usage or is this a valid case @jhchen ?
