### ISSUE TITLE
Receive error and lose cursor focus when creating content in newlines

### ISSUE THREAD

**Issue by mattroyer** [quilljs/quill#1061]
When using `setContents(<some_delta>)`, I'm getting an error when there is a newline character in the middle of a string for an `insert` value.

Here is my code (with console outputs):

```javascript
var database = firebase.database();

var delta;
var data;

quill.on('text-change', function() {
  delta = quill.getContents();
  firebase.database().ref('text').set(delta);
});

var textRef = firebase.database().ref('text');
textRef.on('value', function(snapshot) {
  data = snapshot.val();
  console.log("Data value: " + JSON.stringify(data));
  console.log("Data type: " + typeof data);
  console.log("Quill Version: " + Quill.version);
  quill.setContents(data);
});
```

I receive the data back as an object. It's like it is trying to find a place to put the cursor after the newline character is introduced (I'm guessing, since it's using the `selection` section) and it can't find it because of that character. Not sure.

**Steps for Reproduction**

1. Type anything in the editor without hitting the Enter key
2. Press the Enter key
3. Type anything else
4. Error comes up when one letter is typed besides hitting the Enter key

**Expected behavior**:
Should be able to type and hit the Enter key to create newlines

**Actual behavior**:

![image](https://cloud.githubusercontent.com/assets/225065/19535432/d9e32d9c-9604-11e6-8de6-329f85de88de.png)

> Receive the error `The given range isn't in document.` and the cursor loses focus.

**Platforms**:

Browser: Chrome Version 53.0.2785.143 m
OS: Windows 10

**Version**:

1.1.0

**Comment by benbro** [comment]
I've tried typing, pressing enter and typing again in the [playground](http://quilljs.com/playground/) and I'm not getting an error in Chrome 54.

I see that you are calling quill.setContents(data) with a delta received from firebase.
Instead of 'type anything, press enter...' can you specify the exact steps to reproduce?
Something like:
1. Type 'abc'
2. Place the cursor after the letter 'b'
3. Press Enter
4. Call quill.setContents(data); with {"ops": [... fill the actual ops here...]}
