### ISSUE TITLE
Header option placed in wrong paragraph when use getContents()

### ISSUE THREAD

**Issue by galenyuan** [quilljs/quill#1076]
Hi, I try to use header option in toolbar, but I found when I try to use getContents(), it placed header attribute to wrong paragraph

**Steps for Reproduction**

1. Visit http://jsbin.com/nojuhoxiqi/edit?html,output
2. Open your console
3. Input something

**Expected behavior**:
```json
{
    "ops": [{
       "attributes": {
            "header": 1
        },
        "insert": "Hello World!"
    },
    {
        "insert": "\n"
    }]
}
```
**Actual behavior**:
```json
{
    "ops": [{
        "insert": "Hello World!"
    },
    {
        "attributes": {
            "header": 1
        },
        "insert": "\n"
    }]
}
```
**Platforms**:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Version**:

1.0.0

**Comment by benbro** [comment]
This is by design.
Some formats like alignment, direction and list act on the whole line while others like bold and underline act on several characters. You can't have one character with left alignment and another with center alignment on the same line. The new line character is the perfect place to store formats that affect the whole line.

**Comment by galenyuan** [comment]
@benbro Thanks!
