### ISSUE TITLE
Docs do not explain how to retrieve Quill html result

### ISSUE THREAD

**Issue by jptillman** [quilljs/quill#1098]
Quill Editor v1.1.3

The available quill docs and the downloadable examples all fail to provide some critical information that explains the best way to retrieve the resulting HTML the Quill editor.  Unless I've misunderstood the way Quill works (which I would also consider a deficiency in the docs, considering the time I've blown poring over the exact same text so far), this is a significant blockage to anyone wanting to use the editor for anything other than a demonstration.

I suggest someone at least add this somewhere appropriate in the online docs.  I'm a reasonably intelligent guy, and I blew a good half hour on this until I read all the way through this issue: 

https://github.com/quilljs/quill/issues/903#issuecomment-243844178

Note that I was seeking the _supported_ method of doing this.  Sure, I could have just gone after `container.firstChild.innerHtml` but by remaining mute on the topic, you leave me worried that your next point release will blow up my code.

**Comment by jhchen** [comment]
The answer is "get it the normal way." Quill is not special.

`container.firstChild.innerHTML` is one way to do that. I suggested others in other issues that can be found by searching simply "html", "get html" or "gethtml" on this github repository or "quill" + any of these queries on Google since Google indexes Github. There is no guarantee with regards to `firstChild` which I pointed out in that issue you linked.

I have already made it clear in the upgrading guides (which can be found on the main documentation site and top 3 search results for the above queries) and in comments of multiple issues that I am not adding a passthrough API.

I do not continue to comment in those issues such as #903 my response to the new comments can already be found by scrolling up. I do not believe it is productive to talk or argue in circles.
