### ISSUE TITLE
merge consecutive blocks

### ISSUE THREAD

**Issue by RobAley** [quilljs/quill#1117]
Is there a way to cause consecutive block formats to merge? 

Currently, if you press enter while in e.g. a blockquote Quill creates a new blockquote element. 

This means that I can't use CSS to style the "whole" blockquote if it contains new/blank lines, e.g. I can't set border-top and border-bottom.

Is there any way to allow new lines in a block format, or merge consecutive ones on the fly?

If not, then I guess this is a feature request :)

**Comment by jhchen** [comment]
It is still possible to use CSS but less straightforward if you use sibling selectors.

It is not possible to have one `<blockquote>` tag for multiple lines at the moment and I don't see a reason to add it due to lack of a practical use case. If you have one please follow the [Contributing Guide](https://github.com/quilljs/quill/blob/master/.github/CONTRIBUTING.md#feature-requests) for feature requests.

**Comment by RobAley** [comment]
Thanks, I'll write up a proper feature request. I can't use css for e.g. a custom "aside" block that allows newlines (or a blockquote that quotes multiple paragraphs from another document) and has a border all the way around. You can only tell if the block is the last block (to set a bottom border) once you get onto the next block of a different type, and css selectors can't look backwards (afaik). You also can't use :last-of-type selector as that would only allow for one block of that type per document.
