### ISSUE TITLE
Way to render diff between two document versions ?

### ISSUE THREAD

**Issue by ncoquelet** [quilljs/quill#1125]
Hi All,

I'm starting to use Quill and I'm really impressive by the simplicity  of integration
Do you know if it exist a solution to render the difference between two versions of the same document ?
For example between the published document and a draft version !

Thanks a lot

**Comment by jhchen** [comment]
This is not an available feature. I'm not sure it makes sense to add to the core library but feel free to make a [case](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#feature-requests) for it.

**Comment by danielkmau** [comment]
You can use the diff() function provided in the Delta library.

**Comment by Percipient24** [comment]
For example, here's a quick pen that uses diff() and compose():
https://codepen.io/percipient24/pen/eEBOjG

**Comment by mihitha** [comment]
@Percipient24 Thanks lot for your smart solution.

**Comment by sgon00** [comment]
Hi, thanks a lot for the diff()/compose() example code. I just get one more question. Do anyone know how to handle the text with format change instead of insertion and deletion? The example code can not show any differences if text format changed from bold to normal or from Heading to normal etc... I tried to implement some functions, but none of them works well. Are there any existing packages which handle such diff easily? Thanks a lot.

**Comment by WindrunnerMax** [comment]
I have a comparative view implemented through a virtual layer [DEMO](https://codesandbox.io/p/sandbox/quill-diff-view-369jt6). This virtual layer refers to applying markers not directly to the document, but overlaying them using DOM structures. This is useful in scenarios that require simultaneous editing and diffing, similar to the "find and replace" feature. There is a related [Blog](https://blog-ssg.touchczy.top/Plugin/%E5%88%9D%E6%8E%A2%E5%AF%8C%E6%96%87%E6%9C%AC%E4%B9%8B%E6%96%87%E6%A1%A3diff%E7%AE%97%E6%B3%95.html) for reference.

<img width="1678" alt="image" src="https://github.com/quilljs/quill/assets/33169019/9af86741-269c-4354-aae2-c7bf5c297e01">
