### ISSUE TITLE
Difficulty in registering linkTooltip to custom theme

### ISSUE THREAD

**Issue by CoenWarmer** [quilljs/quill#1127]
I've been searching through the documentation for guidance on how to implement a link tooltip to a non standard theme (eg, not snow or bubble) but I'm running into problems. It is my understanding I need to import the link module and then register it in order for it to be available in the instance of my editor, but I can't get it to work.

**Steps for Reproduction**

Try this code:

```
	let LinkToolTip = Quill.import('formats/link');
	
	Quill.register(
		new Parchment.Attributor.Style('align', 'text-align', { scope: Parchment.Scope.BLOCK }),
		new LinkToolTip(),
		true
	);

```
**Expected behavior**:

Link tool tip is now a module that is available in my theme.

**Actual behavior**:

Error in console is thrown:

```
TypeError: Cannot set property '__blot' of undefined
    at Link.ShadowBlot.attach (quill.js:613)
    etc
```

**Platforms**:

Chrome, latest version

**Version**:

v1.1.5

**Comment by jhchen** [comment]
>> It is my understanding I need to import the link module and then register it in order for [the link tooltip] to be available

Where in the documentation lead you to believe this?

**Comment by CoenWarmer** [comment]
Okay, maybe I misread this, and I do apologise if this isn't the right channel to ask implementation questions like this. I am looking for a way to implement a Snow like Link blot to an instance of Quill that has no theme defined. I have read through the docs but I am a bit lost. Are there any how-to's available somewhere that describe how to achieve this? Thank you for your work, Quill is an amazing library.

**Comment by jhchen** [comment]
This Issues is primarily for bug reports and feature requests. Fixing *wrong* documentation is crucial, which is why I asked. The example code included to try also does not conform to the signature listed in the [API](http://quilljs.com/docs/api/#register) so I'm wondering where it and the understanding came from.

To answer your question, if you are using your own theme you should probably also implement your own tooltip for it and use the standard [APIs](http://quilljs.com/docs/api/) to interface with Quill (to apply formatting and get formatting state).
