### ISSUE TITLE
Undo/redo toolbar controls/icons

### ISSUE THREAD

**Issue by rquast** [quilljs/quill#1143]
Undo/redo not available in the toolbar. Quill 1.1.5

**Comment by benbro** [comment]
I don't think undo/redo icons are common in text editors.
I don't see such icons in Word, LibreOffice and Google Docs.

If you need it, it's easy to add custom buttons and call the [history](http://quilljs.com/docs/modules/history/) module.
You can find undo and redo icons [here](https://github.com/quilljs/quill/tree/develop/assets/icons).

**Comment by rquast** [comment]
Thanks for the tip about the icons. I'll use those instead.

**Comment by rquast** [comment]
Incidentally, ckeditor has it. I've seen it around the place a fair bit in the past.

http://gdb.rferl.org/589D9520-9C16-48D0-8005-9BE6D65FC276_w610_r1_s.png

Same with tinymce..

https://www.limesurvey.org/media/kunena/attachments/11021/Capture3_2014-02-14.png

**Comment by rquast** [comment]
And word online has it too.. https://support.content.office.net/en-us/media/4189596e-817b-49ab-b5e6-6884c0ca259e.png

**Comment by loveLibra** [comment]
how to extend redo&undo to quill (icon & api) ? Any code or documents guide this ? @benbro  ...

**Comment by drpiou** [comment]
> I don't think undo/redo icons are common in text editors.
> I don't see such icons in Word, LibreOffice and Google Docs.
> 
> If you need it, it's easy to add custom buttons and call the [history](http://quilljs.com/docs/modules/history/) module.
> You can find undo and redo icons [here](https://github.com/quilljs/quill/tree/develop/assets/icons).

I'm sorry but I do not agree. Undo/redo buttons are used by end users, most of them actually doesn't even think to scroll on a page.

But what I do not agree with is the fact that the icons exists, the methods exist, the module exists, but no single option to activate the undo/redo buttons.

As a side note, I'm really sad having read so much articles saying to go with Quill because it's awesome, but now I implemented it on my structure, I am strongly against this choice. I'm loosing sooo much time recovering informations that the documentation is missing (formats options are listed, but nothing from the toolbar options except some more or less complete examples, having a single/simple divider to work was a pain in the ass, the documentation make profit of the internal API but I just don't get it because it seems really weird/complicated, examples make use of jQuery instead of the handlers, missing some basic features like tables/select-all/fullscreen/view-source doesn't seems so Drop-In either, the two plugins I was interested for doesn't works - quill-emoji because it doesn't work - quill-better-table because it needs an un-npm-able quill version, and other frustrations...).

**Comment by dallasnicol** [comment]
> I don't think undo/redo icons are common in text editors.
> I don't see such icons in Word, LibreOffice and Google Docs.

I think it is more common than you think... including in Word and Google Docs.

https://www.addintools.com/documents/word/images/shot-ribbon-undo-button.png

https://i.stack.imgur.com/tfSyT.png

**Comment by jkevingutierrez** [comment]
You already have the icons and the functionality, it would be great to be able to just add it to the toolbarOptions

**Comment by nlgt11** [comment]
- [ ] d
- [ ] fdsafaadsffasf
- [ ] sadfasfdaf

- [ ]

**Comment by Jeremias-Nater** [comment]
I also need this and although i was able to implement the buttons i think it would have been very nice if this was implemented as its such a small amount of code. Also im having issues to find out how to disable / remove the icons when there is nothing to undo redo with my own implementation which would probably be just as easy inside the library.
