### ISSUE TITLE
JSON Schema for delta JSON

### ISSUE THREAD

**Issue by rquast** [quilljs/quill#1145]
I have a feature request: create a delta JSON schema

Reason:

Validation & integrity checking on both the client and server sides. User side saves can be corrupted. Don't want to save if the data being sent is corrupted.

Similar to:

https://github.com/dnephin/quill-data-format/blob/master/schemas/quill.json

**Comment by benbro** [comment]
On the client you could just wrap setContents with try/catch as shown in this [example](http://codepen.io/anon/pen/QGqBPw).

I'm not sure what is the added value of validating the delta on the server.
A malicious user can send a bad delta but he could also send blank text or random characters.
What are we trying to solve here?

If there is an existing project that gives you a JSON schema for Quill, why can't you use it?

**Comment by rquast** [comment]
So I should save, then load it up in an editor again with a try/catch and then send so I don't corrupt the data?

I'm trying to solve validation. I don't trust that the code would always function 100% on everyone's browser enough for it to be saved, then restored without the possibility of corruption at some point or other.

Also, how can I trust that the format won't change over time without a schema? That's why document formats come with schemas. I can use this guys schema, but he doesn't maintain quill. How do I know it's correct?

**Comment by jhchen** [comment]
I'm not understanding the concern, particularly where the fear in bugs lie. If it's in the Quill codebase, then more code in the Quill codebase to implement said JSON schema is not the answer. If it's in your codebase, then that's beyond the scope of Quill. If it's in the browser or some network layer, then I'd be interested in data supporting why that concern is significant.

The Delta codebase and format is semantically versioned.

**Comment by rquast** [comment]
I've changed to substance.io. Closing the issue since I'm no longer interested.

**Comment by cramarokoto** [comment]
Hi there !
Any news on this feature request ?

Quill is a wonderfull project and it would be amazing if deltas were even more explicit. Indeed, we can save the JSON in our backends (as stated in #993 ) but not having a schema has many drawbacks :
- a part of the JSON will just be saved as "any" format because of the polymorphism of some fields (insert can be either a text or an object for example)
- we cannot check the validity of the delta we receive in our backends
- we cannot manipulate the deltas directly without uncertainty

It's not about a lack of trust in the Quill codebase, it's about reducing the cost of the representation of quill deltas in other systems than JS applications so that it feels more open to the developers.
