### ISSUE TITLE
Merge Quill container and editor divs

### ISSUE THREAD

**Issue by bedeoverend** [quilljs/quill#1146]
Essentially I'm after a way to use Quill without adding an extra level of DOM hierachy. Being able to specify the editor element _or_ passing a flag to just use the specified container as the editor would allow this. I realise this would potentially add difficulties around generally adding containers, but would also give more power and flexibility.

I'm looking at Quill to create an inline editor, rather than a full WYSIWYG - where the HTML as similar as possible between when someone is viewing the content, and editing the content. Or at least the DOM structure remains the same. I'm using Quill inside a Custom Element, so the aim is to make the Custom Element itself a Quill Editor.

So far I've made a POC by subclassing Quill - but it seems incredibly hacky, and not at all viable going forward:

I've essentially done this:
```js
class Editor extends Quill {
  addContainer(cls) {
    if (cls === 'ql-editor') {
      return this.container;
    }
  }
}
```

In my case, I'd be happy to then handle any other containers being added - delegating where they go, or if they're stored elsewhere, rather than placing them all alongside the editor.

Thanks for Quill - fantastic editor!

**Comment by benbro** [comment]
What are you trying to do and what doesn't work?

**Comment by bedeoverend** [comment]
I'm trying to instantiate a Quill editor with `contenteditable` being applied to the `container` - that's probably the simplest way I can put it. I can't see of a way to achieve this currently.

Essentially rather than something like:
```html
<div id="container">
  <div class="ql-editor"></div>
</div>
```

after calling `new Quill('#container');` the ability for it end up like:

```html
<div id="container" class="ql-editor" contenteditable></div>
```

**Comment by benbro** [comment]
Quill work as a black box. You apply it to a div and it gives you a rich text editor.
I don't understand why you care about the structure below the editor element and why do you need the contenteditable attribute.

**Comment by bedeoverend** [comment]
@benbro Sorry, I'll try clarify - the `contenteditable` attribute was just to illustrate what I was trying to do - I've updated my comment to make it clearer.

When styling the content of an editor, I don't want to have to worry about the extra DOM level. I want to use Quill to edit _and_ display content on a third party site  - with the same CSS styles applied regardless of editing or viewing. So if on the third party site they have `section > p { ... }` If I then created Quill editor like `new Quill('section#container')` it would break those styles. If however, `Quill` didn't inject an extra level of DOM hierarchy, this styling would work the same.

Does that makes sense?

**Comment by benbro** [comment]
Sorry, I can't keep track. With each comment you are talking about something completely different.
The contenteditable attribute has nothing to do with an extra level of DOM hierarchy or with a page CSS.

**Comment by BoizZ** [comment]
I want to customize the content of the style, so need to add class or id attribute for the elements, there may be a html editing function will be better.

**Comment by jhchen** [comment]
`ql-container` is necessary as it stores not just `ql-editor`, but other containers as well--for example the clipboard. I'm not clear on the benefits or the use case for flattening this.

**Comment by seaneking** [comment]
Use-case for flattening: inline editing. 

We're thinking of using Quill as our richtext editor for [Simpla](https://www.simpla.io), and an important criteria is that it has to work seamlessly inline for the user. The injected wrapper div breaks this promise specifically because Quill acts as a 'black box'.

Few problems this introduces:

- Direct child selectors break (ie: `.quill > p`).

- Inline content breaks. This is more specific to using Quill as a custom element, but say you wanted `<p><quill-editor></quill-editor></p>`, the injected div (block-level element) breaks that markup.

**Comment by jhchen** [comment]
There is an important distinction between a feature and a particular implementation for a feature. Inline editing as a feature does not require a particular DOM hierarchy.

I'm assuming `.quill` is what you are passing into Quill ie `myEditor = new Quill('.quill');`

As `.quill` is a custom class implying you have control over it, why not have your CSS rule be `.quill > .ql-editor > p`?

Can you clarify what the breaking behavior is for the second scenario?

**Comment by seaneking** [comment]
> As .quill is a custom class implying you have control over it, why not have your CSS rule be .quill > .ql-editor > p?

Using `.quill` was just an example, in this case we'd be instantiating Quill in something for a user, who would be the one using this richtext element in their own markup. And yes, we could document that there is a wrapper div injected inside their DOM with a class of `.ql-editor` to deal with, but it's a subtle gotcha that we'd prefer to avoid. 

> Can you clarify what the breaking behavior is for the second scenario?

Sure, again this is in the context of in-place editing. The idea is to allow Quill to operate inside other textual elements (spans, headings, etc), where it would act as an inline element (display inline, only allow line-breaks, etc).

For example, suppose you had the following
```html
<span>
  <!-- quill-editor is display: inline and only allows line-breaks -->
  <quill-editor></quill-editor>
</span>
```

And you wanted the resulting markup to look something like this
```html
<span>
  <quill-editor>
    This is some content...
  </quill-editor>
</span>
```

Having a wrapper div in there
```html
<span>
  <quill-editor>
    <div class="ql-editor">
      This is some content...
    </div>
  </quill-editor>
</span>
```

Breaks both the styling and the validity of our markup, since divs are block-level elements.

I think this all comes down to the fact that, as you said above, Quill is designed to create its own little black box, and in-place editing is kind of at odds with that.

**Comment by jhchen** [comment]
Thank you for the explanation. Quill at the moment needs both the `.ql-editor` and parent `ql-container` div since `ql-editor` is not the only child, and its siblings are not optional. For example paste would not work correctly in all supported browsers if `ql-clipboard` was not present. It could be possible to put these sibling divs somewhere else, but given the description, this does seem to be the only problem you will likely encounter. For example I'm not sure the display: inline use case will work out since Quill and Parchment does expect lines and block level nodes.

If you do want to explore this route more, I would suggest forking Quill and making some of these changes (for example appending ql-clipboard to body instead) and if you are able to get everything to work then we can discuss merging some of these changes or supporting some of the options in the official project. Otherwise right now what I would predict is you'll hit some other roadblock and any work up to that point would be wasted.

**Comment by seaneking** [comment]
Yep that's fair, and thanks for pointing all that out. We'll investigate further ourselves and report back - parchment expecting block level nodes in particular could be problematic.
