### ISSUE TITLE
Is it possible to use jquery.validation and Quill.js together?

### ISSUE THREAD

**Issue by flaudre** [quilljs/quill#1169]
I am using jquery.validation 1.16 and Quill 1.0.0 as modules with require.js. The editor container is placed within a form tag, which i validate using $('form').validate()

On DOM loaded there is no error, but once i click on the editor and then click outside of it jquery.validate throws "TypeError: a is undefined". I believe it is that quill does something with the input, on focus and on blur, I also see that the hidden input inside the editor does not have a name attribute. 

So I just wanted to ask if somebody else already tried this, and if there is a solution.

Firefox 50.0.2, Ubuntu 16.04

**Comment by benbro** [comment]
Quill transforms a div into a rich text editor, not textarea or other form elements.
Please fork the [codepen](http://codepen.io/quill/pen/KzZqZx) with a real example showing your issue.

**Comment by jhchen** [comment]
I don't believe jQuery validation works on Quill.

**Comment by aichholzer** [comment]
I am not sure anyone actually understood the issue posted by @flaudre 
I have exactly the same issue; the DOM loads fine, no errors, but as soon as I click on the editor (quill) and click outside of it jquery throws an exception. It seems that something is happening on the .onblur method with quill.

I guess we need to investigate since there is no info, whatsoever, about it.

**Comment by newbaner** [comment]
I don't know how **quill**'s cursor works, but the **jquery.validator** fails after cursor blur. So,I try to add a configuration item to the jquery.validator:
 `onfocusout: function(element){
                   return false;
                },`
It's well!
