### ISSUE TITLE
Custom blot interaction on key press with Syntax module

### ISSUE THREAD

**Issue by RobAley** [quilljs/quill#1170]
When using a custom block embed blot that accept user input (e.g. editable elements, form fields etc.) and having the syntax module enabled at the same time means that the cursor jumps out of the custom blot back into quill upon a key press. Without the syntax module enabled, it works fine. The minimal codepen below shows the most basic input blot I could think of which demonstrates the connection with the syntax module.

**Steps for Reproduction**

1. Visit http://codepen.io/anon/pen/vyreZR
2. Click the Test Button
3. Try to type into one of the table cells. The cursor will jump out of the table back into the main Quill instance after 1 key press.
4. Comment out "syntax: true" in the JS, re-run the codepen, and repeat 2 & 3. This should allow you to edit the table text fine.

**Expected behavior**:

As described in 4 above, but with syntax module enabled.

**Actual behavior**:

As described in 3 above.

**Platforms**:

Ubuntu Linux 16.04, Firefox 50 and Chromium 53

**Version**:

See codepen includes for versions of quill & highlightjs

**Comment by jhchen** [comment]
The syntax module saves and restores the selection as part of its normal operations. Your InputBlot is reportedly of length 1 (since it is a BlockEmbed) but really it is not which is why when it restores the selection, it is placed at the wrong location. To remedy this your InputBlot will have to report the correct length, and be able to handle split operations.

So yes removing the syntax module happens to allow this part to work, but all selection saving and restoring functionality is broken from the incorrect length reporting.

Tables is a complex feature to add and there is an issue on it #117.

**Comment by RobAley** [comment]
Thanks. (I've seen #117, I'm trying to implement an embed with several form inputs in a non-editable table, but the example I gave was just to illustrate the action). 

If I can calculate it, what/how should my blot report the correct length (and update it if it changes)?
