### ISSUE TITLE
Changing headline back to normal broken in 1.1.7. - working with 1.1.6 

### ISSUE THREAD

**Issue by berndschimmer** [quilljs/quill#1191]
Changing headline back to normal broken in 1.1.7.
With 1.1.6 it is working.

**Steps for Reproduction**

1. Visit http://codepen.io/quill/pen/KzZqZx
2. Step Two
write "test" and change normal to headline 1 (or 2)
3. Step Three
change headline 1 (or 2) to normal -> not working
**Expected behavior**:
could change (all) headline to normal back and forth

**Actual behavior**:
could not change back to normal after changed to headline 1 (or 2)

**Platforms**:
all

**Version**:
1.1.7

Working with Version 1.1.6 
http://codepen.io/anon/pen/pNxBQr

**Comment by torkjels** [comment]
I'm encountering the same problem.
(At the end of your post you've written version 1.17 but version 1.1.7 elsewhere)

**Comment by berndschimmer** [comment]
thx. forgot the . between 1 and 7 :)

**Comment by dmarkow** [comment]
It seems to affect anything with a dropdown in the toolbar (Font, Size, horizontal alignment, text color, background color, etc.) -- the "default" option in the dropdown is always pre-selected rather than the actual current option -- so it doesn't let you click the default.

For example, go to http://quilljs.com/docs/formats type something in and center align it -- when you click to put it back on left alignment, the dropdown already has the "left" option in blue thinking it's already set to that and clicking it does nothing, leaving the text stuck in center alignment.
