### ISSUE TITLE
Background color is not preserved when copy/cut text from quill then paste again in IE11 

### ISSUE THREAD

**Issue by GammaFelix** [quilljs/quill#1211]
**Steps for Reproduction**
1. Visit [this fiddle](https://jsfiddle.net/gamafelix/m3g1ysnj/)
2. Write a line with more than one word.
3. Set the background color of any word, except the last one.
4. Mark all text. Cut (Ctrl+x) then paste (Ctrl+v)

**Expected behavior**:
Background color is pasted.

**Actual behavior**:
The background color is lost.

**Platforms**:
IE11

**Version**:
1.1.7

Note: It works in IE11 if the format is in the last word of the line.

**Comment by smura** [comment]
I found a solution.

### Detail of this issue

Because of `Node.cloneNode` does not work correctly in IE11, so `background-color` of original node will be corrupted.

#### `Node.cloneNode` does not work correctly in IE11

- Proof of concept is here : https://jsfiddle.net/smura/7uf45wjn/
- Link for IE11 : https://jsfiddle.net/smura/7uf45wjn/show/

#### Why `Node.cloneNode` causes this issue ?

[ShadowBlot of quilljs/parchment](https://github.com/quilljs/parchment/blob/master/src/blot/abstract/shadow.ts#L64) uses `Node.cloneNode` and [Block of quilljs/quill](https://github.com/quilljs/quill/blob/9a77567fe356d384074df7479c33ceac509d9351/blots/block.js#L112) uses `ShadowBlot.clone`.

When the splited node by `Node.cloneNode` is updated, the `background-color` of original node will be corrupted. (By initalizing `background-color` of next node)


### Solution

Clone by DOMParser if `Node.cloneNode` is broken. [quilljs/parchment](https://github.com/quilljs/parchment/blob/master/src/blot/abstract/shadow.ts#L64) should be updated.

```TypeScript
const IS_CLONE_NODE_BROKEN = (function() {
  const original = document.createElement('div');
  original.style.backgroundColor = '#ff5';
  
  const clone = original.cloneNode(false);
  // This will overwrite background color of the "original" in IE11.
  clone.style.backgroundColor = '';
  
  return !original.style.backgroundColor;
})();

function safeClone(source) {
  let clone = source.cloneNode(false);
  if (IS_CLONE_NODE_BROKEN) {
    const sandbox = new DOMParser()
      .parseFromString(container.outerHTML, 'text/html');
    clone = sandbox.body.childNodes[0];
  }
  return clone;
}
```

**Comment by gurkerl83** [comment]
Hi Smura, great finding, just hit the same problem. Is there any chance the solution can be integrated into quill soon. Is it possible to teach quill to use your parchment version which fixes the problem?

**Comment by smura** [comment]
Hi @gurkerl83
I'm glad to hear your praising.

Unfortunately, it seems IE 11 is not currently supported. (See https://github.com/quilljs/quill/issues/2239#issuecomment-412236210)
Since IE 11 is a deprecated browser, I think that it is a reasonable decision.

**Comment by mrjacobbloom** [comment]
In the meantime, one could do something like this:

```javascript
Node.prototype.oldCloneNode = Node.prototype.cloneNode;
Node.prototype.cloneNode = function() {
	var newElement = Node.prototype.oldCloneNode.apply(this, Array.prototype.slice.call(arguments));
	newElement.setAttribute('style', this.getAttribute('style'));
	return newElement;
};
```
