### ISSUE TITLE
Linkified text after paste is sometimes off by one character

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#1221]
I've setup a custom clipboard matcher (copying/pasting the code exactly from the [unit test that Jason has provided](https://github.com/quilljs/quill/blob/develop/test/unit/modules/clipboard.js#L114)) to automatically linkify a pasted link. It generally works.

However, when pasting certain links, the linkified text is off by one character.

My guess is the issue is not the custom matcher code since it generally works on most links. And the actual destination url when you click on it takes you to the right place (as in the destination link is not off by one character). So I suspect instead something is going awry with the paste or substitution process itself.

**Steps for Reproduction**

1. Visit quilljs.com/playground/
2. Paste the following code:
```
Delta = Quill.import('delta')

var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      ['image', 'code-block']
    ]
  },
  placeholder: 'Compose an epic...',
  theme: 'snow'  // or 'bubble'
});

quill.clipboard.addMatcher(Node.TEXT_NODE, function(node, delta) {
  let index = 0;
  let regex = /https?:\/\/[^\s]+/g;
  let match = null;
  let composer = new Delta();
  while ((match = regex.exec(node.data)) !== null) {
    composer.retain(match.index - index);
    index = regex.lastIndex;
    composer.retain(match[0].length, { link: match[0] });
  }
  return delta.compose(composer);
});
```
3. Paste the following snippet which includes 2 links:
```
<a data-flickr-embed="true" href="https://www.flickr.com/photos/16555999@N00/8708932554/in/album-72157633419841224/" title="contacts01"><img src="https://c3.staticflickr.com/9/8402/8708932554_c833b98689.jpg" width="500" height="303" alt="contacts01"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
```

**Expected behavior**:
The two urls are linkified such that the linked text starts with https:// and ends before the trailing double quote

**Actual behavior**:
The two urls are linkified, but the first character (h) of https is NOT included in the linkified text. And the trailing double quote is linkified instead. It appears that the linkified text is off by one. Yet the actual destination link url when you click on it is correct.

![screen shot 2016-12-24 at 4 39 36 pm](https://cloud.githubusercontent.com/assets/192650/21469284/96e95cd8-c9f7-11e6-8f92-d6f84e449d49.png)

**Platforms**:
Mac OS 10.12.2
Google Chrome 55

**Version**:
Quill 1.1.8

**Comment by jhchen** [comment]
One note is that you cannot actually follow step 3 from Github because it turns it into a code block so Quill will paste it as a code block. So you either have to disable code blocks with a `formats: ['link']` into the config or paste it to some plain text editor first and copy from there. In either case the matcher is working as expected for me.

![quill](https://cloud.githubusercontent.com/assets/192974/21509938/0e7a1f2e-cc43-11e6-989e-3380c70d4dd0.gif)

To aid in debugging can you add `debug: true` to the config and add what the `quill:clipboard convert` log says?

It should also go without saying that a unit test snippet should not be considered a feature.

**Comment by sachinrekhi** [comment]
Oh sorry for adding the code block to the Github issue. When I copy/paste from the original source (Flickr) the snippet isn't in a code block. So it's more akin to copying/pasting from a plain text editor with the code block format staying on.

Strange, I still seem to get the error. The debug log does show the incorrectly generated link Delta on my side.

Here is the debug log:

(Screenshot)
![screen shot 2016-12-27 at 5 37 35 pm](https://cloud.githubusercontent.com/assets/192650/21511904/5535ebf6-cc5b-11e6-89e5-84303773b93d.png)

**Comment by sachinrekhi** [comment]
Actually if you look closely at your included animated GIF, it appears that the link in your case is also incorrectly linkifying the trailing double quote.

**Comment by jhchen** [comment]
The trailing quotes being linkified is because the regular expression `/https?:\/\/[^\s]+/g` is using whitespace as a trailing delimiter. Excluding double quotes fixes this (`/https?:\/\/[^\s\"]+/g`) though you'd probably want to exclude single quotes too.

As with most cases involving regular expressions, they are usually the culprit. Again the unit test is testing for a very specific thing and is not a feature so debugging this further is beyond the scope of Quill.

**Comment by sachinrekhi** [comment]
Thanks for pointing me in the direction of the regex issue, really helpful!

In case anyone else ever runs into this, here is what I discovered regarding not including the first h in my example. It appears that Quill collapses multiple spaces into one. So it turns out when copying from Flickr the snippet had 2 spaces before href="https://www.flickr.com/photos/16555999@N00/8708932554/in/album-72157633419841224/". The addMatcher method provides both the node object and a delta object. The node object includes both spaces but the delta object has collapsed the 2 spaces into 1. Since I am matching the regex against the node object instead of against the delta object, I get the off-by-one issue I am experiencing when I compose my Delta to the delta object that has already removed the extra space.

I guess then maybe it's a better idea to match against the delta instead of the node to avoid this issue.
