### ISSUE TITLE
Font is not being applied to text inside of codeblocks

### ISSUE THREAD

**Issue by GaurangTandon** [quilljs/quill#1223]
_(Using an "interactive playground" forked pen with same 1.1.8 dependencies and cdn links)_

**Steps for Reproduction**

1. Visit http://codepen.io/anon/pen/GNbmjy
2. Type some random one (or more) line text.
3. Select the text and press the `</>` button to make it a code block.
4. Now, select the font-family dropdown to convert text from sans-serif to monospace.

**Expected behavior**:
Text appears in monospace font.

**Actual behavior**:
Text remains in sans-serif font

**Platforms**:
Chrome latest, Win 10. Quill 1.1.8

**Comment by jhchen** [comment]
Text is appearing in monospace for me. That is to say the font-family dropdown has no effect on the code block, which is the expected behavior.

To confirm is the expected and actual behaviors reported in this issue described as intended? "Text remains in sans-serif font" does not make sense since once you make it a code block in step 3 it is monospace so "remains" is a confusing verb here.

**Comment by GaurangTandon** [comment]
@jhchen Thanks for your quick response! Forgive my ignorance, I now checked the dev tools and have realized that code blocks did already have that monospace font. What made me ask this question was the visible font difference between a normal monospace text and code block monospace text:

![image](https://cloud.githubusercontent.com/assets/6308683/21512830/40187cbc-ccd7-11e6-84dd-1e800554b8f5.png)

You may close the issue, Thanks!
