### ISSUE TITLE
Remove block format from a line

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#1228]
It's not possible to remove code formatting from an empty line.
Block formatting is removed only when there is a selection range.
When the code block is at the beginning of the document, it's not possible to enter normal lines above it.

**Steps for Reproduction**

1. Visit http://quilljs.com/docs/formats/
2. Copy the following code block (three lines)
```javascript
var a = 1;

var b = 2;
```
3. Place the cursor on the second line. Click on the T<sub>x</sub> button
4. Place the cursor on the third line. Click on the T<sub>x</sub> button

**Expected behavior**:
Code block formatting should be removed from the second and third lines.

**Actual behavior**:
Both lines still formatted as code blocks.

**Platforms**:
Chrome 55 on Windows 7

**Version**:
1.1.8

**Comment by jhchen** [comment]
I think the issue is remove formatting requires at least a selection. There does not seem to be complete consistency between other editors' remove formatting feature. Some do not remove block level formats at all. There was a discussion on redesigning this in #954 but it does not seem like many people had any strong opinions.

The [documentation](http://quilljs.com/docs/api/#removeformat) is not clear about it needing to be a highlight. Perhaps that should just be clarified?

**Comment by benbro** [comment]
I've added a comment on #954.

Currently removeFormat doesn't remove block formats when the range is collapsed.
That's the only thing missing to make Quill remove format behavior ideal.
