### ISSUE TITLE
Editor contains tags on initialisation and when content is empty

### ISSUE THREAD

**Issue by CoenWarmer** [quilljs/quill#1235]
I am using Quill in an application that autosaves the contents of the editor on init and on change. 

I noticed that by default the contents of the ql-editor element is `<p><br /></p>`. So by default, these tags are being picked up by my save function and thus being saved to my backend.

Also, when entering content in the editor and then clearing it with `<control>`+`<a>` and `<delete>` or by backspacing until the beginning, the `<p><br /></p>` tags remain in the editor.

I could look for this specific combination of tags in my save function to simply pass 'null' or an empty string to my backend instead, but I'm wondering if this is the best approach. I think the case could be made that since the editor is visually empty, the output of the editor should also be empty? Interested to hear your thoughts.

**Steps for Reproduction**

1. Visit Quill playground
2. Inspect contents of ql-editor element, notice there is already `<p><br /></p>` content in the editor
3. Type something in the editor
4. Clear the contents of the editor by backspacing all content, or selecting all content and pressing delete
5. Inspect contents of ql-editor element, notice there is still an `<p><br /></p>` content in the editor

**Expected behavior**:
The contents of ql-editor is fully empty.

**Actual behavior**:
Empty paragraph and br tag present in editor

**Platforms**:
Platform / browser independent

**Version**:
1.1.9

**Comment by TheMightyPope** [comment]
The quill editor always contains a newline (at least) as per documentation. It also causes me some pain, as I try to copy Delta from one editor into another (insert), I have to manually delete the last 'newline' INSERT before doing so to avoid it being inserted. A solution that could handle a truly empty editor would be nice, I second the motion :)

**Comment by CoenWarmer** [comment]
**<Respectful *bump*>**

**Comment by jhchen** [comment]
My apologies I was trying to compose a detailed response when I saw this, but forgot to finished it.

The short of it is `<p><br></p>` representing the empty document is by design and and foundational to how Quill works. Many parts of Quill's codebase assume at any given index in a Quill document there is both a block and inline blot. So there would have to be a strong reason / benefit to a change, and more conveniently being able to detect emptiness does not hit the mark.

I'm not sure if this is still true but older browsers (that Quill supported) definitely did not work correctly with an empty contenteditable div, in that since it is empty, it is not selectable so you could not put your cursor inside and type. Some also simply rendered 0px height since there's nothing inside the editor (though there are acceptable though not ideal CSS workarounds). There are also reason why the paragraph and break tags are used but that is not relevant to their existence at all.

As to why an empty document still has '\n' there a detailed explanation in http://quilljs.com/guides/designing-the-delta-format/ (you can stop reading after the Line Formatting section, but everything before that is relevant context).

You can use quill.editor.isBlank() to check if the editor is empty but its interface is experimental and not protected by semver. Also it does not consider an editor with no text but does have a formatted line empty. For example, `<ul><li><br></li></ul>` is not empty.

**Comment by CoenWarmer** [comment]
Thank you for taking the time to write this reply. I understand the reasoning and will implement another way on my end to detect an 'empty' Quill instance.

**Comment by brylie** [comment]
We are also experiencing trouble with this, and are considering 'fixing' it on our end as well. I.e. we are stripping the block element and inline blot from our form submission. However, this seems like it would be cleaner if it were solved in Quill.

**Comment by mbbarry91** [comment]
this is what I did until we get a fix.
By checking the text, I'm able to control what I save 
`  const handleChange = (content, delta, source, editor) => {
    if(editor.getText() == null) do nothing return
    setContent(content)
  };`

**Comment by sachinbm1717** [comment]
This only happens after I enter something in editor and delete all content. I mean if I don't type anything in editor It will be null.
but when i type something in editor and delete all the quill content and text is cleared still contains {ops:[{insert:\n}]} not sure why and how?

**Comment by ProbirSarkar001** [comment]
const stripHtml = (html) => {
    const doc = new DOMParser().parseFromString(html, "text/html");
    return doc.body.textContent || "";
  };
