### ISSUE TITLE
Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined

### ISSUE THREAD

**Issue by SkyeTang** [quilljs/quill#1249]
hello:
I have a problem , when I pack the code with 'npm run build' .
then I use  quill.js in my project , this fault tips were occurd --"Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined "

and I find in the dist file quill.js have this code:
![image](https://cloud.githubusercontent.com/assets/12405329/21768994/7b89e7c4-d6b7-11e6-8a95-32cd7cbc0fb9.png)

but i search your production code version 1.1.9 on cdn  has't those code.
how can i package production files as same to you? thank you. @jhchen 
(sorry,my english is too bad.)

**Comment by jhchen** [comment]
What browser and OS are you using?

**Comment by SkyeTang** [comment]
I'm using chorme  55 in mac OS.  
there is more detail i'd like to tell you.
if  I link single source with script tag <script src="xxxx">  it's ok.
now ,my project using webpack  import quill like this.
![image](https://cloud.githubusercontent.com/assets/12405329/21792474/0e9d67ee-d725-11e6-8d09-64b6b20336ea.png)

then i bundle js ,and open browser will occurd the issues.
thanks again you answer my question .

**Comment by jhchen** [comment]
There needs to be a reproducible [report](https://github.com/quilljs/quill/blob/develop/.github/CONTRIBUTING.md#bug-reports) for this Issue to be actionable. It's not clear to me why you are importing from 'p/quill' instead of just 'quill' but a few details point to this issue simply being the result of misconfiguration in your project. But of course a reproducible case would set things straight.
