### ISSUE TITLE
Titles on buttons

### ISSUE THREAD

**Issue by CHR15-** [quilljs/quill#1271]
Is it possible for titles to appear on the action buttons, i.e hovering 'B' would reveal 'Bold'?

**Steps for Reproduction**

Visit quill, hover over any action button

**Expected behavior**:

For a title to display 'Bold' when hovering over bold

**Actual behavior**:

No title displayed

**Platforms**:

All

**Version**:

All?

**Comment by jhchen** [comment]
#650

**Comment by hughlomas** [comment]
@jhchen I've come here because there are no hover hints for the toolbar. All I see are weird suggestions like using Bootstrap tooltips or user hacks for such a basic piece of functionality. 

Just add a `title="whatever"` attribute to the buttons. It's a browser standard.

<button type="button" class="ql-bold" title="Bold">

This is so simple. Why the aversion to adding this?

**Comment by rbonomo** [comment]
It's laughable how disregarded accessibility is among the JS community
