### ISSUE TITLE
Can we have OnFocus and OnBlur events?

### ISSUE THREAD

**Issue by dons20** [quilljs/quill#1273]
This isn't really an issue, but more of a request/suggestion. It would be quite useful to know when the editor is focused or not through listeners. Any possibility of this being added?

**Platforms**:

Mozilla Firefox, Windows 10

**Version**:

1.1.10

**Comment by benbro** [comment]
You can use the [selection-change event](http://quilljs.com/docs/api/#selection-change) for that.

> A null range indicates selection loss (usually caused by loss of focus from the editor). You can also use this event as a focus change event by just checking if the emitted range is null or not.

**Comment by wilk** [comment]
@benbro unfortunately, `selection-change` is not triggered when the user clicks on the same row that has been selected.
this problem occurs when you focus on a certain node and then click inside the editor to loose the focus on the previous node: with `selection-change` this cannot be achieved if you click on the same selected row.

**Comment by abramz** [comment]
@benbro this hasn't had activity since you closed the issue while there is still very much a problem with your suggested solution.

In addition to what @wilk said... 8 months ago, there is no `selection-change` event when the editor is focused and the user clicks outside of the editor. 

This is a rich **text editor**, HTML text inputs have `focus` & `blur` events. QuillJS should too.
