### ISSUE TITLE
Completion with quill

### ISSUE THREAD

**Issue by friedrith** [quilljs/quill#1278]
Hi,

Is there a way to add completion feature in quill 1.x ? I have seen the thread #81 and I would like if something has changed.

I tried something with [At.js](https://github.com/ichord/At.js) : [here](http://codepen.io/DaneelOlivaw/pen/PWWvzN). The completion menu is perfectly displayed, however I get the following error when I choose an item :

```
Uncaught DOMException: Failed to execute 'setEndAfter' on 'Range': the given Node has no parent.
```

I have difficulties to understand this issue in quill context whereas I have no problem with At.js in another part.

I am ready to contribute to this project if it is possible to add this feature.

**Comment by jhchen** [comment]
Looking at At.js specifically, there's a few things I ran into. 

First is use Quill's text insertion instead of At.js's. I'm not sure why it is throwing the error you mentioned but Quill has an API for text insertion so it will be safer to use that. There is an option to do though it does not appear documented at the moment, so maybe it's experimental:

```js
$(quill.root).atwho({
  at: '@',
  data: ['Peter', 'Anne'],
  functionOverrides: {
    insert: function(text) {
      let range = quill.getSelection();
      quill.insertText(range.index, text, Quill.sources.USER);
    }
  }
});
```

Secondly, it seems if you use arrow keys + enter, the enter key is actually passed into the editor for some reason. This will have to be detected and prevented.

Third, something seems to be interfering with selection preservation, so the above `quill.getSelection()` returns the incorrect range sometimes. It's not clear why this is happening but will naturally have to be addressed.

Without using At.js, in general you would need to:

1. Trigger showing the completion dropdown
2. Render and position the dropdown
3. Detect selecting an item from the dropdown
4. Insert text into Quill.

You could use a [keyboard API](http://quilljs.com/docs/modules/keyboard/) to accomplish 1, `quill.getBounds()` is half of 2, 3 is work with handling all the keyboard and mouse interactions but fairly straightforward, 4 can be done with `quill.insertText`.

**Comment by ThibaultFriedrich** [comment]
Thx for your very accurate answer. I didn't know the `functionOverrides` field from At.js. I have experiment you the enter issue but not the selection inteference yet.

I will find the best way to integrate completion in quill and post the answer here.

**Comment by ThibaultFriedrich** [comment]
I try to prevent tab and enter in quill when the the completion dropdown is displayed but I am experimenting a weird behavior.

I have no problem to binding letters like 'a', '*', etc but it seems to doesn't work for enter or tab.

This is a codepen : http://codepen.io/DaneelOlivaw/pen/VPPOpw

Notice that in the codepend I use keyCode but I also tried with 'tab', Keyboard.keys.ENTER, Keyboard.keys.TAB.

Do you any idea about the origin of this issue ?

**Comment by jhchen** [comment]
Quill has default handlers for enter and tab so if you add yours after initialization, it will never get to run. There's an Issue to discuss adding some sort of priority to addBinding but right now you have to pass them into the configuration for it to run before Quill's: http://codepen.io/quill/pen/qRmEBr

**Comment by thibaultfriedrich** [comment]
Ok I will try it but does it remove default bindings because I would to keep the current behavior and just add some improvements. 

Moreover, I find the documentation with ENTER binding disturbing if it is not possible: [https://quilljs.com/docs/modules/keyboard/#empty](https://quilljs.com/docs/modules/keyboard/#empty). Maybe it could be more accurate to change the key of the binding in the documentation.

Finally is it the same with all key which are not characters like BACKSPACE, etc ? or it is only tab and enter ?

**Comment by thibaultfriedrich** [comment]
Thanks a lot. ENTER binding works very well in standalone now. I am gonna to make it working with At.js now.

**Comment by adamkdean** [comment]
FYI functionOverrides was removed from At.js, so you'll have to use the latest version (not released yet) if you want to use this.
