### ISSUE TITLE
Quill stripping image class

### ISSUE THREAD

**Issue by ajgagnon** [quilljs/quill#1325]
It seems quill strips classes off images when it's initialized. Is there a way around this? Is this expected behavior?

**Steps for Reproduction**

1. Visit http://codepen.io/anon/pen/OWeqOp
2. Image class is removed when quill is initialized

**Expected behavior**:
Image class isn't stripped

**Actual behavior**:
Image class is stripped

**Platforms**:

All

**Version**:
1.1.4

**Comment by jhchen** [comment]
This is expected behavior and not really a way around it. All markup in Quill has to have meaning Quill understands or else it is liable to be discarded on rendering. If there **is** meaning to the classes you would define and register a [class attributor](https://github.com/quilljs/parchment#class-attributor).

**Comment by ajgagnon** [comment]
Appreciate the helpful response! 👍 😄

**Comment by cpinto-cb** [comment]
@jhchen What is the solution to my problem.
I have added this code -> 
    var Token = Quill.import('formats/image');
    Token.className = 'token';
    Token.blotName = 'img-token';
    Quill.register(Token);

And that works, but it is stripping the alt tags now.

How do I change that little bit of code to get the alt tags back?
