### ISSUE TITLE
Unexpected behavior when pressing line break at the ending of paragraph

### ISSUE THREAD

**Issue by vasconita** [quilljs/quill#1340]
Unexpected behavior when pressing line break at the ending of paragraph

It's related to #1339, but I created two issues because I'm not sure if it's the same problem.

**Steps for Reproduction**

1. Visit quilljs.com
2. Write a line with heading style
3. Enter line break
4. Write other line

![breakeline1](https://cloud.githubusercontent.com/assets/7622399/23453254/ec5b3af2-fe67-11e6-9ad8-5116c71f10fd.gif)

**Expected behavior**: I expect to preserve my heading style.

**Actual behavior**: It changes the style of my paragraph to normal

**Platforms**: Google Chrome 56.0.2924.87 (64-bit) in Windows 10

**Version**: 1.2.2

**Comment by borodean** [comment]
Not a Quill contributior, but I think this behavior is valid – Word and Google Docs behave the same way. To split the heading and keep the style you should insert an _actual_ line break – `shift` + `enter`.

**Comment by jhchen** [comment]
Yes the two issues are separate so thank you for creating two. As @borodean suggested this was intentionally added in #540. You can override this behavior if you'd like with a [keyboard config](http://quilljs.com/docs/modules/keyboard/). Note from the docs, because enter is specially handled, it will have to be specified in the configuration, not with `addBinding`.

**Comment by vasconita** [comment]
Thank you very much, I'll override this behavior with a keyboard config :)
