### ISSUE TITLE
Safari 10.1 reports incorrect range on "selection-change"

### ISSUE THREAD

**Issue by montlebalm** [quilljs/quill#1387]
In Safari 10.1 the "selection-change" event is reporting a range of `{ index: 0, length: 0 }` _after_ the first character is typed. This appears to be a recent regression in Safari 10.1. The range is correct after typing subsequent characters.

![screen shot 2017-03-30 at 3 24 27 pm](https://cloud.githubusercontent.com/assets/739390/24528928/bb06a4d4-155d-11e7-94ec-72cf041cb069.png)

**Steps for Reproduction**

1. Visit https://codepen.io/montlebalm/pen/ryoxeB
2. Type "a" into the input

**Expected behavior**:

The reported range should be `{ index: 1, length: 0 }`.

**Actual behavior**:

The reported range is `{ index: 0, length: 0 }`.

**Platforms**:

Broken: Safari 10.1
Working: Safari 10.0.3, Chrome 57

**Version**:

Version 1.2.3

**Comment by montlebalm** [comment]
Looks like this also happens for the first character on every line.

**Comment by jhchen** [comment]
Thanks for the detailed report and codepen.

The issue is `selection-change` actually happens after `text-change`. Since `text-change` can cause a `selection-change`, the selection code depends on `text-change` in order to update itself. It seems like in previous versions of Safari and Chrome, the browser did the right thing and did not require reconciliation from Quill. I'll add a couple sentences to the text-change docs to note this for posterity.

I'm assuming the reason you are listening on `text-change` and querying `getSelection` instead of just listening on `selection-change` is you want to get silent events? In that case I would recommend the [`editor-change`](https://quilljs.com/docs/api/#editor-change) event. This goes without saying but since these events fire very frequently, the handlers should be very fast so similar caution given to stuff like the DOM's `scroll` or `mousemove` events should be given here.

Either way you can see the example here: http://codepen.io/quill/pen/vmNLyK

**Comment by montlebalm** [comment]
@jhchen thanks for the explanation. I'll look into switching my "text-change" handlers and see if it resolves the problem.

**Comment by montlebalm** [comment]
> I'm assuming the reason you are listening on text-change and querying getSelection instead of just listening on selection-change is you want to get silent events?

I'm listening to "text-change" so I can react to specific characters being typed (e.g., "@"). I can't listen to "selection-change" exclusively since it doesn't fire on (all) user typing.

I need to grab all the text from the start of the input up to the cursor including what was just typed. I was hoping to avoid making the "text-change" handler async.
