### ISSUE TITLE
[Firefox Mobile] Cursor jumps back

### ISSUE THREAD

**Issue by gofabian** [quilljs/quill#1423]
If I write text after some single newlines the cursor will jump in front of the newlines. The text will be input in front of the new lines, too.

This issue is reproducible in Firefox Mobile only (version 53.0, Android). I cannot reproduce it with Chrome on Android.

**Steps for Reproduction**

1. Visit http://quilljs.com/playground/#autogrow-height
2. Focus in playground "result"
3. Enter some newlines via "return" on Android keyboard
4. Enter text

**Expected behavior**:
The text will be input after the newlines.

**Actual behavior**:
Cursor jumps back. The text will be input in front of the newlines. 

**Platforms**:
Sony Xperia Z5 Compact (E5823)
Android 6.0.1
Firefox Mobile (v 53.0)
cannot reproduce with Chrome

**Version**:
Quill 1.2.4

<img src="https://cloud.githubusercontent.com/assets/3092660/25308378/1c6b5870-27b3-11e7-9a82-98c5fa4093d2.png" width="200"> <img src="https://cloud.githubusercontent.com/assets/3092660/25308377/1c68b962-27b3-11e7-8673-b58280239046.png" width="200"> <img src="https://cloud.githubusercontent.com/assets/3092660/25308379/1c6fe840-27b3-11e7-9678-b3f6e4802b45.png" width="200">

**Comment by jhchen** [comment]
What version of Android is this?

**Comment by gofabian** [comment]
Sony Xperia Z5 Compact (E5823)
Android 6.0.1

**Comment by gofabian** [comment]
Same on another smartphone with Android 4.4.2 and Firefox Mobile 53.0

**Comment by adrien-n** [comment]
I'm getting the same on latest Firefox available on F-Droid and Android 7.1 (latest OxygenOS from OnePlus) but I've had it for at least a couple months (i.e. probably always because I haven't used Quill for much more than that).

I'll try to take a look at the issue but I'm currently a bit busy and not very familiar with debugging on mobile so it's not unlikely someone will beat me to it.

**Comment by gofabian** [comment]
The referenced pull request seems to resolve this issue. I cannot reproduce it using Firefox 54.0.1 and quilljs 1.3.0 . 

Should we close the issue?

**Comment by jhchen** [comment]
Sounds good thanks!

**Comment by adrien-n** [comment]
The problem actually still exists with FF 50 on Android. This is the version currently shipped through F-Droid because of build or builder woes with newer versions.

I don't know if you support such configurations. I would definitely understand you don't (FF is a difficult package but mobile applications usually have a good update rate).

**Comment by jhchen** [comment]
Firefox on Android is not officially supported due to it not being a supported platform on SauceLabs, which we use to automate. I do try to fix Firefox bugs in general though since it is a pleasant enough development environment. However even so the browser version policy is last two versions, which right now is 54 and 53.
