### ISSUE TITLE
Unordered list does not change list-stype-type when indented

### ISSUE THREAD

**Issue by JordyVlassembrouck** [quilljs/quill#1425]
When indenting an ordered list, the list-style-type switches between decimal, lower-alpha and lower-roman. 
However, when indenting an unordered list, the list-style-type stays the same.

It would be logical to switch between disc, circle and square when indenting an unordered list.

**Steps for Reproduction**

1. Visit [https://quilljs.com/docs/formats/]
2. Enter some text in the Quill editor.
3. Create an unordered list of your text with the bullet-list button.
4. Indent this list entry and see that the list-style-type stays the same.

**Expected behavior**:
The list-style-type should switch between disc, circle and square when indenting an unordered list.

**Actual behavior**:
The list-style-type does not switch between disc, circle and square when indenting an unordered list.

**Platforms**:
I have included the browsers that I have tested, but this is not caused by browsers. This is merely the cause of lacking functionality.

Chrome for Mac, Version 57.0.2987.133
Firefox for Mac, Version 48.0.1
Safari for Mac, Version 10.1 (12603.1.30.0.34)

**Version**:

Version 1.2.4

**Comment by jhchen** [comment]
Only numbered list styling is supposed to change at the moment though of course we would could make bulleted styling change with indentation as well. You can already define CSS rules to control the bullet style what this really means is what Quill does by default and I'm not sure the majority of people would prefer a non-disc bullet style since so few applications and websites render lists this way.

Please thumbs up or down this issue to indicate your preference (up: alternate disc style, down: keep as is).

**Comment by jhchen** [comment]
Looks like we should keep as is at least for now. Again changing it for your own application is just a matter of defining your own css rules for `indent-1`, `indent-2`, etc.
