### ISSUE TITLE
Can't find the "setHTML" function.

### ISSUE THREAD

**Issue by crowdwave** [quilljs/quill#1449]
Hello

I can't seem to find the "setHTML" function.

Here's a screenshot in Chrome.  I would have expected it to be displayed next to setText.

Can anyone suggest what I am doing wrong?

![image](https://cloud.githubusercontent.com/assets/13228330/25829969/0ac36724-349d-11e7-98b7-282531b83584.png)

thanks

**Comment by crowdwave** [comment]
Hmmm....  it looks like this function is perhaps not in the latest version of Quill?

How then can I set the HTML programatically?  I'm trying to load the initial data into the control upon load.

thanks!

**Comment by benbro** [comment]
https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml

**Comment by crowdwave** [comment]
For those who might come later on.......

The actual problem that I was trying to solve is how to save data from quill and restore it next time quill is loaded.  I assumed that the right way to do this was to save the HTML and then write it back somehow.

Further learning appears to indicate that in fact the correct way to load and save data is to save quills "delta" object in your database or whereever and this delta can be reloaded via "setContent()"

**Comment by shivavelingker** [comment]
![image](https://user-images.githubusercontent.com/6578523/34399623-92787ec6-eb4e-11e7-8460-d3b92221ff2d.png)

Within the clipboard module, I see no function called `dangerouslyPasteHTML`, especially since the API says you just need to run `quill.clipboard.dangerouslyPasteHTML(5, '&nbsp;<b>World</b>');`. Where is the function being stored?

**Comment by rw3iss** [comment]
... but saving/loading of delta does not offer a way to somehow preview the contents in some other way, elsewhere (ie. outside of Quill). I think the only solution to that would be to save two fields for the data (one with the delta, one with getting the innerHTML of the editor). Does anyone know a way otherwise to store as one field, ideally html, and then be able to load it into Quill again later, as HTML?

**Comment by gustawdaniel** [comment]
In my opinion methods to `get` and `set` HTML should be described in official docs. 

Of course with notice that using these methods is bad practice.

But It is confusing if it is not described at all.

**Comment by shepelevstas** [comment]
I use Quill with Vue and I need to store html in db because often I just want to show formatted rich text (not editable). So I just paste it in div.ql-container > div.ql-editor. And sometimes I save the initial content and then I want to "Discard Changes" and set editor content back to the initial. So the setHtml function that would not trigger text-change event would be very helpful. Now I have to do something ugly like this:
```js
// when the Vue component with Quill editor is mouted
this.$refs.editor.innerHTML = this.value
this.quill = new Quill(this.$refs.editor, {})
this.quill.on('text-change', ()=>{
  this.notUserInput = true
  this.$emit('input', this.$el.querySelector('.ql-editor').innerHTML)
})

// and then watching for external changes
value(val){
  if (!this.notUserInput){
    this.$el.querySelector('.ql-editor').innerHTML = val
  } else {
    this.notUserInput = false
  }
}
```

**Comment by Toemsel** [comment]
> In my opinion methods to `get` and `set` HTML should be described in official docs.
> 
> Of course with notice that using these methods is bad practice.
> 
> But It is confusing if it is not described at all.

I don't see why that should yield any bad practice. The quill editor isn't famous for its security, hence we need to extract the html in order to sanitize it. As long as the user has 100% access to the editor and its code, security is not an argument to me.

However, the server should validate every user's input. And that does include the quills content as well.

**Comment by praveenkpatare** [comment]
If you are trying to bind the content of quill editor to a value, so that it gets loaded on any event you can try this..
<div id=<<id>> bind:this={editor} bind:innerHTML="{<<value>>}" contenteditable="true"/>
