### ISSUE TITLE
Move from DEFAULT_BLOCK_TAG = 'DIV' to Block.tagName = 'P'

### ISSUE THREAD

**Issue by lcpriest** [quilljs/quill#1470]
Why did the default block tag change from 'div' to 'p'?

I've done a bit of a deep dive to figure out when it happened - it looks like blots were added in this commit: e36fb12605308a2e5c0eb9dd1b5b9e817e06be1c.

The new `blots/block` code was added using 'p' as the default tag, [here](https://github.com/quilljs/quill/blob/e36fb12605308a2e5c0eb9dd1b5b9e817e06be1c/src/blots/block.coffee#L5). At the same point in time, the existing code still used the 'div' tag as the default block tag [here](https://github.com/quilljs/quill/blob/e36fb12605308a2e5c0eb9dd1b5b9e817e06be1c/src/lib/dom.coffee#L357).

I have no argument to support either decision - I personally want to use 'div' and would like to read/understand the reasons behind changing so I don't accidentally introduce a bug into my own implementation.

Thanks for the great (and beautiful) editor, I really appreciate all the work that has gone into it.

**Comment by jhchen** [comment]
Quill 1.0 allowed for much more support and customization different tags/DOM nodes (no longer hard-coding `div`) and it became more of a question of what should be default. There is a minor technical benefit on not using `<div>` because the root Scroll Blot uses `<div>` but this is easily disambiguated by specifying a className (which the Scroll Blot does). A lot of users also pushed for `<p>` because it was more semantic so it became default in 1.0.

**Comment by lcpriest** [comment]
Thanks!
