### ISSUE TITLE
Feature Suggestion: replace getIndex(blot: Blot): Number with getRange(blot: Blot): { index: Number, length: Number }

### ISSUE THREAD

**Issue by amitm02** [quilljs/quill#1486]
Feature Suggestion: 

Replace:
`getIndex(blot: Blot): Number `
With:
`getRange(blot: Blot): { index: Number, length: Number }`

So the user can get both start and end of a bolt instead of just the start.

**Comment by jhchen** [comment]
Thank you for the suggestion. This is easy enough to implement as there already is `blot.length()` so this API would just be a shorthand for getIndex(blot) and blot.length().

I don't want to replace `getIndex()` because `length()` is not free performance-wise especially if the blot has many descendants. Adding `getRange` is problematic as well since range usually refers to the user's selection in editors. `getIndex` itself is still experimental so I'd like to avoid the confusion and addition to the API namespace for now, especially if the benefit is just for shorthand purposes.
