### ISSUE TITLE
Incorrect numbered list ordering when un-indent intermediate item

### ISSUE THREAD

**Issue by sachinrekhi** [quilljs/quill#1508]
When you un-indent an intermediate list item, the subsequent list number ends up being labeled incorrectly.

**Steps for Reproduction**

1. Visit quilljs.com
2. Replace editor content with the following:
<img width="201" alt="bullets 1" src="https://user-images.githubusercontent.com/192650/27110378-bacc4038-505d-11e7-9db1-05384faf3c37.png">

3. Un-indent b

**Expected behavior**:
Expect the last indented bullet to be labeled a

**Actual behavior**:
The last indented bullet is incorrectly labeled b
<img width="181" alt="bullets 2" src="https://user-images.githubusercontent.com/192650/27110385-bf32c516-505d-11e7-876e-1cebc8f0bf41.png">

**Platforms**:
Chrome 58, Mac OS X 10.12.4

**Version**:
Quill 1.2.6

**Comment by dchenk** [comment]
I noticed this issue too. It's very bad.

The problem is with the way Quill is rendering lists in general. I think the "ql-indent-#" classes should be abandoned completely, and instead lists should properly _nest_ other lists (inside if `li` elements).

For example, Quill.js currently turns this:
```
[
 {"insert":"aaa"}, {"attributes":{"list":"ordered"},"insert":"\n"},
 {"insert":"bbb"}, {"attributes":{"list":"ordered"},"insert":"\n"},
 {"insert":"ccc"}, {"attributes":{"indent":1,"list":"bullet"},"insert":"\n"},
 {"insert":"ddd"}, {"attributes":{"indent":1,"list":"bullet"},"insert":"\n"},
 {"insert":"eee"}, {"attributes":{"list":"ordered"},"insert":"\n"}
]
```
into this:
```
<ol>
 <li>aaa</li>
 <li>bbb</li>
</ol>
<ul>
 <li class="ql-indent-1">ccc</li>
 <li class="ql-indent-1">ddd</li>
</ul>
<ol>
 <li>eee</li>
</ol>
```
But it should render one list like this:
```
<ol>
 <li>aaa</li>
 <li>bbb</li>
 <li>
  <ul>
   <li>ccc</li>
   <li>ddd</li>
  </ul>
 </li>
 <li>eee</li>
</ol>
```
This second way is simpler, leaner HTML and makes the item ordering easier. Currently the editor uses weird CSS things like `counter-reset: list-1 list-2 list-3 list-4 list-5 list-6 list-7 list-8 list-9` and `counter-increment`. But simply nesting lists correctly would eliminate the need for this CSS.

**Comment by jhchen** [comment]
There are actually tradeoffs to nesting or flattening and Quill went with the simpler approach. Place your proposed HTML into a renderer. I don't think it will be the result you are expecting.

**Comment by dchenk** [comment]
@jhchen ok, I see where you're coming from.
