### ISSUE TITLE
Quill inside nw.js: Cursor does not move forward when typing at the end of a line.

### ISSUE THREAD

**Issue by jomuel** [quilljs/quill#1519]
I embedded quill in a node-webkit (nw.js) application. When trying to type at the end of a line, the cursor does not move forward but stays in front of the typed letter. 

**Steps for Reproduction**

1. Initialize an empty directory as a nw.js application and import quill: run

npm init -y
npm install --save quill

2. Create a minimal html page named  "index.html" that loads quill with this script:

<script>
	var Quill = require("quill");
	var quill=new Quill(document.getElementById("editor"));
</script>

and make it the start point: 

"main": "index.html" 

in package.json.

3. Run the nw command in the directory to start and try typing into the empty line of the quill element.

**Expected behavior**:

Cursor moves along with the line end when expanding a line by typing.

**Actual behavior**:

The cursor stays in front of the first typed letter, then moves normally as it is no longer at the end of the line. E. g. typing "Quill" yields "uillQ".

**Platforms**:

nw.js on Ubuntu 16.10 ("sdk build flavor" of nw.js)

**Version**:

1.2.6

**Comment by jhchen** [comment]
We're going to need the help of members of the community who use nw.js to help make it work with Quill. Some steps to start are 1) steps to set up a development environment 2) get the Quill test suite to run on it 3) automate testing.

**Comment by erikreagan** [comment]
I've experienced this as well without the context of nw.js.

Example video: http://d.pr/v/eFa1n2

**Comment by jhchen** [comment]
What browser + OS is that in @erikreagan?

**Comment by f1hornet** [comment]
I'm seeing the same behavior? has there been a resolution to this issue?

thanks

John

**Comment by benjismith** [comment]
I use Quill extensively in NWJS and I haven't experienced this problem. However, my project structure is somewhat different.

You're probably experiencing some weirdness because of difference between browser-context and node-context. NWJS has [two different execution contexts](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/) for javascript, and you have to carefully manage the boundary between those contexts.

Rather than installing Quill with NPM, I downloaded a tarball from the [releases page](https://github.com/quilljs/quill/releases) and unpacked it into a `vendor` directory. Then I use a `script` tag to include the Quill javascript into my main html.

```
<!DOCTYPE html>
<head>
  <meta charset="utf-8">

  <!-- jquery -->
  <script src="vendor/jquery-3.1.1.min.js"></script>
  <script src="vendor/jquery-ui-1.12.1.min.js"></script>

  <!-- quilljs -->
  <link rel="stylesheet" href="vendor/quill.core-1.3.3.css">
  <script src="vendor/quill-1.3.3.js"></script>

  <!-- custom css -->
  <link rel="stylesheet" href="my-app.css">

  <!-- application startup script -->
  <script src="main.js"></script>

</head>
<body>
</body>
</html>
```

My own `main.js` file is also included via a `script` tag, so that I can capture all the browser globals, and then pass them into my `Application.js`, which uses the nwjs `require` to build its own module hierarchy

*main.js*
```
var Application = require('./lib/Application');
$(document).ready(function () {
  Application.initialize({
    "JQUERY" : $,
    "WINDOW" : window,
    "DOCUMENT" : document,
    "QUILL" : Quill
  });
});
```

And finally, my `Application.js` module manages access to those browser globals, builds the GUI, etc.

```
var Application = (function() {

  var $, window, document, Quill;
  function initialize(BROWSER_GLOBALS) {

    $ = BROWSER_GLOBALS.JQUERY;
    window = BROWSER_GLOBALS.WINDOW;
    document = BROWSER_GLOBALS.DOCUMENT;
    Quill = BROWSER_GLOBALS.QUILL;

    setTimeout(startup, 1);
  }

  function startup() {
    // LOTS OF OTHER STUFF HERE...
    createQuillEditor("my-document-id");
    // LOTS OF OTHER STUFF HERE...
  }

  function createQuillEditor(documentId) {
    var editor = new Quill("div#editor-" + documentId);
    editor.on("text-change", function(delta, before, source) {
      onDocumentTextChanged(documentId, delta, before, source);
    });
  }

  function onDocumentTextChanged(documentId, delta, before, source) {
    // LOTS OF OTHER STUFF HERE...
  }

  exports.initialize = initialize;

})();
```

Try that out, and see if it works for you... In my experience, NWJS and Quill work really well together already!

**Comment by briantsai-rep** [comment]
Running into the same problem without context of nwjs, any tips on a solution? Running Quill on Chrome and Mac OSX.

**Comment by benjismith** [comment]
@briantsai-rep If you post a minimal example, I'll take a look and see if I can help.
