### ISSUE TITLE
User is not allowed to input minus folowed by the spacebar.

### ISSUE THREAD

**Issue by fiurrr** [quilljs/quill#1538]
After user type minus followed by a spacebar, content is automatically interpeted as a bullet list. After removing bullet list formating, '-' sign dissapear. I was looking into doc and coundn't find a way to remove/disable/override that behavior.

Is there any way of doing this, handling user input, or overriding bullet list behaviour?
The only way to do this is type 'something - 30%' and then remove something;

**Steps for Reproduction**
1. try to type in into editor: '- 50%'

**Platforms**: 
Chrome 58 on Windows 7

**Version**:
Quill 1.2.6

Would appreciate any input, thanks!

**Comment by jhchen** [comment]
To answer the question about overriding, you can [customize](https://quilljs.com/docs/modules/keyboard/) the keyboard shortcuts or supply a custom [module](https://quilljs.com/docs/modules/). However I also made a change so that you can undo the automatic conversion. Just type "- 50%" and then control+z to undo.

**Comment by jhchen** [comment]
Not sure why Github did not link the commit: https://github.com/quilljs/quill/commit/7c7235e8c7d2005f764ba76542e63957d36719b7
