### ISSUE TITLE
Inserting text via API while toolbar dropdown is open does not update selection range

### ISSUE THREAD

**Issue by mdpye** [quilljs/quill#1542]
Inserting text via API while toolbar dropdown is open does not update selection range.

On selecting a format to apply, it is applied to the wrong text.

I would be happy to work on a fix if some hints can be given as to where to start.

**Steps for Reproduction**

1. Visit quilljs.com playground
2. Open your browser JS console
3. Type "this test" in to editor
4. Select chars 5 through 9 (`test`)
5. Click on the text size dropdown in the toolbar
6. In the browser console, execute `quill.insertText(5, 'oops ')`
7. Click on the "Large" option from the text size dropdown

**Expected behavior**:

The word `test` is rendered in large font.

**Actual behavior**:

The word `oops` is rendered in large font.

**Platforms**:

Chromium Version 58.0.3029.110 Built on Ubuntu, running on Ubuntu 16.10 (64-bit)
Also witnessed on Firefox for Ubuntu.

**Version**:

1.2.4. Also tested on `develop@0b2af05`

**Possibly related**:

https://github.com/quilljs/quill/issues/1397
https://github.com/quilljs/quill/issues/1290

**Comment by jhchen** [comment]
Not sure about solutions yet but looked into the cause. When the dropdown picker is clicked, focus changes to it so the last selection is saved, represented by an index and length. There's currently one Text DOM node with value "this test" and this is modified when insertText is called. Since the DOM node changed, the native selection is lost too. So when Large is finally clicked the best we have is the last saved selection which now has an outdated index and length.

**Comment by mdpye** [comment]
Without much knowledge of the architecture, the obvious fix appears to be to transform the saved selection appropriately when the contents of the editor are manipulated. However, from what you say about native selection and fall-back to a saved selection, I imagine this is not completely straightforward if there isn't a single source of truth.

Still happy to work on a patch if you can give a quick overview of how selections are handled in general.
