### ISSUE TITLE
Bad html block render with a specific set of ops

### ISSUE THREAD

**Issue by krichprollsch** [quilljs/quill#1558]
Hello here,

First thank you for Quill, it's a fantastic editor and we love use it :taco: 

With this specific list of operations, I have a bad render with quill:

```json
[
  {"insert":"a"},
  {"retain":1,"attributes":{"header":1}},
  {"insert":"b"},
  {"insert":"\n","attributes":{"code-block":true}},
  {"insert":"c\n\n"},
  {"insert":"d","attributes":{"bold":true}},
  {"insert":"e"}
]
```

The position index seams unsynced with our sharedb server and the edition of this document break the server version :/

**Steps for Reproduction**

https://codepen.io/krichprollsch/pen/gRvjbd

**Expected behavior**:

I'm not very sure of the exact html render expected, but I suppose it's something like:

```html
<h1>a</h1>
<pre>b</pre>
<p>c</p>
<p><strong>d</strong>e</p>
```

**Actual behavior**:

```html
<h1>a</h1>
<pre>b</pre>
<p>c</p>
<p>d</p>
<p>e</p>
```

**Version**:

`1.2.6`

**Comment by jhchen** [comment]
Your input is not valid since it has a `retain` in it. When setting contents you are going from nothing to the contents you specify. Retain means keep text but there is nothing to keep since you are starting from nothing. How the retain is getting there is what you have to track down in your application code.

**Comment by krichprollsch** [comment]
Hum well I see, I will search in this direction now.
Thank you for your response :+1:

**Comment by guillaumepotier** [comment]
Hi @jhchen, I'm working with @krichprollsch on that issue :)

I understand why our input seems wrong. But these are the Deltas/Ops that Quill generate on this simple use case:

1- get an empty document
2- enter "a" letter
3- format as heading

You can test it on quilljs.com homepage.

Put a `quill.on('text-change', (delta, oldDelta, source) => { console.log(delta) })`

 in your console and watch the outputs, you'll have:

``` 
{"ops":[{"insert":"a"}]}
{"ops":[{"retain":1},{"retain":1,"attributes":{"header":1}}]}
```

Fortunately, a `quill.getContents()` seems to output the desired Delta:
```
{"ops":[{"insert":"a"},{"attributes":{"header":1},"insert":"\n"}]}
```

But, in our case, we work with shareDB (that uses through `rich-text` quill-Delta) and the quill-delta compose is producing a **wrong output**:

```js
const Delta = require('quill-delta');                                            
                                                                                 
var a = new Delta([{"insert":"a"}]);                                             
var b = new Delta([{"retain":1},{"retain":1,"attributes":{"header":1}}]);        
                                                                                 
var composed = a.compose(b);                                                     
                                                                                 
console.log(composed); 

// the result is
// Delta {
//  ops: [ { insert: 'a' }, { retain: 1, attributes: [Object] } ] }
// this is BAD
```

That's why when we start our page and that our editor populates content from shareDB with `quill.setContents(shareDBDocument.data)` it populates this wrong input from above. `quill.getContents()` still output a good output (how's that, it do not uses same quill-delta mechanisme as rich-text?). But as @krichprollsch explained with its example above, with some others operations, it becomes a mess.

What are we missing here?

Thanks for your time and your help

**Comment by calibr** [comment]
Looks like that is because a quill delta always ends with "\n", therefore an empty document contains the delta:

`{"insert":"\n"}`

When you type the "a" letter your editor actually contains this delta

So, if you add this missing part to your compose chain you will get the expected result:

```js
const Delta = require('quill-delta');

var a = new Delta([{"insert":"\n"}]);
var b = new Delta([{"insert":"a"}]);
var c = new Delta([{"retain":1},{"retain":1,"attributes":{"header":1}}]);

var composed = a.compose(b).compose(c)
// {"ops":[{"insert":"a"},{"insert":"\n","attributes":{"header":1}}]}
                                  
```

more info here https://quilljs.com/guides/designing-the-delta-format/

**Comment by jhchen** [comment]
@calibr is correct -- the empty document in Quill is a newline. 

> Put a quill.on('text-change', (delta, oldDelta, source) => { console.log(delta) })

> in your console and watch the outputs, you'll have:

I'm not sure by this if you are saying the output is incorrect. If so then there may also be a misunderstanding between using Deltas to represent change and to represent state. The output pasted from the result of `console.log(delta)` is the expected and correct output.

**Comment by guillaumepotier** [comment]
Thanks @calibr and @jhchen for your answers. Our problem might come from the first `/n` omission in our code within shareDB. We'll look today in that way.

Dunno how users do, but in our case we blindly do like said above a `quill.setContents(shareDBData)` and on an empty document, `shareDBData = {"ops":[]}`. Quill handle that by adding its `/n` automatically and then our ops in sharedb are missing that insert. We'll find a way but I think it might be a common mistake for others.

@jhchen regarding `var c = new Delta([{"retain":1},{"retain":1,"attributes":{"header":1}}]);`, it seems wrong because of the two retains in the instructions. I'll re-read the delta documentation but I would have expected something more like just `var c = new Delta([{"retain":1,"attributes":{"header":1}}]);`, that's why I said it seemed wrong and I suspected that line to cause our later problems with the document.

I'll keep you posted. Best

**Comment by jhchen** [comment]
`new Delta([{"retain":1},{"retain":1,"attributes":{"header":1}}])` is not equal to `new Delta([{"retain":1,"attributes":{"header":1}}])`. The helpful link @calibr posted will explain the difference.
