### ISSUE TITLE
How to set a cursor: no-drop when drag and drop is disabled?

### ISSUE THREAD

**Issue by Natim** [quilljs/quill#1582]
**Steps for Reproduction**

1. Visit https://jsfiddle.net/t7dkr266/
2. Try to drag and drop something
3. If you go up the toolbar you can see the `no-drop` cursor, however you see the default `alias` one.

**Expected behavior**:

It should use the `no-drop` cursor on the quill.js panel.

**Actual behavior**:

It keeps showing the alias pointer while the css `no-drop` one is configured.

**Platforms**:

Firefox, Ubuntu

**Version**:

1.2.6

**Comment by jhchen** [comment]
Can you specify exactly what should be dragged and where it should be dropped in step 2? I'm not getting the classes to update at all.

**Comment by Natim** [comment]
Sure.

> what should be dragged

a selection of text for instance that you would drag into the quill.js

**Comment by jhchen** [comment]
When I try to drag a selection of text, the selection just changes. I tried with an image though onto a textarea though with no Quill involvement: https://jsfiddle.net/0718fzou/. The forbid-cursor class is added but the cursor rendering does not change either so unclear if there is an issue with a lower layer or the example code.

I am using Firefox on Mac instead of the stated Firefox on Ubuntu.

**Comment by Natim** [comment]
I can confirm a similar behaviour with Chrome.

**Comment by Natim** [comment]
I opened the following Bug for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1381759

**Comment by Natim** [comment]
I guess we can close the issue because it is not related to Quill.js
