### ISSUE TITLE
Add header and footer + page break

### ISSUE THREAD

**Issue by maximeozenne** [quilljs/quill#1618]
Hi, thanks for your editor it's wonderful !

For my needs I have to automatically add custom header/footer on each page. Is there a way to do this ?
Also I need that my users can accurately see when they will have a page break, is this feature planned ?

**Comment by jhchen** [comment]
Can you elaborate on the custom footer/header? We are not planning to add page break indicators.

**Comment by maximeozenne** [comment]
As it's done in Word Online, you can click on "Header & Footer" under the "Insert" Tab : 

![7ec96681-4153-4e28-8625-4dc39b67a174](https://user-images.githubusercontent.com/12842987/29020505-8a2b8486-7b62-11e7-8bed-1ce87a573944.png)

It opens 3 textboxs where you can write text at the left, middle or right of the header. This text will be placed at the top (or bottom if you filled the footer textbox) of each page during the print process.

But without the page break indicator, I'm not sure this feature would be useful. Anyway I handled it by adding my custom header skeleton on the html code so my users can fill it with the help of the bubble theme.

**Comment by jhchen** [comment]
Glad you are able to solve it externally and it does seem like the right approach. Quill will lack some features a full word processor like Word has and it is not a goal to fill them all. Which ones to include or not is on a case by case basis but this one specifically sounds like it would be better handled in the application rather than the core editor like you are doing.
