### ISSUE TITLE
Text formatting stops working correctly if selection ends outside of document [Chrome]

### ISSUE THREAD

**Issue by mitjaz** [quilljs/quill#1645]
It's not possible to apply formatting if user is selecting text and releases mouse outside of the document where quill was instantiated, or outside of the browser window. Quill events don't seem to be fired anymore after such action.

**Steps for Reproduction**

1. Visit quilljs.com and open any of the playground cases
2. Start selecting text - hold down mouse
3. Release mouse outside of the browser window or outside of the document where instance was created
4. Select some text and try to format it

**Expected behaviour**:
Formatting text should works as intended

**Actual behaviour**:
Not possible to format selection with buttons, keyboard formatting works correctly

**Platforms**:
Chrome 60.0.3112.90
OSX 10.12.5 & Windows 10

**Version**:
1.3.1

**Comment by benbro** [comment]
What do you mean by "Quill stops responding"?

In my test the selected text isn't getting attributes if releasing the mouse outside the browser window:
1. Visit https://quilljs.com/ or https://quilljs.com/playground/
2. Type the word "test" in the editor.
3. Select the word "test" and release the mouse outside the browser window.
4. Click on the Bold button.

Expected behaviour:
The text should be bold.

Actual behaviour:
The text isn't bold. Selecting the text again and trying to apply attributes has no effect.
New text behave as usual.

Platforms:
Chrome 60.0.3112.90 on Windows 7.

Version:
1.3.1

**Comment by mitjaz** [comment]
Sorry for the confusion with the description, I've tried to update it a little bit. I experienced the same kind of problems you have, but also none of the quill events seem to fire any more. On the examples with floating toolbar, the toolbar doesn't appear anymore after selecting text.

 What may be of help is that formatting with keyboard shortcuts works as expected.

**Comment by thinksaydo** [comment]
I can confirm this also happens in Safari.

**Comment by thinksaydo** [comment]
I can also confirm that reverting to 1.3.0 fixes this problem. So something in 1.3.1 changed.

**Comment by thinksaydo** [comment]
It appears it may have something to do with this commit: https://github.com/quilljs/quill/commit/d30e36d7a8e32d680b54ed47b40a79b839603fc9

**Comment by jhchen** [comment]
Think this is similar to #1654 and also fixed by https://github.com/quilljs/quill/commit/57d26fc3f68e5c8eb7234fcd5cb70dbe8d795750
