### ISSUE TITLE
How to keep a block format when copy paste a paragraph

### ISSUE THREAD

**Issue by amitm02** [quilljs/quill#1713]
I use a block format to associate a paragraph with an external data (e.g an url link).

Do you see any potential issues with piggyback the "block format" mechanism to associate an attribute to a paragraph? Is there a better way to accomplish this?

One problem i came across is that if the user want to mark the text & copy-paste the paragraph in order to move it to a different location, the block format is lost. Any suggestion how to go about it?

Thanks

**Comment by jhchen** [comment]
This is a pretty broad question to have a helpful answer to. I'm not sure what the "block format" mechanism referred to is and anything can have potential issues. It sounds like you already ran into one in the third paragraph? If so please elaborate.

**Comment by amitm02** [comment]
Apologies for the long delay.
By "block format" I means the [block attribute](https://github.com/quilljs/parchment#block-blot). I've named it here block format as it often used to [format the block](https://quilljs.com/docs/formats/#block)

I'v attempted to mark a paragraphs using
```
let BlockMark = new Parchment.Attributor.Class('block-mark', 'block-mark', {scope: Parchment.Scope.BLOCK});
Quill.register(BlockMark,true)
```
and than in the Delta i can do something like this

```
{ ops: [
         { 
               "insert" : "some text"
         },
         {
             "attributes": {
             "block-mark": someBlockID                     
          },
              "insert": "\n"\
          }
          ]
}

```

I'm wondering if that is the right approach and if the copy-paste issue can be resolved or if I better go for a different solution all together. And if so, what would you recommend?

Awesome project btw.
Amit

**Comment by jhchen** [comment]
Adding your code into the playground works for me: https://codepen.io/anon/pen/LzgJpv. Select-all and paste works as expected (not losing the block format).

**Comment by amitm02** [comment]
Please examine: [https://codepen.io/amitm02/pen/pWxOxZ](https://codepen.io/amitm02/pen/pWxOxZ)

If you cut "some text2" and paste it a line below the line "some text3".
(1) the empty space left is still marked as "item2" and (2) the pasted line is marked as "item3" (instead of item2).

For some reason, when using "header" block format, the pasted content keep the block format: [https://codepen.io/anon/pen/veVQaP](https://codepen.io/anon/pen/veVQaP)

**Comment by jhchen** [comment]
By default creating a newline continues the formatting the previous line had. Try bolding some text or making it a list and hitting enter. In the bold case you will see the next character you type is also bold and in the list case you can see the list is continued. This is true of all formats by default but headers turn this off by overwriting a keyboard binding. This exception is added due to UX reasons. But this keyboard binding is actually irrelevant in this case I think.

In your scenario when you cut, the browser only copies `<span>some text2</span>` since it does not copy classes in general. So after you cut and hit newline, the format continues and the new empty line has `block-mark-item3` and when you paste you are pasting plaintext "some text2" resulting in what you see. The browser does think h2 tags are meaningful so if you used that it would copy `<h2>some text2</h2>` and it behaves as you expect.

Most browsers' copy and paste does not copy data that does not contribute to rendering and Quill's paste handling can only do with what data is given to it by the browser. Open to suggestions if you can think of any.

**Comment by amitm02** [comment]
It is possible to override the copy/past event. The following seems to work: [https://codepen.io/amitm02/pen/dVLxRz](https://codepen.io/amitm02/pen/dVLxRz)

Notice that now if you copy "some text2" and paste it a line below "some text3": "some text2" has the block format attribute "block-mark-item2".

It is a design decision. But due to the flexibility nature of quill/delta, i think it is a good one. At the very least, I would suggest an event hooks for copy/cut/paste within the editor to allow the developer a clean way to modify those behaviours.

**Comment by jhchen** [comment]
If there is a not super complex way to generate the copied HTML with the desired modifications I would be open to adding this. As you say, the tricky thing is handling partial copies.

You can already do something like `quill.root.addEventListener('copy')` and I would prefer not to add passthrough functions to Quill's API surface.

**Comment by amitm02** [comment]
I've managed to do a simple detection if the exact block is selected. If so, it keeps the attributes, if not, drop back to the default copy-paste. [https://codepen.io/amitm02/pen/dVEyOP](https://codepen.io/amitm02/pen/dVEyOP).
This kind of meets my needs. I wish I could make it support multiple blocks selection, but I couldn't find an elegant way to do so without transversing over all the nodes between the anchorNode and the focusNode of the selection one by one.

@jhchen, I think keeping all the attributes for copy/cut-paste is a nice feature for quill, but i'm not sure if it is a trivial one to make. I'll leave it to you to decide if this issue should be closed or move to the backlog.
