### ISSUE TITLE
How to insert a mp4?

### ISSUE THREAD

**Issue by jackie9gag** [quilljs/quill#1724]
I am able to upload images or gifs with toolbar button or via `dangerouslyPasteHTML` api.
But i can't find a way to upload or insert mp4. Is mp4 one of the accepted format of Quill?

**Comment by boldwade** [comment]
Probably not get a response here as the help is almost non-existent (as they always push to SO), the docs are so terrible and the api is lacking, at best. You might try stack-overflow.

**Comment by alexjyong** [comment]
@boldwade  @jackie9gag I know this issue is years old, so I doubt y'all need this anymore, but for the curious reading this, I'm working on a future PR that adds this feature.  
https://github.com/alexjyong/quill/tree/bd03a5b6912ab80a3f4263d6e0eb2beb2576b4b4

Right now, it allows you to insert various video types directly through the toolbar:
<img width="470" alt="image" src="https://github.com/quilljs/quill/assets/5464404/ecc9e10e-e54b-44c6-82aa-d8aebdd80b94">


As well as maintaining the URL functionality.  

If folks are reading this and want this now, go to my github repo link at the particular commit, check it out, run 

`npm run install`
`npm run build`

And use the files in the `dist` container it creates. :)
