### ISSUE TITLE
`.setHTML(html)` freezes browser for few seconds if `html` is longer than few lines

### ISSUE THREAD

**Issue by venil7** [quilljs/quill#175]
calling `setHTML(html)` when `html` is real life piece of html (few paragraphs) freezes browser and consumes enormous amount of memory

please see js fiddle http://jsfiddle.net/3mH5c/

I also have Chrome JavaScript profiler dump if required

**UPDATE**: introduced since release 0.15.2

**Comment by core433** [comment]
I know this issue is resolved for populating an empty doc but I ran across a related issue in case anyone else's search brings them here.

When I have an existing quill editor with a large content and setHtml to a new large content, it again freezes JS for a long logn time.  A profile shows the majority of time is spent in the diff algorithm.

If you're running into this, run editor.setContents([]); before running editor.setHtml();  This will clear the Delta and thus bypass the need to calculate a huge diff between two text files.

Lastly, thanks for maintaining quill, it's great.
