### ISSUE TITLE
Drag Drop Image Issue

### ISSUE THREAD

**Issue by abusomani** [quilljs/quill#1772]
I am trying to use drag drop feature of image in quill Editor. It works fine in Chrome, but on edge if i insert an image and then i drag and drop it within a text(that was already present in the editor) it leads to page refresh.

# **Steps for Reproduction**
**Specifically use EDGE browser**
1. Visit https://quilljs.com/playground/
2. Add some default text let say " I am robot trying to test the drag drop feature"
3. Now insert an image in the editor by either toolbar's insert command or dragging and dropping
4. Drag the inserted image and try releasing it somewhere between the text let say after "robot". 

**Expected behavior**:
The image should drag/drop between text with no difficulty.
**Actual behavior**:
The page is refreshed and all the content is drained/erased.
**Platforms**:
EDGE Browser ( Version >= 14 )
OS : Windows 10

**Version**:
Tried on official quill website :  https://quilljs.com/playground/

**Comment by larryisthere** [comment]
**Expected behavior:**
The image should drag/drop between text with no difficulty.
**Actual behavior:**
The page is refreshed and all the content is drained/erased.
**Platforms:**
Chrome Version 64.0.3253.3 (Official Build) dev (64-bit)
Mac OS Version 10.13.2 Beta (17C60c)

**Comment by dip-iitr-ms** [comment]
**Expected behavior:**
The image should drag/drop between text with no difficulty.
**Actual behavior:**
The page is getting refreshed intermittently and all the content is erased. And if we are doing drag-drop of images between the text then a '~' icon is coming instead of dropping that image.
**Platforms:**
EDGE Browser ( Version >= 16 )
OS : Windows 10

 Please help us on the same to resolve it.
