### ISSUE TITLE
Option + arrow jumps over underscores

### ISSUE THREAD

**Issue by montlebalm** [quilljs/quill#1851]
On macOS, using `<option> + <right arrow>` jumps you to the end of a word. Quill handles them correctly _except_ when it comes to underscores. Quill jumps to the next word in the event of a trailing underscore.

**Steps for Reproduction**

1. Visit https://quilljs.com/playground/
2. Enter the text "one_ two" (note the space between "_" and "two")
3. Position your cursor left of "one" and hit `<option> + <right arrow>`

**Expected behavior**:
The cursor should be to the right of "one_".

**Actual behavior**:
The cursor is at the right of "two".

**Platforms**:

macOS:
- Chrome 62.0.3202.94
- Safari 11.0.2

**Version**:

1.3.4

**Demo**
![dec-07-2017 13-36-36](https://user-images.githubusercontent.com/739390/33739929-b642e392-db53-11e7-8183-68d829d5c70b.gif)

**Comment by jhchen** [comment]
Quill is not doing anything to overwrite native behavior and this appears to be how native textareas and inputs behave (at least on Mac + Chrome). 
![native](https://user-images.githubusercontent.com/192974/34054274-fd45535c-e17e-11e7-820a-44fcc4c71b9a.gif)

Quill does support custom [keyboard bindings](https://quilljs.com/docs/modules/keyboard/) to overwrite any keyboard shortcut. The backwards behavior being inconsistent with forwards does indicate some sort of issue or bug. However I'm always hesitant to overwrite native behavior especially when it comes to editor interactions since they cannot be reliably tested by automation and implementations are typically very pretty error prone.

**Comment by zengyuangai** [comment]
1.3.6 no problem

**Comment by luin** [comment]
The latest Webkit should have this issue fixed. Closing...
