### ISSUE TITLE
Accessibility Issue on Editor Toolbar

### ISSUE THREAD

**Issue by abusomani** [quilljs/quill#1869]
From accessibility point of view, some of the buttons of toolbar are not Tab accessible.

**Steps for Reproduction**

1. Visit https://quilljs.com/
2. Try pressing Tab to bring focus on the toolbar.

**Expected behavior**: Tab focus should come on "Heading" button , "Font" button and should work by pressing Enter/ Space

**Actual behavior**: The Heading button and Font button are not getting focused and is not triggered by Space/ Enter

**Platforms**:
All browsers , Windows.

**Version**:
Quill official website.

**Comment by DmitrySkripkin** [comment]
You need editor content to be selected to apply formatting. If you "tabbed" to something else then editor is not focused anymore and there is no sense in triggering toolbar controls.
I think expected behavior is "Tab focus shouldn't come on toolbar controls"

But if you want 100% keyboard accessibility you can use keyboard bindings to apply formatting.

**Comment by mutoe** [comment]
link to https://github.com/quilljs/quill/pull/937
