### ISSUE TITLE
Range Selection Issue

### ISSUE THREAD

**Issue by arist0tl3** [quilljs/quill#1889]
**Steps for Reproduction**

1. Visit quilljs.com
2. Enter an email address on the first line
3. Enter an email address on the second line
4. Triple click the first line, select link, save
5. Triple click the second line, select link, save
6. Top link isn't prefixed with mailto: (because the range isn't properly selected)

**Expected behavior**:

Range selection is consistent regardless of content on the next line.

**Actual behavior**:

Range selection changes based on content below the current line.

**Platforms**:

Able to repro on windows and ubuntu, firefox and chrome.

**Version**:

1.3.4

**Notes**:

The broken mailto: link is just a symptom of the underlying issue, which is that the range is including an extra character. If you log the output of `quill.on('selection-change', function (range, oldRange, source)`, you will see that the range is different in the repro steps, which is leading to the incorrect parsing of the Link/mailto code.

Also, alternatively to the triple click, Shift+UpArrow causes the same behavior.

**Comment by jhchen** [comment]
Yes this issue is triple clicking selects the newline character after the link as well so it does not match the email regex. You can overwrite this behavior or any toolbar handler with https://quilljs.com/docs/modules/toolbar/#handlers but I don't think Quill's tooltip should be modifying the range based on content context so I do not think Quill should be mitigating this UX in core.
