### ISSUE TITLE
Syntax/Tag Highlighting

### ISSUE THREAD

**Issue by scottfr** [quilljs/quill#1913]
I'm trying to implement a Quill module that adds a background color for all text that is contained between curly brackets.

The code is loosely modeled of the syntax.js module, however, instead of replacing the the dom with the highlighted text, I use Quill's formatText command to added a 'highlight' blot to any text between curly brackets.

This works, however it interacts poorly with the UndoManager. The formatText() calls appear to break undo history in strange ways even when calling everything with the 'silent' setting.

The rough sequence of events in my code is the following triggered on an edit with a delay:

1. quill.update(silent)
2. range = quill.getSelection()
3. find sections of the doc that need need to be highlighted
4. repeat for each section:
    quill.formatText(index, length, 'highlight-blot', true, silent)
5. quill.setSelection(range, silent)

**Comment by jhchen** [comment]
This approach is a bit concerning as Quill wants to treat code as plain text and let libraries (such as highlight.js) handle the highlighting, so your approach would be fighting against Quill's design. I would look into highlightjs's plugin system instead.

**Comment by scottfr** [comment]
Is the highlight.js approach compatible with quill styling? I want the user
to be able to edit rich text and then have the syntax highlights applied
over that.

**Comment by jhchen** [comment]
Sorry I misunderstood the scope of your use -- I thought this was just curly brackets within code, but you are talking about the entire document, even non-code. In that case can you elaborate on "break[ing] undo history in strange ways?"

**Comment by scottfr** [comment]
It appears the "formatText" call inserts an undo point (even though it is called with the "silent" source).

The result of this is you can get you in a situation where:

1) Edit something that creates a new section that should be highlighted
2) The highlighting routine gets called and formatText is called to highlight that new area
3) That inserts an undo point
4) You try to undo what you just edited, but because a new undo point is inserted by formatText you actually just undo the formatText call
5) After undoing that highlighting, the highlighting routine triggers again and does the formatText call again (as that section should be highlighted)
6) If you try to undo again, 4-5 just repeat

The result of this is you can't undo past the last formatText

**Comment by jhchen** [comment]
One point is "silent" does not mean history will ignore it, it just means text-change events are not emitted. It is important for history to be aware of all changes in the editor -- otherwise it cannot maintain an accurate stack to perform undos and redos.

In your case the approach I would take is listen on the bracket close key and make your color change there. You can then in the handler either:

1. Construct a delta and use updateContents like https://github.com/quilljs/quill/blob/043e32977f4b89fbf8254f2bbad8fdd064c27f7c/modules/keyboard.js#L238-L246
2. Call `insertText(index, '}', ...)` and then formatText separately and use [`quill.history.cutoff`](https://quilljs.com/docs/modules/history/#cutoff-experimental) to control undo points like https://github.com/quilljs/quill/blob/043e32977f4b89fbf8254f2bbad8fdd064c27f7c/modules/keyboard.js#L196-L202

**Comment by scottfr** [comment]
Thank you for this advice.

Looking at the History docs page you link to, it seems like the {userOnly:
true} config setting is actually exactly what I am looking for. Is there
anything to be cautious about in regards to it?

**Comment by DonovanCharpin** [comment]
Hey @scottfr, did you find an elegant way to do it? I have the exact same use case.
