### ISSUE TITLE
custom font color 

### ISSUE THREAD

**Issue by leo-zhao** [quilljs/quill#198]
Does quill have the ability to do custom font colors rather from the color palette, eg rgb color picker?

**Comment by tylerkrett** [comment]
Hey Guys,

Is there any help on how to do this ? has anyone made an arbitrary color picker for Quill.

I am just about to give it a go so any help would be great

**Comment by simonwilbert** [comment]
@tylerkrett did you have any luck with this? I'm about to do the same

**Comment by tylerkrett** [comment]
I got very close to implementing it but the main flaw i was having was setting the colours picked to a board to be reused.

so in the end I used Tiny-MCE but remember that tiny-mce support for react is not up to date so you can use my repo that is to get you going

**Comment by jhchen** [comment]
Custom colors have worked out of the box as described by the documentation since a very early version of Quill.

Via the API, formatText just works. You an try it out by going to https://quilljs.com, opening the developer console and trying `quill.formatText(0, 10, 'color', '#abc123');`

Via a custom toolbar, you can just change the toolbar setting to `{ color: ['#abc123'] }` like in this [example](https://codepen.io/quill/pen/KZEMYx). The configuration details for the toolbar can be found [here](https://quilljs.com/docs/modules/toolbar/).

**Comment by lili21** [comment]
how to make the toolbar accept text to arbitrary color rather than predefined color?

**Comment by lili21** [comment]
I tried the [solution](https://stackoverflow.com/a/48156458/3928561), it doesn't change line color under the `A` button
