### ISSUE TITLE
Left key handler is not triggered in an empty editor

### ISSUE THREAD

**Issue by christianhg** [quilljs/quill#2005]
**Steps for Reproduction**

1. Visit https://codepen.io/christianhg/pen/bLXOwL
2. Place cursor in the editor
3. Press the `right` key
4. Notice that `"right"` is printed in the console
5. Press the `left` key

**Expected behavior**: `"left"` is printed in the console

**Actual behavior**: the `left` key handler isn't called

**Platforms**:

MacOS 10.13.3
Chrome 64

**Version**: 1.3.5

**Comment by christianhg** [comment]
@jhchen Would this be a good first bug? If so, I could give it a shot.

**Comment by atifsyedali** [comment]
I came across this too. I worked around it temporarily by binding onKeyDown in addition to the binding in the keyboard module.

**Comment by tomwalters** [comment]
I came across this issue and dug into the existing default bindings for the arrow keys, eventually landing on "embed left" - https://github.com/quilljs/quill/blob/0f20a58acece17853cfec8c177543108733e722c/modules/keyboard.js#L538

This [default handler](https://github.com/quilljs/quill/blob/0f20a58acece17853cfec8c177543108733e722c/modules/keyboard.js#L638) returns `false` which prevents additional handlers from firing [as per the docs](https://quilljs.com/docs/modules/keyboard/#key-bindings). I'm not sure why this is in core, but this is what's causing the issue.

Grabbing the name of this binding and overwriting it in my own configuration enables me to fire the event handler:

```
keyBindings: {
  'embed left': {
    key: 37, /* Left arrow */
    collapsed: true,
    offset: 0,
    handler: (range, ctx) => {}
  }
}
```

It's not a great solution as it overwrites this handler, but it works™.

**Comment by tommyc38** [comment]
This relates to #2423.  Rather than overwriting Quill's keyboard binding, you can give the keybinding a numerical name (e.g. `1`) vs `embed left`.  This will make your keybinding have higher priority than Quill's (e.g. their documentation is wrong with regard to how quill gives priority over default keybindings which is stated in #2423).  It's a hack but hopefully some keyboard api updates will be coming to address these issues.  Hopefully this helps someone.
