### ISSUE TITLE
[Feature] Adding JavaScript inside editor

### ISSUE THREAD

**Issue by isaac2004** [quilljs/quill#2048]
One feature that is interesting is the ability to put JavaScript (<script> tags) inside of the editor, and that script runs when the editor is loaded. This would be valuable when pasting Gists into the editor and the Gist being injected into the DOM.

Here is a sample of a gist.

  <script src="https://gist.github.com/isaac2004/b76c594709130d146a752d550c1ce770.js"></script>

**Comment by jhchen** [comment]
This seems problematic from a security perspective so unless there is a very compelling real world use case it does not seem like a fit for the core project.

**Comment by charrondev** [comment]
Definitely agreed here. Many use cases for for an editor like this involve displaying user content to other people. One of the largest benefits for our use case is that the quill delta format is much easier to parse securely on the server side than HTML.

Loading any random script into your page alongside your own javascript, essentially allows 1 user to totally rewrite your page in any way they wish for other users.

If you're not familiar with XSS you should read up on it https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting because that is essentially what you are asking for as a feature.
