### ISSUE TITLE
`removeFormat` will append new line at the end

### ISSUE THREAD

**Issue by ocavue** [quilljs/quill#2071]
**Steps for Reproduction**

1. Visit https://codepen.io/ocavue/pen/wmLqRW
2. Tap `B` and you can see that all text are blue beacause `formatText(0, quill.getText().length, 'color', 'blue')` was called. After tapping `B`, editor still have only one line
3. Tap `N` and all text beacome black again beacause `removeFormat(0, quill.getText().length)` was called. But everytime I tap `N`, there is an empty line appended into editor. See the screen shot below.

![image](https://user-images.githubusercontent.com/24715727/38772219-25a09566-4064-11e8-8947-bb8f658db9e3.png)

**Expected behavior**:

`formatText` and `removeFormat` have same behaviour: both them will not append line at the end.

---
macOS 10.13
chrome 65
quill 1.3.6

**Comment by dundalek** [comment]
I've also run into this. The reason is that `removeFormat` ends up using `getText` which always returns extra newline even for empty strings (see https://github.com/quilljs/quill/issues/1559).

The workaround that seems to work is to exclude the newline like:
`quill.removeFormat(0, quill.getLength()-1)`.

**Comment by xs528** [comment]
This is indeed a problem
