### ISSUE TITLE
Custom inline blot is being rendered multiple times when pressing ENTER

### ISSUE THREAD

**Issue by vasilionjea** [quilljs/quill#2154]
Hello,

We have decided to use Quill for a project and I'm running into an odd issue where a custom inline Blot is being copied and rendered multiple times when pressing the ENTER key immediately after formatting with my custom Blot.

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/OExJvW
2. Enter "Hello "
3. Then press the *Macro* button in the example
4. Then press the ENTER key multiple times

**Expected behavior**: The custom Macro blot shouldn't be copied and rendered multiple times. Simply a new line should be rendered.
**Actual behavior**: It's copied and rendered multiple times.

**Platforms**: Google Chrome 66, macOS Sierra
**Version**:  Quill 1.3.6

**Comment by vasilionjea** [comment]
I found a solution to this: https://codepen.io/anon/pen/MXEXBb Basically I removed the `static formats(domNode)` definition.  With that said, not totally sure how you'd go about wrapping the text in a span with a classname with this approach.

Another approach is to use an Embed like in this example: https://codepen.io/anon/pen/jKGKbg which works for the most part. The only issue with the Embed approach is that the cursor position "jumps" way to the right with this hack: `quill.insertText(range.index + 1, ' ', Quill.sources.SILENT)`.

**Comment by arslnb** [comment]
@vasilionjea I think the hack works, but only if the blot contains text with a length of 1. A generic use case would have to use something like `quill.insertText(range.index + data.length + 1, ' ', Quill.sources.SILENT).`

**Comment by lakshanVio** [comment]
I am facing the same problem. Does anyone know a not-hacky solution for this? The first solution mentioned by @vasilionjea does not work for me cause I am not overriding the  `static formats(domNode)` method anyway. The second approach is also not works for me because I am already using insertEmbed method to insert my custom blot. And, even though we use `quill.insertText(range.index + data.length + 1, '  ', Quill.sources.SILENT)` to insert a emply space after inserting the blot, the user can select the ending of the blot, and press enter. When this happens the second approach becomes useless. So, highly appreciated if anyone can provide a solution.

**Comment by anywhichway** [comment]
This is a total hack, but seems to work. Quill calls `formats` multiple times for inline blots, but if `formats` returns `undefined`, then the duplicate blot is thrown away. I have spent hours stepping through Quill source, but the async nature of the DOM observer that responds to the insert of the first occurrence of the blot makes it very hard to track down where the duplicate call is coming from.

```
static formats(node) {
            if(node.lock) return;
            node.lock = true;
            setTimeout(() => node.lock = false);
// put your normal format code below, in our case we just copy all attributes
            return [...node.attributes].reduce((value,attr) => {
                value[attr.name] = attr.value;
                return value;
            },{});
        }
```
