### ISSUE TITLE
dangerouslyPasteHTML may steal the input focus

### ISSUE THREAD

**Issue by dcsaszar** [quilljs/quill#2156]
`dangerouslyPasteHTML` sets the focus to the Quill editor element.
In a setting with concurrent HTML changes, where the edited content receives external updates of the HTML, `dangerouslyPasteHTML` leads to unwanted loss of focus, if the current focus is not on the Quill editor.

**Steps for Reproduction**

1. Visit https://codepen.io/anon/pen/Yvrwme?editors=0010
2. Try typing in the JS code box (i.e. not within the Quill editor) for 2 seconds

This example simulates updated HTML from an "external" source every 1 second.

**Expected behavior**:

The input focus is kept in the JS code box.
This could be:
* an API which allows to update from HTML, without changing focus
* make `dangerouslyPasteHTML` not change the input focus

**Actual behavior**:

The input focus is lost

**Platforms**:

OSX Chrome, Win 10 IE 11

**Version**:

1.3.6

**Comment by holgertidemand** [comment]
Any progress on this. I have the same problem. :)

**Comment by rafa-as** [comment]
some news here?

**Comment by mix3d** [comment]
Would definitely need to be parameterized, since the paste function IS setting the focus to the end of the pasted area. 

You can programmatically set the contents using the Deltas format with `.setContents()` function, but [line 125](https://github.com/quilljs/quill/blob/develop/modules/clipboard.js#L125) is definitely where the focus is being stolen, by putting the cursor at the end of the paste text. 

What I'm noticing between this issue and issue 2530 is that there needs to be a way to REPLACE the contents with HTML, which is functionally different than pasting, especially given the workaround needed to replace the contents right now (`setContents([]); dangerouslyPasteHTML(...)`). Replacing wouldn't focus the text. Manually setting the innerHTML of the root Quill DOM element AFTER initializing Quill is also not an ideal scenario.

**Comment by zaplachinsky** [comment]
`pasteHTML` also causes this issue.

**Comment by jri** [comment]
@jhchen Do you have any advice on this issue?
We need a way to `pasterHTML`/`dangerouslyPasteHTML` without changing the focus.

**Comment by jri** [comment]
This way you can set HTML content without changing the focus:
```js
const html = '<p>Set HTML content <i>without</i> changing focus</p>'
const delta = quill.clipboard.convert(html);
quill.setContents(delta);
```
That is don't use `pasteHTML` but convert your HTML to a delta and use `setContents` instead. It works for me. Focus does not change.

I think the Quill docs do not mention `quill.clipboard.convert`. But I found it here:
https://codepen.io/iice/pen/vQKrWY

**Comment by johnozbay** [comment]
For our specific use case, a quick disable & enable did the trick. Simplified example : 
```javascript
quill.disable();
quill.clipboard.dangerouslyPasteHTML(index, html);
quill.enable();
```
We now try our best to disable the editor while it's not in use, and re-enable it right before it's ready for use to work around some of these edge-cases.

And this way, if you're addicted to danger & adrenaline like I do, you can continue to use your favorite `dangerouslyPasteHTML` instead of the `setContents` 🎉

**Comment by nazarposhta** [comment]
> For our specific use case, (which is to prevent the on-screen keyboard from suddenly popping-up due to editor receiving focus) a quick disable & enable did the trick. Simplified example :
> 
> ```js
> quill.disable();
> quill.clipboard.dangerouslyPasteHTML(index, html);
> quill.enable();
> ```
> 
> We now try our best to disable the editor while it's not in use, and re-enable it right before it's ready for use to work around some of these edge-cases.
> 
> And this way, if you're addicted to danger & adrenaline like I do, you can continue to use your favorite `dangerouslyPasteHTML` instead of the `setContents` 🎉

`quill.disable();` blocks pasting anything in to the editor. 
About `setContents` there is no parameter `index` if I have to place a content in specific place.

**Comment by abdallahalsammanlm** [comment]
> > const delta = quill.clipboard.convert(html);
> > quill.setContents(delta);
> 
> For me this sets the html tags as text. Node idea why. Any ideas?

They changed the [source code](https://github.com/slab/quill/blob/v2.0.3/packages/quill/src/modules/clipboard.ts#L100)

Now you need to do quill.clipboard.convert({html: '<p>test</p>'});
