### ISSUE TITLE
copy/paste does not move font family

### ISSUE THREAD

**Issue by benhauer-kolodziejczyk** [quilljs/quill#2169]
When i use copy/paste inside creator it does not move font family when text is also colored.

**Steps for Reproduction**
1. Insert any text in editor
2. Separate text from bottom and top with Enter
3. Change color of text
4. Change font family on text
5. Select text using only mouse selection (ctrl + A, triple left moue button click works properly)
6. Paste text inside editor

gif:
![quill_font_bug](https://user-images.githubusercontent.com/40599205/41909246-d0890f1a-7946-11e8-90aa-91477e78a10d.gif)

**Expected behavior**:
Text is copied with color and font family

**Actual behavior**:
Text is copied only with font color

**Platforms**:
system: Linux version 4.4.0-128-generic (buildd@lcy01-amd64-019) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) 
browsers: Google Chrome - Version 54.0.2840.71 (64-bit), Mozilla Firefox 60.0.2 (64-bit)

**Version**:
1.2.6, 1.3.6

**Comment by naveen-plivo** [comment]
@benhauer-kolodziejczyk are you able to fix this?

we have tried the below approach to get the `font` attribute but `quill.clipboard.convert` is returning delta without the `font` attribute

```JS
quill.clipboard.addMatcher(Node.ELEMENT_NODE, function (node, delta) {
  if (node.style.fontFamily) {
    return new Delta().insert(node.textContent, {
      ...(delta.ops[0].attributes ?? {}),
      font: node.style.fontFamily.slice(1, -1),
    })
  }
  return delta
})

quill.clipboard.convert(`<html>....</html>`)
```

**Comment by jjnistico** [comment]
If anyone comes to this comment, in my use case Calibri font could not be pasted into the editor though it could be used within the editor from the font menu. I'm guessing that commas break the font matchers and when Calibri is used on a page it usually is used like `font-family: Calibri,sans-serif;`. In order to overcome this, I create a custom matcher to add to the list of clipboard matchers as follows:

```
export const handleCalibriFontMatcher = (
  node: any,
  delta: DeltaStatic
): DeltaStatic => {
  delta.ops?.forEach((op) => {
    if (node.style.fontFamily.includes("Calibri")) {
      const attributes = { ...op.attributes, font: "Calibri" };
      op.attributes = attributes;
    }
  });
  return delta;
};
```

This checks for Calibri in the font-family and if it exists, adds this font to the attributes of the current text.

**Comment by benbro** [comment]
Please test with v2.0.0-rc.0
https://v2.quilljs.com/standalone/full
