### ISSUE TITLE
Quill import from WebPack build breaks for consumer

### ISSUE THREAD

**Issue by RyanV** [quilljs/quill#2228]
**Steps for Reproduction**
1. Visit this code pen https://codepen.io/anon/pen/JBaMMB?editors=0010

**Expected behavior**:
Editor should not throw error

**Actual behavior**:
an error is thrown
```
TypeError: Class constructor Inline cannot be invoked without 'new'
    at new MyFormat (pen.js:12:210)
    at Registry.create (webpack://Quill/./node_modules/parchment/src/registry.ts?:34:22)
    at Scroll.create (webpack://Quill/./node_modules/parchment/src/blot/scroll.ts?:34:30)
    at Cursor.wrap (webpack://Quill/./node_modules/parchment/src/blot/abstract/shadow.ts?:127:62)
    at Cursor.formatAt (webpack://Quill/./node_modules/parchment/src/blot/abstract/shadow.ts?:69:18)
    at Cursor.format (webpack://Quill/./node_modules/parchment/src/blot/embed.ts?:12:15)
    at Cursor.format (webpack://Quill/./blots/cursor.js?:37:13)
    at Cursor.formatAt (webpack://Quill/./node_modules/parchment/src/blot/embed.ts?:16:18)
    at eval (webpack://Quill/./node_modules/parchment/src/blot/abstract/parent.ts?:122:19)
    at LinkedList.forEachAt (webpack://Quill/./node_modules/parchment/src/collection/linked-list.ts?:125:17)
```

**Version**:
2.0.0-dev.2

--------------------
There are a couple issues here.
The root problem is that the compiled code doesn't transform es6 classes.  When a consumer includes Quill in a project that will be transpiled to ES5 and tries to extend the resulting es5 function with an ES6 class, we get the above error.  Compounding the problem, the "main" reference in the package.json points to the quill.js build which uses webpack module eval, preventing the consumer from including Quill as a transpile target unless they reference the minified version.

I think ideally, the consumer of the package should not have to worry about transpiling anything from node_modules.  This should be an easy/quick fix, but it depends on if this is just an oversight or a decision has been made specifically to skip class transforms.

@jhchen, comments?

**Comment by jhchen** [comment]
Quill is using babel-preset-env now and so the transpiling is automatic based on its list of supported browsers (`_develop/webpack.config.js`). Since those browsers all support `class` that's why it is not transpiled.

The consumer should not have to transpile -- it seems like the issue is they are anyways into ES5 and then using ES6 syntax. If you disable babel in that Codepen everything works and in your own projects if you use babel's recommendation of using babel-preset-env it should work too.

I do see the argument for making it as errorless as possible for as many environments as possible but the tradeoff seems to be that everyone that is following best practices is going to pay a build size tax to help the people that do not. Also in my experience sourcemaps don't work perfectly and so not needing them for as much of the codebase as possible helps with development as well.

**Comment by RyanV** [comment]
Yeah that makes sense.  I actually forgot to update my babel configuration after migrating to Quill.  I am publishing an internal package with quill as a dependency and on the initial development work (with another editor), I was transpiling the code to increase compatibility across projects.  But considering Quill doesn't support browsers that do not support class syntax I can remove this transform from my own babel config as well.  Closing this issue.  Thanks!

**Comment by prateek14** [comment]
I am facing the same issue,
cannot get it to work. I'm using Angular 6 environment

**Comment by chloerei** [comment]
@RyanV Can you tell me how to update babel configuration? I'm not familiar with babel and webpack.
