### ISSUE TITLE
copy+past lost font size

### ISSUE THREAD

**Issue by Jianyf-Jianyf** [quilljs/quill#2290]
I choose several words to adjust its size,  copy and paste it to the editor. it's size lost. I used the offical website example

![image](https://user-images.githubusercontent.com/42170635/44966043-7c812500-af6b-11e8-976a-7162a77dcc33.png)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/45008687-9a678c00-b036-11e8-9d26-a03766185f9d.png)

I just try this in Chrome 68 + macOS, same. copy big font size and paste would lost font size.
I guess because default copy&paste didn't handle format correctly.
not sure how to solve this. (I am not core team member)

by the way, did you guys just start using quill? or already using quill for a while now？

**Comment by Jianyf-Jianyf** [comment]
It has been used for some time.  And just discovered this problem......

**Comment by bricksimpleseanmccaffery** [comment]
Related issue here: https://github.com/quilljs/quill/issues/1083.   Has anyone found a workaround?

**Comment by 1c7** [comment]
@bricksimpleseanmccaffery Nope. I simply don't use Quill all together.
actually my project just don't use editor at all now.

**Comment by kaptron** [comment]
You can try my solution in the related issue here: https://github.com/quilljs/quill/issues/1083#issuecomment-601052716
