### ISSUE TITLE
Refactor: Change css styling for specificity

### ISSUE THREAD

**Issue by shyamal890** [quilljs/quill#2379]
**Steps for Reproduction**

**Actual behavior**:
- Currently quill styling are overriding custom styles due to improper specificity. For example toolbar buttons are styled like:
`.ql-snow .ql-toolbar button`

- Because of this even if we add a bootstrap styled button in the toolbar it is overridden by quill styling due to specificity.

**Expected behavior**:
- Have styles like `.ql-snow .ql-toolbar .ql-btn`

**Version**:
1.3.6

**Comment by ashleemboyer** [comment]
I agree with this. I found it difficult to style the toolbar and easily add options to it because I didn't know the there were super specific selectors to use. For example, to change the border color of the toolbar, I had to use the `.ql-toolbar.ql-snow` selector to do so.

But I also think the toolbar module should have an easy way to dynamically add controls.
