### ISSUE TITLE
All Browsers: entering a number with a dot  (eg. "30.") creates an empty sorted list ("1.") instead of the simple text (for eg. final result "30. November")

### ISSUE THREAD

**Issue by natterstefan** [quilljs/quill#2408]
**Steps for Reproduction**

![screen capture on 2018-11-23 at 10-14-51](https://user-images.githubusercontent.com/1043668/48935640-a7469e00-ef08-11e8-9507-ed401eaefe15.gif)

1. Visit our [lovely-editor storybook](https://lovely-editor.netlify.com/?selectedKind=Editors%2FEditorQuill&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
2. enter "30."
3. now press space again

Here's the [source code of the editor](https://github.com/lovelysystems/lovely-editor/blob/develop/src/components/editor-quill/index.js) and here the [storybook story](https://github.com/lovelysystems/lovely-editor/blob/develop/src/components/editor-quill/index.stories.js).

It also happens [on the playground](https://quilljs.com/playground/) with the following config:

```js
var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      [{'list': 'ordered'}, {'list': 'bullet'}]
    ]
  },
  formats: [
    'header',
    'bold', 'italic', 'underline', 'strike', 'blockquote',
    'list', 'bullet', 'indent',
    'link', 'image'
  ],
  placeholder: 'Compose an epic...',
  theme: 'snow'  // or 'bubble'
});
```

![screen capture on 2018-11-23 at 13-32-37](https://user-images.githubusercontent.com/1043668/48943699-4c22a480-ef24-11e8-9b3d-8c098336f8a0.gif)

**Expected behavior**:

I would expect to get "30. "

**Actual behavior**:

But instead I get an unsorted list with no initial value.

Is there a setting I am missing? When I remove the `list` format it works, but lists (eg. added via menu bar) do not work of course then.

**Platforms**:

It happens on all browsers so far.

**Version**:

Must be 1.2.6, as I am using [react-quill](https://github.com/zenoamaro/react-quill) and [it states it is using `^1.2.6`](https://github.com/zenoamaro/react-quill/blob/master/package.json#L53)

_Thank you for your help!_

**Comment by natterstefan** [comment]
@DmitrySkripkin I am gonna test it. Looks really promising. If it works, you have to send me your https://www.paypal.me/ or another link, please. Because I owe you a beer then 🍺. Damn, you made my day! I was wondering how I can resolve this.

**Comment by DmitrySkripkin** [comment]
@natterstefan you already helped everyone to find issue nobody noticed :)

I just wonder, do I need to create pull request for this issue, or it's "by design". Need approval from @jhchen, оr somebody who can make decisions.

**Comment by natterstefan** [comment]
Hi @jhchen, thanks for the clarification. I understand the intent, but I have a question still.

> people did want to continue a list 

Why does the list then not start with "30." but again with "1."?

And just for the record: Our customers in Switzerland thought this UX feature is a bug and created a story in the project to fix it.

**Comment by DmitrySkripkin** [comment]
Updatet [CodePen](https://codepen.io/DmitrySkripkin/pen/NEEdBe), now list formatting won't be triggered on "11. ".

**Comment by natterstefan** [comment]
Hi @DmitrySkripkin, thank you. Looks like the example was misleading. My fault, sorry. Actually, I would expect to start with "11." in the 3rd gif above. But the current implementation of the "list autofill" always starts at 1. No matter what I enter. See the 2nd example for instance, assuming I want to auto-formatting feature enabled and start a list with 30.

**Comment by seagyn** [comment]
A good example of this and what @natterstefan is wanting to achieve, is to look at Notes on iOS.

If you were to go `11.` and hit space it create a list starting from 11. It's very handy for continuation of lists.

**Comment by gutow** [comment]
As it stands I agree this is a bug. The behavior I would expect from typing 'XX. ' (a number followed by a period and then a space at the beginning of a line) would be to start an ordered list with its start = XX (e.g. `<ol start="XX">`). Just as markdown does (see below):

32. This is item 32 in the list. 
33. It is important to be able to do this because images and tables (when that feature is implemented) will break up the lists.

I would really like to see this feature. I am implementing a rich text editor in Jupyter notebook and JupyterLab. Quilljs is one of the prime contenders, but this is a problem for us.

**Comment by sirgru** [comment]
I don't think the list continuations are implementable in a satisfactory way with the current architecture, as they seem to be implemented with CSS counter which is reset on certain elements. This part would need context sensitive logic which defaults to list continuation, yet allows a popup which reverts it, as is done in Office since 2007.

I find list stating with '-' problematic, yet I want to start them with '*'. Reseting counters when the user types in 2. is almost never what the user intended, so this should be removed IMO. So finally I contended with this:
```
keyboard: {
      bindings: {
        'list autofill': {
          prefix: /^\s*(1{1,1}\.|\*)$/
        }
      }
    }
```

**Comment by HuyenNguyen1209** [comment]
@gutow Have you found a solution yet?

**Comment by gutow** [comment]
@HuyenNguyen1209 No, I gave up on quill despite liking many of its features.

**Comment by ludejun** [comment]
If you give up, you can use [quill-react-commercial](https://github.com/ludejun/quill-react-commercial).

![quill-order-list](https://github.com/quilljs/quill/assets/5129913/492dc38f-e4ec-4cf9-a819-5f0d57185a52)
