### ISSUE TITLE
api does not work as what i think 

### ISSUE THREAD

**Issue by cpu6660** [quilljs/quill#2510]
quill.setContents([{insert:"abcdef"},{retain:1},{insert:"ed"}],Quill.sources.USER);

result shoud be :  aedbcdef 

but wrong display: 

![image](https://user-images.githubusercontent.com/13901890/52830019-e5b7b780-3109-11e9-8f18-a8f6b88db9aa.png)

**Comment by benbro** [comment]
setContents shouldn't have retain ops, only insert ops.
Contents should end with a newline { insert: '\n' }

**Comment by cpu6660** [comment]
> setContents shouldn't have retain ops, only insert ops.
> Contents should end with a newline { insert: '\n' }

whether  delete instruction don't have retain ops before or not?

**Comment by benbro** [comment]
I don't understand your question.
Maybe you need updateContents instead of setContents.
You can read about [setContents](https://quilljs.com/docs/api/#setcontents) and [Delta](https://quilljs.com/docs/delta/) in the docs.
If you have more questions please use StackOverflow. Github issues is for bugs.
