### ISSUE TITLE
Undo / Redo does not work properly for EmbedBlot.

### ISSUE THREAD

**Issue by batmanhit** [quilljs/quill#2524]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

1. Added a new EmbedBlot and defined `value` functions.
2. After I add a new EmbedBlot on the Quill component, I try `CTRL+Z` for `undo`.
3. 
- When there is no appended texts, `undo` just removes that Custom Blot perfect.
But if I try `redo`, then it just adds a simple `text`(from `value()` function) and does not add CustomBlot back.
- When there is appended texts, its behavior is really messy.
I am gonna attach the video below for that.

```
class MathInputCmp extends Embed {
  state = {
    mathField: null
  };

  static create(val) {
    const node = super.create();
    node.innerHTML = '<span class="input__math__field"></span>';
    node.setAttribute('data-latex', val);
    node.setAttribute('contenteditable', false);
    return node;
  }

  static value(domNode) {
    return domNode.getAttribute('data-latex');
  }

  static formats(domNode) {
    const MQ = window.MathQuill.getInterface(2);
    const mathField = MQ.StaticMath(domNode.firstChild);
    return {
      "data-latex": mathField.latex()
    };
  }

  constructor(domNode, value) {
    super(domNode, value);
    const MQ = window.MathQuill.getInterface(2);
    const mathField = MQ.StaticMath(domNode.firstChild);
    mathField.latex(value);
    domNode.setAttribute('data-latex', value);
    this.state = {
      mathField
    };
  }

  value() {
    return this.state.mathField.latex();
  }

  format(name, value) {
    if (name === 'data-latex') {
      if (value) {
        this.domNode.setAttribute('data-latex', value);
      } else {
        this.domNode.removeAttribute('data-latex');
      }
    } else {
      super.format(name, value);
    }
  }
}
MathInputCmp.blotName = "MathInput";
MathInputCmp.tagName = "span";
MathInputCmp.className = "input__math";
Quill.register(MathInputCmp, true);
```

https://vimeo.com/319684211

**Expected behavior**:
1. undo should remove CustomBlot completely.
2. redo should restore CustomBlot again.

**Actual behavior**:
1. undo does not remove CustomBlot sometimes.
2. redo is not adding CustomBlot back never.

**Platforms**:

Google Chrome 72.0
Using this on react
`react-quill`: 1.3.3
`quilljs`: 1.2.6

**Version**:

`quilljs`: 1.2.6

**Comment by felix-voicehub** [comment]
Similar problem. For me though, `undo` restores the custom blot with the word `true`, no matter what was in there before.

I am on `2.0.0-dev.3`.

**Comment by batmanhit** [comment]
@felix-voicehub, so undo/redo is not working for you as well?

**Comment by felix-voicehub** [comment]
At least not with the correct value in the blot, yes.

**Comment by dimshades** [comment]
> Similar problem. For me though, `undo` restores the custom blot with the word `true`, no matter what was in there before.
> 
> I am on `2.0.0-dev.3`.

same here! 
I'm trying to undo a deleted custom DOM element and it returns boolean true.
so that I've checked undo stack and it always "true"
but i'm work with react-quill

**Comment by attacking** [comment]
I also encounter this problem. We need get a complete delta information when excute 'undo' operation. Or whole node is alse accepted.

**Comment by PowerOfM** [comment]
Anyone able to solve this?

**Comment by bharath6365** [comment]
Any updates on this? I'm still facing this issue.

**Comment by cmrd-senya** [comment]
I experienced a similar issue with Quill and React-Quill.

I debugged quill for some time and I realized that when I add the embed to quill, there is a `editor.setContent` operation initiated by React-quill with source of `api` value. This leads in the end to the history module text-change handler, which calls `transform` function when `source` is not `user` by default:

https://github.com/quilljs/quill/blob/9cbf0041e0a96fb34f3cbbcf5b164ec892e2610e/modules/history.js#L18

When this `transform` is called it applies the delta to literally every record in the history stack. In the case with the embed this messes up the history stack and therefore there is no more correct undo/redo data available.

So as a workaround I ended up just commenting out this `transform` call there. It doesn't look like commenting it out breaks something significant. I don't understand why deltas generated with source `api` are supposed to affect every single point back in history. My expectation is that they silently merged with the latest history point (current state). Anyway, here's the set of specs describing this behavior: https://github.com/quilljs/quill/blob/3795d471a5ff8a87c675a679c0f05cf222988080/test/unit/modules/history.js#L168

Here I've written a test for Quill showing exactly how history is getting messed up when `setContent` is called with `api` source: https://github.com/quilljs/quill/commit/17421b847184662a708ab8aa0e23ddee7155ef52 (the history is basically overwritten in that case).

So personally for me the workaround with disabling this `transform` line works because I don't care about history being transformed for `api` events, but I don't know what could be a proper fix here.

**Comment by Sweet-KK** [comment]
> 

I don't understand your comment. It looks the same as the source code. Where to modify the code?

**Comment by SavvasAshwiniBhat1** [comment]
I am facing the same issue. We have to support undo and redo for Math embed blot.

If undo / redo is not supported for embeds, is there a way to remove embeds from history stack?

**Comment by Mritunjay-rte** [comment]
I am facing an issue related to undo/redo functionality. I'm using react-quill version 1.3.3, quill-mention version 2.1.1, and React version 18.3.1. Is this combination not compatible with undo/redo?
how to fix it?

**Comment by ZeYuan-lg** [comment]
same issue
