### ISSUE TITLE
jest fails to instantiate quill instance

### ISSUE THREAD

**Issue by matanpa** [quilljs/quill#2526]
**Description**

Hi,
I'm trying to create a test using jest framework, where I want to create a quill instance like this:

```
import Quill from "Quill";

beforeAll(() => {
  let el = document.createElement("div");
  el.setAttribute("id", "editor");
  document.body.appendChild(el);
});

it("should instantiate quill", () => {
  const quill = new Quill("#editor");
  expect(quill).toBeTruthy;
});
```

when running `jest` I get the following error:

>  FAIL  src/index.test.ts
>   × should instantiate quill (15ms)
> 
>   ● should instantiate quill
> 
>     TypeError: Quill_1.default is not a constructor
> 
>       10 | 
>       11 | it("should instantiate quill", () => {
>     > 12 |   const quill = new Quill("#editor");
>          |                 ^
>       13 |   expect(quill).toBeTruthy;
>       14 | });
>       15 | 
> 
>       at Object.<anonymous> (src/index.test.ts:12:17)

I'm not sure this is a problem with Quill or if I'm missing anything else,
Would appreciate any assistance.
Thanks,
Matan.

**Steps for Reproduction**

1. Clone https://github.com/matanpa/TestQuilljs.git
2. npm install && npm run test

**Expected behavior**: Test passes
**Actual behavior**: Test fails to instantiate quill

**Platforms**:
node.js on Windows server 2016

**Version**: 
1.3.6

**Comment by KillerCodeMonkey** [comment]
@matanpa 

this is not a quilljs issue. More an issue with the typings (not maintained here).

if you are using v1.3.6 of typing you need to import Quill like these

```
import * as Quill from 'quill'
```

there are newer typings for quill 1.3.x

try v1.3.10 :).

PS: the typings version here not directly connected with the exact quill Version, because there are hotfixes for types, so you have different hotfix versions.
