### ISSUE TITLE
How to transform html from database to formatted text in QuillJS editor?

### ISSUE THREAD

**Issue by loic-mazallon-gtec** [quilljs/quill#2534]
It's okay to write some HTML in database with QuillJS editor. But when I want to edit my text, I take back HTML from database, and add it to my div with:

quill.setText(dataRegistered);
and it shows HTML in my editor like `<p><h1>test</h1></p>`.

It doesn't display formatted H1 like when you write on it and format it as you like with bold buttons etc. I would like that the editor doesn't write H1 but shows directly a H1

Thanks for help :).

**Expected behavior**:

HTML from database directly formatted in editor like <h1> test </h1>

**Actual behavior**:

HTML  Tags are displayed in the editor like `<h1> test </h1>`

**Version**:
Quill 1.3.6

**Comment by ashleemboyer** [comment]
I've read that you can get HTML _from_ the editor by doing `quill.root.innerHTML`. I wonder if you can just set that to get what you're looking for? I have never tried it personally.

**Comment by benbro** [comment]
You can put the html inside the element you use as a container like shown here:
https://quilljs.com/playground/#autosave

Quill had [dangerouslypastehtml](https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml) but it's deprecated because it's insecure.

You can also use a [library](https://github.com/quilljs/awesome-quill#deltas) to convert to-from html.
