### ISSUE TITLE
Quill - Cursor Focus 

### ISSUE THREAD

**Issue by marcelof00** [quilljs/quill#2562]
I am having issues setting the cursor in a particular place.
This is what I have so far:

I am populating the editor by adding a 12 characters word using a javascript function that is executed on the body onload.

After that, the same javascript function has the following lines:
quill.focus();
quill.setSelection(12, 0);

I tried putting quill.focus() after the setSelection and does not work either.

Any help is greatly appreciated.

**Comment by ashleemboyer** [comment]
> I am populating the editor by adding a 12 characters word using a javascript function that is executed on the body onload.

Are you using a Quill function to do this?

After you've constructed your Quill object, you can do something like the following to set the cursor to the end of a "Hello" string:
```
quill.insertText(0, 'Hello');
quill.setSelection(5);
```

You can alternatively pass `quill.getLength()` instead of the length of your inserted text if you always want the cursor to be at the end of the contents after the insert.

**Comment by marcelof00** [comment]
Thank you for your comment. The quill.insertText was key as I was populating the DIV using Javascript, and that was not being recognized by quill, therefore the cursor was not being placed correctly.
thank you!
