### ISSUE TITLE
Avoiding link tooltip

### ISSUE THREAD

**Issue by carlonicora** [quilljs/quill#2636]
Hello everyone,

I am using the Snow theme, and every time I create a link, clicking on it I see a small tooltip where I can edit, remove or follow the link (which opens in a new tab).
I have been looking around the documentation extensively, but I haven't found a way of overriding the default behaviour, with a super minimalistic one: clicking on a link opens it. Full stop. The functionality I am trying to implement is the same used in app.asana.com.

Do I have to create a new theme to avoid the tooltip, or is there a functionality I can override to achieve this?

I am using QuillJS 1.3.6 on Chrome (latest) and I create quill with the following options:

var toolbarOptions = [['bold', 'italic', 'blockquote'],[{ 'size': ['small', false, 'large', 'huge'] }],[{ 'align': [] }],[{ 'indent': '-1'}, { 'indent': '+1' }],   ['link', 'image'],  [{ 'list': 'ordered'}, { 'list': 'bullet' }]];

var options = {
    modules: {
        toolbar: toolbarOptions,
        keyboard: {
            bindings: bindings //few optional keyboard shortcuts
        }
    },
    theme: 'snow'
};

Thanks a lot!

**Comment by lollyisland** [comment]
The `a`(nchor) element behaves the way it does due to `div.ql-editor` - `myQuill.root` - having the `contenteditable` attribute set to `true`. This occurs when the editor is enabled - `myQuill.enable()`. Rather than disabling the entire editor - `myQuill.disable()` - just set `contenteditable` to `false` for `a`(nchor) elements created in the editor (refer to code below). This behaviour will make `a`(nchor) elements exhibit their default behaviour, including `cursor: pointer` rather than `cursor: text`. The downside is that when you want to edit an `a`(nchor), you may need to delete and recreate it.

```
myQuill.on("text-change",
   function(delta, oldDelta, source)
   {
      switch (source)
      {
         case Quill.sources.USER:
            $(myQuill.root).find("a").attr("contenteditable", "false");
            break;
      }
   });

```
