### ISSUE TITLE
Row and Col Or Plugin

### ISSUE THREAD

**Issue by MarcGodard** [quilljs/quill#2850]
I am wondering if there is a way to write an overwrite on the table functionality to replace table elements with divs with classes such as `<div class="row"><div class="col"></div></div>`

**Comment by padraigfl** [comment]
Assuming this is Quill v2, you could expand the table module to use those tags here https://github.com/quilljs/quill/blob/develop/formats/table.js and add attributes into the various generators, I guess?

Although this will likely cause huge issues when copying and pasting as I think (and I might be wrong here) the matchers wont be able to detect it's a table.

**Comment by MarcGodard** [comment]
Any guides out there on adding this as a full plugin so there isnt a copy paste issue?

**Comment by padraigfl** [comment]
There's hardly anything about how the existing table plugins operate at all, I would say, within the confines of Quill, stick with html tables unless you've a really good reason not to; tables are pretty much the most complicated thing you're likely to deal with within a rich text editor with so many edge cases to deal with.
Just to give you an idea of what're you're dealing with: the tables in Quill v2 do not accept line breaks within their cells, pasting in content that's spread across multiple lines will split the table

If tables are more important than editor choice I would go with an editor which has more advanced table support (e.g. ProseMirror looks like it has decent table support and is also fully open source to the best of my knowledge) because you're gonna go insane working with tables in Quill.

**Comment by NeonCreativeStudios** [comment]
I may attempt creating a plugin for it, but I had a look at the source code for quill-better-table and it looks incredibly daunting.

I also don't really have the free time available, but this is a feature I would benefit from also. It would allow me to use it as a full page CMS editor. Columns are common in website content.

**Comment by NeonCreativeStudios** [comment]
Actually, I'm going to try my best to create this plugin. Wish me luck lol

**Comment by padraigfl** [comment]
RE: quill-better-table, bear in mind that plugin is for quill v2 so while it's probably the best table plugin for quill by a long shot, it's for a version that's made very little progress over 2 years and is likely to have breaking changes.

quill-table, which looks like something one person threw together about 3 or 4 years ago and has hardly progressed since, is really buggy but might be a better starting point. I might do a fork of it with some documentation of how it works if people are interested.

Really though... if you need tables, use a different editor. Because of how quill works the data for tables will pretty much never be readable imo.

**Comment by NeonCreativeStudios** [comment]
I made some progress but I'm struggling to replicate better-table's children multi-line blots.

![image](https://user-images.githubusercontent.com/49883221/70254975-e21b1d00-177d-11ea-9497-b890ecc47853.png)

The read multi-line DIV is supposed to be inside the columns. Anyone want to help?
I have a Container blot (row) > Block blot (column) > Container blot (multi-line container) > Block blot (multi-line row)

Any smaller working examples of embedded blots? Any outside of better-table?

**Comment by padraigfl** [comment]
quill-table on v1 does multiline with very little hassle, it handles it by having every new line character within the table contain the ID for that particular cell. a new line character with a different ID will instantiate a new cell (including the inline content before it) whereas one without an ID will result in the end of the table.

Feel like there's a decent chance quill-better-table handles it the same way?

Now, the big issue with multiline is that block elements wont work without rewriting (e.g. lists, heading tags)

**Comment by NeonCreativeStudios** [comment]
No better-table actually handles it by inserting new blot for each line, I think the resulting delta is actually multi-layered rather than flat.

It's also still maintained, last release was posted just an hour ago. I could keep playing with the better-table source code to figure it out but it will likely take me a long time.

**Comment by NeonCreativeStudios** [comment]
![image](https://user-images.githubusercontent.com/49883221/70259269-c287f280-1785-11ea-8542-372d1e1f3d0f.png)

Oh damn I never noticed that those things don't work. So certain things just won't work even if I replicate what better-table is doing. That's a shame :(

**Comment by padraigfl** [comment]
Images work okay I think? they did for me the brief time I used it

Personally I think Quill just shouldn't support tables or anything that promotes nesting beyond a basic list and should be upfront about why it doesn't support them. The whole data handling approach is flat deliberately and turns the content into a linear stream. There's little need to be doing a more complex approach when things like ProseMirror and TinyMCE exist.
I said it before in another issue but a "You should not use quill if..." part of the documentation would probably save Jason et al from an absolute ton of stress.

**Comment by NeonCreativeStudios** [comment]
I've considered ProseMirror, TinyMCE and Slate but the perfect WYSIWYG solution doesn't exist and perhaps may never exist. Either they are HTML only, not open source, too large or use external dependencies I don't wish to add to my project (jQuery / react / vue etc.)

![image](https://user-images.githubusercontent.com/49883221/70265559-958e0c80-1792-11ea-9faf-887858100162.png)
You're right images should work. Once I have more time to spend on this, I'll send an update.

Being unable to use lists won't be too much of an issue for me

**Comment by sachinrekhi** [comment]
@NeonCreativeStudios Curious what your issue was with Slate specifically? It looks quite promising as an editor.

**Comment by NeonCreativeStudios** [comment]
**Update:** just realised headings don't work inside custom blocks, I would possibly need to customise my heading blocks.

@sachinrekhi I think Slate depends on react? React is in their package.json so I suspect so. So probably isn't the most lightweight? Also their examples website appears to have stopped working? https://www.slatejs.org/examples/tables

**Comment by padraigfl** [comment]
Slate looked like it was a bit more modern with cleaner data but more a replacement for quill than a significantly powerful alternative, good but tables are a very hard problem. It does seem a lot more actively maintained in comparison to quill though. 

ProseMirror seemed like the best fully open source option to me (TinyMCE and CKEditor require a license to remove the credit text iirc) https://react-prosemirror-example.now.sh/ I gather it's more heavy duty though. The guy who leads it looks like a bit of an open source superstar too https://github.com/marijnh


To backtrack though, you really shouldn't be using Quill v2 dev version if the product is expected to be maintained. With v1 you've years of people posting issues on here and stackoverflow and getting answers to them, it's pretty stable.
