### ISSUE TITLE
Support inherited classnames

### ISSUE THREAD

**Issue by whather** [quilljs/quill#295]
I'm trying to assign the following HTML to a quill component:

```
<div class="signature">
  Outer text
  <div class="unsubscribe">
    Inner Text
  </div>
</div>
```

But Quill only wraps the child div with the class "signature", not "signature unsubscribe". Is this the intended behavior?

Cheers,
Wes

**Comment by jhchen** [comment]
Are you using `setHTML`? The expected behavior is that Quill moves the inner block out since Quill needs all block elements to be on the same level (no nested blocks). So the resulting HTML should look something like this:

```html
<div class="signature">Outer text</div>
<div class="unsubscribe">Inner text</div>
```

When I try it out it looks like the unsubscribe class is lost in the move. While this is unexpected the easy workaround is call `setHTML` with input that Quill will not have to transform.

**Comment by whather** [comment]
Yeah I'm using setHTML. So I should try to keep my HTML flat then, as Quill won't need to transform it in this case? I assume Quill supports multiple class names per div?

**Comment by jhchen** [comment]
Yes. Multiple class names are fine.

**Comment by whather** [comment]
Hey @jhchen are there any plans to support nested divs in the future? We're seeing styling issues because of the flattening.

**Comment by jhchen** [comment]
Nested divs is not a specific feature on the roadmap but it's likely that more general changes / functionality could enable this such as the ongoing effort to support custom formats. It will be more clear when that dust settles.
