### ISSUE TITLE
Ability to resize embedded image from the toolbar

### ISSUE THREAD

**Issue by miktam** [quilljs/quill#3040]
Is there a way to apply changes to an image from the toolbar, eg to resize it?

**Comment by mikeroher** [comment]
Do either of these 2 projects work? 

https://github.com/benwinding/quill-image-compress
https://github.com/Fandom-OSS/quill-blot-formatter

**Comment by jpike88** [comment]
@miktam if you want to be real cool, you can just parse the data and isolate base64 strings, and replace them with a compressed version. I don't think this belongs as a quill enhancement because images can vary widely in format etc, it's going to be a problem for such a library like this to handle that stuff.

**Comment by miktam** [comment]
@jpike88 let me be more specific.

Is it possible to apply CSS to the image (eg setting max-height, max-width), and also align the image to the left, center or right?

I agree that changing the size of the image should not be responsibility of Quill - as it would not play nice with separation of concerns principle.

**Comment by jpike88** [comment]
In the unholy event someone tried to attach a massive image... I haven't considered that being a problem.

Try this. Depending on your framework, capture all dragover events and make it so any images must be dragged in and attached as their own 'comment' events. This is the only way man
