### ISSUE TITLE
Why inserting a video URL results in a blank block?

### ISSUE THREAD

**Issue by sgon00** [quilljs/quill#3051]
Hi, I am trying quill today. 
In the official playgroud here: https://quilljs.com/standalone/full/
I tried to insert a video URL: http://vjs.zencdn.net/v/oceans.mp4
That is a valid mp4 video and you can see by clicking on it. 
But what I saw in quill UI is just inserting a blank block and impossible to play it. 
Why and how to workaround it? 
Thanks a lot.

**Comment by GwynethLlewelyn** [comment]
You're right. Interestingly, the official playground seems to be able to properly embed YouTube videos, but there is something it doesn't like about your video...

**Comment by Hyuchia** [comment]
The video seems to be getting blocked with this error: `Blocked loading mixed active content “http://vjs.zencdn.net/v/oceans.mp4”`

Which means it doesn't work because you're trying to load a `HTTP` resource inside a `HTTPS` context. Browsers block this for security.

If you use the `https://` URL of the video (https://vjs.zencdn.net/v/oceans.mp4) it loads just fine
