### ISSUE TITLE
setHTML doesn't reset active toolbar buttons

### ISSUE THREAD

**Issue by dandormont** [quilljs/quill#320]
This can be seen on the example page http://quilljs.com/examples/

1. In the "full" editor, highlight the Wikipedia link. The Link toolbar shows as active. 
2. In a Javascript console, run `fullEditor.setHTML('<div>Hello</div>');`
3. The content is replaced, but the Link toolbar button still shows as active.

**Comment by willrowe** [comment]
`setHTML` should reset the selection range to either the beginning or end. This would then trigger the `selection-change` event and reset the toolbar correctly. I can make a PR for this if wanted.

**Comment by dandormont** [comment]
@willrowe  funny you should mention that, I was actually already doing that in my own application for another reason - I was seeing an issue where if the new content was shorter than the old, and the selection had been at the end, it would lead to errors.

I would love it if setHTML could do that itself, I just wasn't sure exactly what was the right place to do that.

**Comment by willrowe** [comment]
I can put together a PR for this unless someone else wants to.

**Comment by jhchen** [comment]
A PR would be great!

**Comment by willrowe** [comment]
I'm trying to figure out what would be the best way to do it. I can simply trigger `setSelection`, but after some digging it turns out that it's already being triggered, but using `silent` as the source. After looking into the code further I've come to question why the `selection-change` event is ever silenced. In my thinking, you'd want the event to be triggered in most every case (whether it's triggered internally or not) and let the listener decide if it wants to act based on `source` type. Can you give some insight @jhchen ?

**Comment by jhchen** [comment]
From an internal/DOM perspective the selection changes when the DOM node it is on changes or if the index on that DOM node changes. This will happen as a result of typing because that changes the DOM text node. The silent is available for cases like this where the selection change is a side effect of another action and in those cases perhaps desirable--otherwise every keystroke would trigger a selection change. I think the silent selection update you are referring to is due to this case.

**Comment by willrowe** [comment]
Even if the selection is changed because of something internal, that's still an important event. This is evident because of the bug that we discussed above. You can see [here](https://github.com/quilljs/quill/blob/6b28ef9d927b1c54fd795fbc7107f59ddb591052/src/core/editor.coffee#L72) that the source which is passed to the `update` method on the `selection` instance is set to silent if there's been any change to the text (a `delta` instance). If it wasn't for this then the `selection-change` event would be triggered normally.
The toolbar is listening for the `selection-change` event so that it can update its active buttons, so it needs that event triggered every time the cursor is moved, no matter if it's internally or by the user. Can you see my confusion as to why it's being silenced?

**Comment by jhchen** [comment]
I guess what I was trying to get at is the DOM/internal definition of a selection change is not what one would expect and should be abstracted from the end user/developer. If I type a letter did the selection change? How about if I didn't do anything at all but some module used the API to insert content a couple places before my cursor? In both cases the DOM definition is yes but intuitively it's no--hence the silent feature.

The preferred solution to addressing this bug is just to set the selection to index 0, like you originally suggested (although there are some edge cases to consider such as if it's already there before calling setHTML).

**Comment by willrowe** [comment]
Thanks for your explanation. I re-evaluated the issue and since the selection is already reset (without triggering an event), setting it again would be redundant and a bit hacky. While looking through the code I also discovered that in addition to `setHtml` this bug also affects `setText`, `insertText`, `insertEmbed`, `deleteText`, and `formatText`. I also came up with a simple solution, which is to add a listener for the `TEXT_CHANGE` to trigger `updateActive`. I'll submit a PR with this fix as soon as I can.
