### ISSUE TITLE
Pasting text with strikethrough does not persist strike

### ISSUE THREAD

**Issue by tomrefresh** [quilljs/quill#3410]
When copying text from Google sheets or Microsoft office and pasting it into the Quill editor it loses all of it's strikethroughs. Bold and italics are persisted but strikethroughs disappear. 

**Steps for Reproduction**

1. Type text with a strikethrough into a Google sheet
2. Paste it into the Quill playground: https://quilljs.com/playground/
3. See strikethroughs have disappeared 

**Expected behavior**:
Strikes persist

**Actual behavior**:
Strikes don't persist

**Platforms**:
Windows

Include browser, operating system and respective versions

Google Chrome

**Version**:

https://cdn.quilljs.com/1.3.6/quill.js

**Comment by baptl** [comment]
Hello,

Been a couple of months, but I just now stumbled on the same issue while pasting from LibreOffice, so here's my two cents.

**Apparently LibreOffice's – and Google Sheet's maybe ? – "strikethrough" format becomes a `<strike>` tag in HTML.**

Sounds pretty logical/obvious but this old tag has been [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike) and should now be replaced either by a `<del>` tag to indicate deleted text, or by an `<s>` tag otherwise.

**Apparently, on the other hand, Quill uses only `<s>` tags :**
- when you apply "strikethrough" format using Quill's editor, it becomes an `<s>` tag ;
- when you paste `<del>`, `<s>`, and `<strike>` formatted text from a web page into Quill's editor, only `<s>` is rendered as "strikethrough", `<del>` and `<strike>` are ignored and rendered as plain text.

So basically, all you have to do is say to your Quill editor, "if you come across `<del>` or `<strike>`, consider it's an `<s>`", which can easily be done using a [clipboard matcher](https://quilljs.com/docs/modules/clipboard/).

**Method # 1 after instantiating your Quill editor :**

```
var Delta = Quill.import("delta"); // import Quill's delta format

yourInstantiatedQuillEditor.clipboard.addMatcher("del, strike", function(node, delta) {
  return delta.compose(new Delta().retain(delta.length(), { strike: true }));
});
```
**Method # 2 directly in your Quill editor's config :**

```
var yourQuillEditor = new Quill("#editor", {
  ...
  modules: {
    clipboard: {
      matchers: [
        ["del, strike", strikethrough],
        ... // other matchers
      ]
    },
    ... // other modules
  },
  ... // other options
});

var Delta = Quill.import("delta");

function strikethrough(node, delta) {
  return delta.compose(new Delta().retain(delta.length(), { strike: true }));
};
```

Both methods worked for me, I hope they'll work for you too :v:
