### ISSUE TITLE
[FeatureRequest]: Block Malicious code 

### ISSUE THREAD

**Issue by shwetasingh-10** [quilljs/quill#3431]
Enter some text with malicious code like:
 "<script>alert(document.cookie);</script>"

**Expected behavior**:
 I would like to request a feature to block this type of malicious code i.e not allow users to enter this type of text in the editor and give some error.
If any such thing exists to achieve this. Please let us know.

**Comment by natevw** [comment]
@shwetasingh-10 Can you explain? What exactly do you mean by "enter some text"?

When I type that text into a Quill editor I just get those letters in the editor like any other text:

<img width="956" alt="Screen Shot 2021-08-20 at 4 13 35 PM" src="https://user-images.githubusercontent.com/265902/130301703-9f77cc4a-43f7-4a57-be29-ddcf07bd38cf.png">

Are you using some extra plugin that causes that text to turn into HTML when typed in?

Or is some code setting the malicious string `"<script>alert(document.cookie);</script>"` into Quill using `dangerouslyPasteHTML` and expecting it not to be dangerous?

Or are you rendering that string directly onto the page instead of the example Quill div of:

```
<div id="editor">
  <p>Hello World!</p>
  <p>Some initial <strong>bold</strong> text</p>
  <p><br></p>
</div>


<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script>
  var quill = new Quill('#editor', {
    theme: 'snow'
  });
</script>
```

Are you doing something like this?

```
<div id="editor">
  <script>alert(document.cookie);</script>
</div>

<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script>
  var quill = new Quill('#editor', {
    theme: 'snow'
  });
</script>
```

**Comment by shwetasingh-10** [comment]
@natevw,
"**When I type that text(<script>alert(document.cookie);</script>) into a Quill editor I just get those letters in the editor like any other text:**" - Exactly I want something where Quill alerts me or gives me warning like some malicious code like "<script>alert(document.cookie);</script>" is entered in the editor. Until i am not using any pluginto render these tag differently.
Please let me know if you want to know any other details

**Comment by benbro** [comment]
This should probably be a server side validation and depends on your use case. Quill treat it as text.
