### ISSUE TITLE
Newline at the end of the text : retain count is 1 greater than expected

### ISSUE THREAD

**Issue by rocketraman** [quilljs/quill#344]
http://jsfiddle.net/fxfg1fad/

When a newline is entered at the end of the text, the delta retain includes the internal newline Quill keeps at the end. The end result is fine since the new newline becomes the new "internal" end newline, while the old "internal" newline is retained. However, it is inconsistent since the "internal" newline is not actually user editable i.e. it is not shown in the user, so one would expect the retain count to be one less, as it is when entering a character other than newline.

In the fiddle above, "Dump Editor Contents" and then entering "1" at the end of Foo results in:

```
{"ops":[{"insert":"Foo\n"}]}
[{"retain":3},{"insert":"1"}]
```

But "Dump Editor Contents" and then entering "\n" at the end of Foo results in:

```
{"ops":[{"insert":"Foo\n"}]}
[{"retain":4},{"insert":"\n"}]
```

Also, the author attribute, if applicable, gets associated with the "wrong" newline.

It is the same behavior when deleting the last newline.

**Comment by jhchen** [comment]
I agree this is a bit confusing. The reason this came to be is when line formats (text-alignment, lists/bullets). The following list:

1. Eggs
2. Bacon

is represented by the ops:

```js
[
  { insert: 'Eggs' },
  { insert: '\n', attributes: { lists: true } },
  { insert: 'Bacon' },
  { insert: '\n', attributes: { lists: true } }
}
```

In this case the trailing newline *has* to be in the delta--otherwise we wouldn't know that "Bacon" is part of the list. We could only include the trailing newline only if the last line is formatted but in that case it's equally confusing, just less common. Also this creates a case where adding a format would change the length of the document. The current state is best solution we have but open to new ideas.
