### ISSUE TITLE
"insert : 1" delta results in inserting a "!"

### ISSUE THREAD

**Issue by cphyc** [quilljs/quill#347]
Is the fact that `{insert: 1}` has the same behavior as `{insert: '!'}` a feature or a bug?
I am getting to this situation because I am writing a collaborative text editor that first inserts the text (thus the `{insert : 1}`) and only **then** applies the attributes.

A hacky solution would be to transform all the inputs `{insert : 1}` to `{insert : 1, attributes: {image: ""}}`.

**Comment by jhchen** [comment]
It's expected behavior--though arguably non-optimal. The reason this is the case is if you have a document with an image and call `getText()`, what should that text value be for an image? It could be nothing but then the length of `getText()` is different from the length of the document. So the current workaround is just output "!" as the text content of the image. Perhaps it's not important the length of `getText()` is the same as `getContents()` but this is the current state of things.
