### ISSUE TITLE
insert a image

### ISSUE THREAD

**Issue by wghust** [quilljs/quill#369]
```javascript
_pthis._editor.updateContents({
   ops: [{
               insert: 1,
               attributes: {
                     alt: "Lab Octocat",
                     image: 'http://ossweb-img.qq.com/images/cf/web201412/match/cfdl.jpg'
               }
    }]
});
```
I want to insert a image, but always has this bug ‘Cannot read property 'isType' of undefined’. maybe I have lost some attributes, what I should do?

**Comment by willrowe** [comment]
If you remove `alt: "Lab Octocat",` it works. The only place that I can see a reference to being able to set the `alt` attribute is in the [documentation](http://quilljs.com/docs/deltas/#insert). I don't believe it's possible to set any attributes on an embed in this way. Not sure if this was supposed to be a feature at one time, but it should probably be removed from the documentation since it doesn't work.

**Comment by wghust** [comment]
@willrowe but if I want to set the image's width is 100%， what can I do? I can't set this in attributes.

**Comment by willrowe** [comment]
I'm not familiar with how all that's supposed to work. @jhchen might be able to help you out.

**Comment by wghust** [comment]
@jhchen hi, I have some problem with quill. In which function can I set the image's width which was uploaded by user.

**Comment by jhchen** [comment]
The best way right now is to set a css rule setting width to 100%. There is not currently a way to control image attributes in Quill more dynamically.

**Comment by devmarco** [comment]
[Question]

After insert a image with the command below, the image is inserted using base64.

```
insertEmbed(range, 'image', url);
```

My question is, after that, I am uploading that image to the server behind the scenes, and when I have the success information, I would like to just update the "src" reference to the correct url.
Is there any way to do that on quill? using updateContents or other method?

I could do that deleting the image added before, and adding a new one. But I didn't like this way because the user experience is not good.

**Comment by shivavelingker** [comment]
@devmarco did you figure out a solution for that?
