### ISSUE TITLE
broken "edit on github" links in docs sections of website

### ISSUE THREAD

**Issue by wimachtendink** [quilljs/quill#3756]
apologies if this is the wrong repo. The "edit on github" links point to "https://github.com/quilljs/quill/tree/develop/docs/docs/[pageName].md" but none of them seem to link to anything except the github 404

**Steps for Reproduction**

1. Visit https://quilljs.com/
2. navigate to Documentation
3. select any page
4. click "edit on github"

**Expected behavior**:
should open appropriate github tab 

**Actual behavior**:
navigates to github 404 page

**Platforms**:
only tested on Chrome Browser/windows

**Version**:

website

**Comment by ADTC** [comment]
Looks correct here: https://github.com/quilljs/quill/blob/d2f689fb4744cdada96c632a8bccf6d476932d7b/website/gatsby-config.js#L4

It's likely because the deployed website is from the last release version which was in 2019, and still has the old path. I think there's nothing to do here except wait for a new release and the deployment of an updated website.

**Comment by benbro** [comment]
Fixed in v2.
