### ISSUE TITLE
Horrible

### ISSUE THREAD

**Issue by Nashorn** [quilljs/quill#3770]
Absolutely horrible and bug filled project

**Comment by luin** [comment]
Hey @Nashorn 👋 ,

Thank you for your interest in Quill! It's true that there are many open issues right now, but we have gradually started to prioritize and address them based on their importance. This process will take some time. If you have any specific suggestions or questions, please feel free to raise them. We cannot guarantee immediate action due to the limited bandwidth, but we will address them in order of importance.
