### ISSUE TITLE
Update quilljs version (from 1.0.0 to 1.3.7) in README in this repo and on npmjs.com

### ISSUE THREAD

**Issue by vadimkantorov** [quilljs/quill#3932]
Currently it says `1.0.0` which is very outdated and leads to [problems](https://github.com/cloverhearts/quilljs-markdown/issues/74) with extensions, such as quilljs-markdown :(

**Comment by srohatgi01** [comment]
Should we update the version to 1.3.6 or to 1.3.7? Asking because on website's documentation we have 1.3.6 so should we proceed with updating readme here with 1.3.7 and on website 1.3.6 or have it consistent on both website and repo readme?

![image](https://github.com/quilljs/quill/assets/24872423/df069950-c7de-451f-83dd-2fe0690b5144)
(Image shows the website docs screenshot)

Also can this issue be assigned to me, please.

**Comment by vadimkantorov** [comment]
https://github.com/quilljs/quill/releases says 1.3.7 is out, bur then maybe better to update it when 2.0.0 is out...

I'm not maintainer and cannot "assign" and don't know if this concept is practiced at all in this repo, but you can just send directly a PR with the README update
