### ISSUE TITLE
Justified content is not justified in FF Nightly

### ISSUE THREAD

**Issue by cphyc** [quilljs/quill#396]
If I past any content that is more than one line long and justify it, it is not justified!
 ![justify](https://cloud.githubusercontent.com/assets/5411875/8188010/7e47a302-1453-11e5-9901-43ba3f02bef9.png)

**Comment by willrowe** [comment]
This is because of
```css
.ql-editor {
    white-space: pre-wrap
}
```
interfering with the `text-align` value. According to [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=299721) it is actually the expected behavior according to the standard for the white-space property. I tested this on all major browsers, the results are as follows:
:heavy_check_mark: = follows standard (does not display justified)
:x: = does not follow standard (displays justified)

| Browser           | Windows            | Mac OS X           |
| :---------------- | :----------------: | :----------------: |
| Chrome            | :x:                | :x:                |
| Firefox           | :heavy_check_mark: | :heavy_check_mark: | 
| Opera             | :x:                | :x:                |
| Safari            | :heavy_minus_sign: | :heavy_check_mark: |
| Internet Explorer | :heavy_check_mark: | :heavy_minus_sign: |
It seems that the only problem is with Blink-based browsers. The interesting thing is that if you set it to right or center aligned it will do that, just not justified. If these other browsers were adhering to the standard fully then it would fallback to the initial value (which is left aligned).

**Comment by willrowe** [comment]
I found where this was changed in Blink:
https://codereview.chromium.org/148013005/
It seems it's up to the browser whether to justify or not.

**Comment by jhchen** [comment]
FYI Quill uses the the `pre-wrap`rule  to make tabs display properly--otherwise browsers collapse tabs into a single space.

**Comment by cphyc** [comment]
I found the W3C specification about that issue [here](http://www.w3.org/TR/CSS21/text.html#alignment-prop).
