### ISSUE TITLE
The same styles need add in the header once on init Quill

### ISSUE THREAD

**Issue by IndexOf** [quilljs/quill#411]
Every time when block is initialized in the header adds the same styles.
http://screencast.com/t/biQXzOlF

**Comment by jhchen** [comment]
If you pass in `{ styles: false }` into the [options](http://quilljs.com/docs/configuration/#styles) Quill will not add the styles to the header. Since quilljs.com/examples shows code that's actually being used on the page I think its more clear to not have one of the options to include `{ styles: false }`.
