### ISSUE TITLE
Focus issues when scrolled down in IE10+

### ISSUE THREAD

**Issue by magus** [quilljs/quill#415]
https://github.com/quilljs/quill/issues/221

This issue above still seems to be present in IE10+, you can easily reproduce it on the http://quilljs.com/ homepage examples.

Perhaps we can do a fix similar to the pasting scroll issue (https://github.com/quilljs/quill/issues/143) and just quickly scroll back to the selected content. Calling preventDefault for the buttons will work just fine for the buttons, but not the select items due to their unique nature.

**Comment by jhchen** [comment]
I'm not able to reproduce this in IE10 or IE11. Can you post steps for reproduction?

**Comment by magus** [comment]
Go to quilljs.com
Scroll down to bottom of text editor
Type in some content, select it, then click the bold formatting button or select a new font from the dropdown
The view will jump due to the focus call

**Comment by muhleder** [comment]
We're seeing this as well, using something like this to fix it.
https://github.com/muhleder/quill/commit/ca9cd7b6b1005969a26239a8f60762a476562edb

**Comment by Pavek** [comment]
I can still reproduce it with Quill 0.20.1 on Win7/IE11.

The simplest testcase:
Go to [http://quilljs.com/](url) in IE11
Scroll editor area down to bottom
Click any button: Bold/Italic etc..
=> The editor area is immediately scrolled to the top (this is bad because you might have edited something at the bottom, obviously)

Looks like this is caused by: https://github.com/quilljs/quill/blame/0.20.1/src/modules/toolbar.coffee#L59
