### ISSUE TITLE
Add horizontal line (hr)

### ISSUE THREAD

**Issue by freshsun** [quilljs/quill#434]
I search the code and found that HR is a VOID_TAG
Is it possible to add hr and toolbar button to insert it?
hr is useful as a divider, also I found that quilljs has no support for table at this moment, hr can be used for creating a table like block.

**Comment by jhchen** [comment]
Quill will eventually have official support for tables. You should be able to add your own formats like `<hr>` when Quill 1.0 is out with better custom format support.

**Comment by lalitkapoor** [comment]
@jhchen is this possible now? Thanks!

**Comment by benbro** [comment]
@lalitkapoor you can see an example how to create a custom divider (hr) button here:
http://quilljs.com/guides/cloning-medium-with-parchment/#dividers

Table support is tracked here:
https://github.com/quilljs/quill/issues/117

**Comment by lalitkapoor** [comment]
Awesome thanks @benbro

**Comment by CodeSmith32** [comment]
> http://quilljs.com/guides/cloning-medium-with-parchment/#dividers

@benbro this documentation isn't really that helpful because it only explains how to do it with a completely custom menu.

Horizontal lines *really is* something that should be built into Quill by default. From your comment, I assumed that, even as a noob to Quill, it would probably be relatively trivial to implement. Clearly not:

I'm trying to implement it using the following toolbar config:

```ts
modules: {
  toolbar: [
    [{ font: [] }, { size: [] }, { header: [] }],
    ["bold", "italic", "underline", "strike"],
    [{ color: [] }, { background: [] }],
    ["code-block", "blockquote"],
    [
      { indent: "-1" },
      { indent: "+1" },
      { list: "ordered" },
      { list: "bullet" },
    ],
    [
      { align: "" },
      { align: "center" },
      { align: "right" },
      { align: "justify" },
    ],
    ["link", "image", "divider" /* <--- */ ],
  ],
}
```

Following the 'tutorial' I register the divider exactly as they do (except using import since this is TypeScript):

```ts
import { BlockEmbed } from "quill/blots/block";

class DividerBlot extends BlockEmbed {
  static blotName = "divider";
  static tagName = "hr";
}
Quill.register(DividerBlot);
```

Now, this all does work *except* for the super ugly `Enter divider:` prompt that appears everytime I click the "divider" button. The user is required to put garbage contents in it in order to make the `<hr>` appear.

This prompt seems to appear due to a hardcoded `instanceof EmbedBlot` check that Quill does when clicking buttons.

How do I get around this?

**Comment by CodeSmith32** [comment]
Ok:

Apparently, with Quill, it will always show the dumb prompt *unless* you register a handler. At this point, I wrote a handler that works better than the default anyway. So to set up a smoothly working `<hr>` feature is NOT trivial, but feel free to copy/paste the following TypeScript code below:

```ts
import { BlockEmbed } from "quill/blots/block";
import Toolbar from "quill/modules/toolbar";

// register Quill divider Blot:

class DividerBlot extends BlockEmbed {
  static blotName = "divider";
  static tagName = "hr";
}
Quill.register(DividerBlot);

// post-process function for Quill instances:

const postProcessQuill = (quill: Quill) => {
  const toolbar = quill.getModule("toolbar") as Toolbar;
  const divider = toolbar.container?.querySelector(".ql-divider");

  if (divider) {
    divider.innerHTML = `
      <svg viewBox="0 0 18 18">
        <line class="ql-stroke" x1="1.795" y1="9" x2="16.205" y2="9"/>
        <polyline class="ql-stroke" points="13.494,4.706 13.494,6.239 4.506,6.239 4.506,4.706 "/>
        <polyline class="ql-stroke" points="13.494,13.295 13.494,11.76 4.506,11.76 4.506,13.295 "/>
      </svg>
    `;
  }

  toolbar.addHandler("divider", () => {
    const range = quill.getSelection(true);
    const prev = quill.getText({ index: range.index - 1, length: 1 });
    const next = quill.getText({ index: range.index, length: 1 });

    if (prev !== "\n" && prev !== "") {
      quill.insertText(range.index++, "\n", "user");
    }
    quill.insertEmbed(range.index++, "divider", true, "user");
    if (next === "\n") {
      quill.deleteText(range.index, 1, "user");
    }

    quill.setSelection(range.index, 0, "user");
  });
};
```

Then, whenever you create a Quill instance, you need to pass it through the `postProcessQuill` function which will configure the toolbar divider button correctly:

```
const quill = new Quill(domElement, { /* ... */ });
postProcessQuill(quill);

//...
```

Specifically the function injects a nice looking icon (I made it - CC0), and adds the needed toolbar handler, which does some proper newline checking before inserting it so that no extra newlines appear.
