### ISSUE TITLE
editor.focus() triggers error leaf is undefined

### ISSUE THREAD

**Issue by rockerest** [quilljs/quill#442]
When using `editor.focus()` Quill reports an error [from the Document](https://github.com/quilljs/quill/blob/cefcf6f78ef4a22064a04bac1e7ea6695ab122c8/src/core/selection.coffee#L122) indicating that `leaf is undefined`.

My specific use-case is the following function:

    function( editor ){
        editor.setText( '\n' );
        editor.focus();
    }

Which led me to believe the issue is when the editor is empty.

I tried `editor.setText( 'a' );`, however, and it still produced the same error.
Then I thought that maybe [the test for zero lines](https://github.com/quilljs/quill/blob/cefcf6f78ef4a22064a04bac1e7ea6695ab122c8/src/core/selection.coffee#L120) was broken.
So I tried `editor.setText( 'test\ntest' );`
However, `.focus()` still triggers the same error.

At this point I'm lost, so I switched the function to this:

    function( editor ){
        editor.setText( '\n' );
        editor.setSelection( 0, 0 );
    }

This suits my purposes, but isn't ideal in the grand scheme of things.

This issue could potentially be related to https://github.com/quilljs/quill/issues/207 or https://github.com/quilljs/quill/issues/292.

**Comment by jhchen** [comment]
I'm not able to reproduce this on the quilljs.com homepage editor on Mac + Chrome. What browser + os are you using?

**Comment by rockerest** [comment]
I'm in Firefox 39.0.3 + Xubuntu 15.04.

**Comment by jhchen** [comment]
I tested it on Ubuntu + Firefox 39 on the homepage and it seems to work as well. I don't believe you can intercept focus while in the dev tools inspector. Set a timeout for `.focus()` and then click on the page--focus will transfer to the Quill editor correctly.

At this point it seems like either bug caused by xubuntu which is not supported or in the integration code since the editor on the quilljs.com homepage works on the supported platforms given your reproduction instructions.
