### ISSUE TITLE
Caret jumps to mouse position or start when selecting option from toolbar select menu

### ISSUE THREAD

**Issue by acrylic-origami** [quilljs/quill#456]
Steps to reproduce:

1. Type multiple lines of text, preferably in a large font size.
2. Access a toolbar menu (e.g. font size) and select an option that overlaps with the editor space (the second option usually works).
3. Repeat until clicking either the toolbar select menu or one of the options causes the caret to jump.

Using Quill Snow theme. The number of times to repeat is inconsistent and seems to be independent of frequency, but generally it's around 5-10 times. As far as I can tell, it occurs on Chrome 44 and Opera 31 (OS X Yosemite). Cannot reproduce in Firefox 39 or Safari 8.0.6.

**Comment by muhleder** [comment]
Might be related to this one.
https://github.com/quilljs/quill/issues/415
We're seeing some weird jumping issues in some cases as well. Inconsistent behaviour as well, sometimes it happens, sometimes it doesn't.

**Comment by jhchen** [comment]
I'm not understanding step 2, particularly the overlaps editor space part. Can you clarify?

**Comment by acrylic-origami** [comment]
![out](https://cloud.githubusercontent.com/assets/13635288/9375499/4d48264c-46cf-11e5-97b0-5e1c2c1addd5.gif)

@jhchen Hopefully the image will help clarify what I mean. Selecting an option on top of the editor space will sometimes cause the editor will focus and the caret will jump under the mouse cursor as if the menu weren't there. I specify "overlapping the editor space" in case the behaviour is different if, say, there is a large margin between the toolbar and the editor.

@muhleder Yup, sounds exactly like what I'm experiencing. I suspect that focusing "through" the select menu is another symptom of the problem. I tried to give your fork a spin, but the issues were only exacerbated? I can't apply any styles at all without caret-jumping and editor-unfocusing. I'll have scrutinize a bit more, but would you mind explaining how your change works?

**Comment by muhleder** [comment]
@acrylic-origami Sure, so from reading other related issues the jumping is caused by the focus called in initFormat()

https://github.com/muhleder/quill/blob/ca9cd7b6b1005969a26239a8f60762a476562edb/src/modules/toolbar.coffee#L43

so I removed that but then @quill.getSelection() was not able to get the selected text from the editor.

Looking at @quill.getSelection() 

https://github.com/muhleder/quill/blob/ca9cd7b6b1005969a26239a8f60762a476562edb/src/quill.coffee#L161

it's really just a proxy for @quill. getRange()

https://github.com/muhleder/quill/blob/ca9cd7b6b1005969a26239a8f60762a476562edb/src/core/selection.coffee#L18

which has an ignoreFocus option. So I added the ability to set that option in @quill.getSelection(), and called it from initFormat(), and the initFormat() then picked up the range properly.

This behaviour in this issue doesn't come from initFormat() I believe, so there may be another call to @quill.focus() in whichever function handles the dropdown here?

**Comment by acrylic-origami** [comment]
@muhleder I spent a few hours tinkering around and still can't rectify the bugs I'm getting with your fork. If text is highlighted, the format is applied normally. However, with a collapsed selection and without [this call](https://github.com/quilljs/quill/blob/develop/src/modules/toolbar.coffee#L56) to @quill.focus(), the format isn't applied. 

In the process though, I may have found the underlying cause of both our issues, and strangely it appears to be race condition-related? `Editor.checkUpdate()` is called periodically based on [this setInterval](https://github.com/quilljs/quill/blob/develop/src/core/editor.coffee#L21) which subsequently makes a call to `@selection.update()`. Comparing `@selection.range` before and after this call, I can confirm that selecting an option from a toolbar select before `@selection.update()` somehow interrupts execution and moves the caret (leading to a discrepancy in the before- and after- Range objects). I feel that [this SO answer](http://stackoverflow.com/a/2734311/3925507) may be relevant.

Removing the `setInterval` call actually reproduces your issue _every time_ a toolbar item is selected. I have no idea why this is, and I don't know if there is an elegant way to clean up the event handling that is causing these problems. I suspect not...

**Comment by jhchen** [comment]
I believe this is the same root cause as #487 where the mouse action is a slight drag, not merely a click.
