### ISSUE TITLE
Cursor jumps to the very beginning when switching 'bullet' or 'list formats

### ISSUE THREAD

**Issue by csk157** [quilljs/quill#461]
Hello, I have noticed a strange issue in Chrome:
![quill-bug](https://cloud.githubusercontent.com/assets/2392131/9441670/be9d4c04-4a77-11e5-934d-7bafe0fff289.gif)

When quickly switching `bullet` or `list` formats on/off with the mouse slightly moving with over the toolbar button (notice the mouse slightly moving upwards in the recording), the editor's cursor jumps to the beginning of the document. Also happens at slower paces (compared to the gif).

Firefox and Safari do not seem to be affected.

**Comment by thomsbg** [comment]
I can confirm -- it looks like (on the demo page at least) that clicking and dragging anywhere inside the toolbar will move the cursor to the beginning of the document.

**Comment by acrylic-origami** [comment]
Related: #415 #456 

From what I can tell, the problem is caused by the event that changes the formatting interrupting the execution of a periodic function that would otherwise compensate for the cursor reposition from the editor defocus.

**Comment by jhchen** [comment]
The problem was very simple: image-tooltip was incorrectly setting the selection to the 0th index when it didn't know what to do. This was more of an issue before quill's internal selection manager kept track of the last known cursor position (useful when a tooltip gets focus and needs to switch back to the last known position when closed).
