### ISSUE TITLE
Pasted text produces unexpected authorship attribution

### ISSUE THREAD

**Issue by atombender** [quilljs/quill#505]
I just tried the [demo](http://quilljs.com/examples/):

1. Select all text.
2. Paste a bunch of text.
3. Deltas now full of random-looking holes (individual characters not authored by "Gandalf"), presumably due to some kind of diffing algorithm, even though _all_ the text I pasted was different.
4. Hit Undo.
5. Entire document is now authored by "Gandalf."

**Comment by jhchen** [comment]
The diffing algorithm is on the character level so the holes are due to common characters in the original and pasted text. The result I agree is surprising to the casual observer though so perhaps there could be some heuristic that does an entire replacement if the ratio between change length and text length is too high.

The authorship module does not necessarily show the original author but rather the most recent, so it's working as designed. Gandalf may not have written the original text but he did cause the undo so he's the reason the text is there which is who the authorship module wants to show.

**Comment by atombender** [comment]
I understand the technical reason, but it's not going to cut it in the real world, where people make mistakes (e.g. by accidentally painting over the entire document). Undo should work consistently with authorship information: if I make a change and undo it, I should be undoing my authorship, too.

It's entirely different if I replace the content with different text, even if there are similarities in the text that a diffing algorithm would pick up. Sure, if I _manually edit_ the text by swapping out 99% of the characters, then 99% are authored by me and 1% should stand with the original authorship. But I would argue quite strongly that if I _paste_ something over something else (by selecting the text before pasting), then arguably my paste is 100% mine, regardless of the pre-existing content. It should be treated as the equivalent to deleting, then inserting, and result in zero holes. There's no heuristic needed.

**Comment by jhchen** [comment]
Authorship is no longer a part of Quill in the 1.0 beta preview.
