### ISSUE TITLE
Is there any possible we can write md in the quilll as the pagedown do

### ISSUE THREAD

**Issue by CooCooooo** [quilljs/quill#507]
I wonder would this feature be add to quilljs in the future

**Comment by jhchen** [comment]
Not sure if you mean using Quill as a markdown editor or having Quill's contents output as markdown. The former is a different use case than Quill is intended for. The latter is not necessarily compatible since Quill contains formats Markdown cannot express, but even if Quill's formats were limited it would be better suited as an external module.
