### ISSUE TITLE
Help with security.

### ISSUE THREAD

**Issue by woverton** [quilljs/quill#510]
Hey guys, this project really looks great.

I am wondering how you would go about sanitizing the output on the server (in node). I understand that this package does not support that and probably should not. I'm just looking for some advice as blindly accepting Quill's output and then printing it to other users is obviously very insecure.

I have tried using projects like: https://www.npmjs.com/package/sanitize-html and many others but they all strip out tags needed by Quill. 

Once again, great project and thanks for your help!

**Comment by jhchen** [comment]
From sanitize-html's docs it looks very promising. It looks like you just have to configure it. Ex this works for the content on Quill's homepage:

```javascript
var clean = sanitizeHtml(dirty, {
  allowedTags: sanitizeHtml.defaults.allowedTags.concat(['span', 'img']),
  allowedAttributes: {
    '*': ['style'],
    'img': ['src']
  }
});
```

**Comment by benbro** [comment]
@woverton can you explain about the security issue?
I wasn't aware that a user can inject a script using the editor.

**Comment by jocoolie** [comment]
Any user input could be a potential problem and should be sanitized - for
example, maybe you could use the console to directly edit the contents of
quill and inject arbitrary javascript. I think that's what is being
considered. "Users are evil" and all that.

**Comment by benbro** [comment]
If a user manually adds
<script>alert('hello')</script>
will quill apply the delta with the unsafe scrip tag?
I thought that quill only has pre-defined set of safe html tags like <img> and <b>.

**Comment by woverton** [comment]
@benbro Well I could just make a http request from a different script to the endpoint my form posts to. You can never rely on client side sanitization.

**Comment by woverton** [comment]
@jhchen Allowing image tags with src would allow user's to load remote javascript with image tag.

**Comment by brettimus** [comment]
Wouldn't that only be an Xss concern if you failed to sanitize (e.g.) the
onerror property?

**Comment by woverton** [comment]
@brettimus My concern is that the url could be a javascript string. https://www.npmjs.com/package/sanitize-html#allowed-url-schemes allows you to force it to use http or https so I can avoid it with these params.

I was just worried about what else could happen. Check out: https://en.wikipedia.org/wiki/Samy_Kamkar#Samy_worm (The fasted spreading worm of all time, which worked by sneaking javascript into an image tag via an online html editor)

**Comment by brettimus** [comment]
Ha! Thanks for that. You made my day :grin: 

Also didn't see the owasp link in your original comment. Feeling slow. Needs coffee. Good morning from portland! :coffee:

**Comment by benbro** [comment]
The problem with image tag is fixed in new browsers.
The question is if a delta in quill can inject a script in modern browsers.

**Comment by woverton** [comment]
@benbro What do you mean by a delta? We're talking about how to sanitize html server side in order to display the output from quill (or a malicious post from something else) to the user safely. 

Thanks :smile:

**Comment by benbro** [comment]
@woverton changes to quill are presented in the form of delta from the previous content.
I thought the security issue is that a user might create a fake delta that injects a script tag into the editor. If that's possible, quill should prevent it but I think it already limits the allowed tags.

**Comment by woverton** [comment]
@benbro My point is that a hacker could completely ignore quill and post malicious html to my API. How can I be sure that my API doesn't start serving script tags etc to other users.

**Comment by benbro** [comment]
@woverton a user posting arbitrary HTML to your server is out of scope of quill.
If, on the other hand, quill might apply insecure delta, that's something that should be fixed or noted.

**Comment by woverton** [comment]
@benbro But without proper guidance, many people using this editor are leaving their websites wide open to hackers. I am trying to use this editor securely, I have managed to do so, but I think the quill docs should be updated to make a point that server side validation is 100% necessary.

**Comment by benbro** [comment]
@woverton This is a server side issue. It's not related to quill in any way. You should never trust user input on the server. I'm not going to comment here any more.

**Comment by woverton** [comment]
@benbro Thats fine, I opened this issues to get help with using quill in a safe fashion and managed to figure it out myself. My point was only that for other editors they often include a little tidbit about making sure you use some verification on the server side. see: http://www.tinymce.com/wiki.php/TinyMCE3x:Security

**Comment by brettimus** [comment]
+1 I think giving this warning is absolutely within the scope of quill. Be
user friendly!

**Comment by brettimus** [comment]
I understand why it seems out of scope, but if a lot of people are using
quill in forms (I am), it's worth giving a reminder somewhere

**Comment by woverton** [comment]
@brettimus Yeah thats exactly what I meant :smile:. A lot of new web developers might use this not realising the dangers.

**Comment by woverton** [comment]
I have created a pull request just to add some needed information to the readme: https://github.com/quilljs/quill/pull/514

**Comment by woverton** [comment]
Pull request was denied. I still feel that a warning should be shown for less experienced developers. Anyway I'm done here.

**Comment by tuomassalo** [comment]
Since this seems to be the first Google hit on this subject (XSS + Quill - at least for any keywords I can come up):

All Quill users should implement server-side sanitation. I'm aware that Quill is a client-side library, but declining to mention server-side sanitation in the documentation is irresponsible.

Secondly, server-side sanitation is not out of Quill's scope, because server-side sanitation should be preferably made to match whatever formatting is allowed client-side with `formats`.

Quill could instruct developers on how to achieve this goal, for example by:

A) shipping with a server-side module, with usage like `sanitize(formats, unsafeHtml)`

B) or pointing to other projects like https://github.com/punkave/sanitize-html and instructing to write the rules based on the chosen `formats`.

Correct me if I'm wrong, but at the moment the "A" solution does not exist.

Even if the Quill developers choose to take no action, I hope this comment helps people who arrive here when searching how Quill can help with server-side sanitation.

**Comment by n1ghtmare** [comment]
Since I couldn't really confirm this, I thought I would ask it here (it's similar to what @benbro was talking about). 

If you post Delta (not HTML) to the server and than store it in a DB. Can a user post a "malicious" Delta that is a security concern when displaying the stored delta as HTML? Or to put it in another way - what happens if I pass Quill a Delta that has "malicious" content (or tags that are not necessary allowed)? Is there some documentation for this?
