### ISSUE TITLE
Move image embeds around freely

### ISSUE THREAD

**Issue by Happy-Ferret** [quilljs/quill#513]
I haven't seen this being talked about before. 
Would it be possible to implement an option that, if enabled, allowed images to be moved around freely, without any sort of text wrapping? 

This behaviour would be similar to Apple Pages and other page layout software, where people generally have more fine tuned control over the flow of text and graphics than in a classical word processor environment.

**Comment by Soviut** [comment]
If you're asking for text reflowing that exceeds the limitations of HTML, then probably not. What are the exact capabilities you're hoping for? Do you have any examples?

The limitations are based on the fact that the editor is not dealing with a specific document size like publishing software such as Pages or Adobe InDesign does. As a result, elements that are positioned using basic left, right, top, bottom anchoring and percentage offsets. Further, to get text to actually flow around images and other elements requires that those elements be "floated" which come with even more restrictions.

To a desktop publisher, this may sound like a step backwards, but it's actually really good because it means text, images and other content can reflow at any browser size and any screen size. This has been really important for mobile websites since they're far more readable on a phone than, say, a PDF is.

**Comment by jhchen** [comment]
The questions @Soviut posed are valid and the lack of answer indicates to me lack of a real need. If this is not the case feel free to re-comment and bring the discussion of merits back to life.

**Comment by CoderBackEndDev** [comment]
it would be helpful if you quill allows to move images freely like
https://www.froala.com/wysiwyg-editor

**Comment by elazarza** [comment]
I would like to see this capability aswell!
