### ISSUE TITLE
API documentation for constructor?

### ISSUE THREAD

**Issue by jakedeichert** [quilljs/quill#517]
I just realized that instead of passing in an ID:
~~~js
var editor = new Quill('#editor');
~~~

You can just pass in the container element itself:
~~~js
var myContainer = document.createElement("div");
var editor = new Quill(myContainer);
~~~

Here's the exact [LOC](https://github.com/quilljs/quill/blob/develop/src/quill.js#L63
) regarding this functionality in **quill.js**: 

~~~js
this.container = typeof container === 'string' ? document.querySelector(container) : container;
~~~

This ability (the constructor) doesn't seem to be specified in the docs anywhere.

Just wondering if it should at least be described on the API page: http://quilljs.com/docs/api/

**Comment by jhchen** [comment]
It's in the [configuration](http://quilljs.com/docs/configuration/) page but not in the api page. I'm not opposed to adding it there as well / instead but it's not obvious which section (retrieval, manipulation, etc) it should go under. What do you think?

**Comment by jakedeichert** [comment]
Wow I completely missed that.

I see things are organized on the API page, but it probably should be it's own section at the top because it's the constructor. Would you agree?

**Comment by jakedeichert** [comment]
Maybe I'm wrong. The configuration page makes sense. I should have really looked harder first!

API just made sense to me since I figured all functions (including constructor) would have been listed there.

**Comment by jhchen** [comment]
Yes I can see how one would look for it in the API page and not in the Configuration page so you're probably not the only one. The constructor is more complex than the other calls though just because of the configuration options variable you can pass in which is why it has its own page. I have considered changing the name from Configuration to say Initialization and that would probably lead more people looking for constructor docs to click on that link but maybe cause fewer people who are looking for configuring the editor to find what they're looking for. Not sure there is a clearly right path so I will just leave it as if for now.
