### ISSUE TITLE
Selecting text from left to right (container padding issue)

### ISSUE THREAD

**Issue by sloppy9** [quilljs/quill#541]
I was playing around with the demo editor on your website, and found that I had trouble changing text when I made a selection from left to right.

Click between the editors border and the text, then drag a selection across to the right. It looks like the text has been selected in Firefox, in Chrome no selection is made, and Internet Explorer selects the whole content.

The problem is the padding on the container, it gives the false impression you can make a text selection there, but you end up selecting the element inside instead.

As a temporary fix, I've moved the padding from `ql-container` to `ql-editor` which resolves the issue.

**Comment by jhchen** [comment]
Thanks for the report. I don't recall why the padding is on `ql-container` vs `ql-editor` but will investigate the reason but simply moving it could be a potential long term fix.

**Comment by jhchen** [comment]
The motivation before the put the padding on the container was so scrolling is synchronized between the editor and other module containers (since its relative parent was doing the scrolling). Scrolling changed back to the editor for other reasons but this is no longer an issue as a result in the [beta](https://beta.quilljs.com/) release.
