### ISSUE TITLE
Headings behavior

### ISSUE THREAD

**Issue by bL0p** [quilljs/quill#564]
I've been working with the npm version of quill (0.20.1). However, I needed Headings in the editor (changing text font-sizes didn't work for me).
I tried the quill version that is in the `develop` branch and I think the _heading_ and _subheading_ options behave strangely:

1. Select some text (not the whole line)
2. Change the selection to a heading
3. Try to change the same selection back to paragraph -> it doesn't seem to work

Also if, for the same selection, you alternate between _heading_ and _subheading_, a `<h1>` is added every time.

My suggestion is: why isn't the heading a _line_ format? I've made some changes in the code that is in `master` to demonstrate this: https://github.com/quilljs/quill/compare/master...bL0p:headings

The idea is that a line can be a list or a heading (i.e. they are exclusive between each other). Although this disables the possibility of having lists inside headings, I think this way the behavior is more consistent.
I'll be happy to contribute to the code with this, if you like.

**Comment by jhchen** [comment]
The develop branch is a work in progress.

**Comment by bL0p** [comment]
I know. What I was trying to say is that, if you like the idea I was presenting, I would be happy to submit a PR to the `develop` branch with the implementation.

**Comment by jhchen** [comment]
Headings will be in 1.0 but what you are looking at in the develop branch is not finished yet, hence the strange behavior. The document model in Quill has undergone significant changes so your implementation will not be compatible with the 1.0 codebase. I don't want to make any more changes/releases to Quill 0.x in order to focus on and push 1.0, as it will be much better.
