### ISSUE TITLE
Background color height is incorrect on large text

### ISSUE THREAD

**Issue by jhchen** [quilljs/quill#61]
1. Select a word
2. Make the font size large
3. Add background color

Background color does not fill the entire height. Seems to be because the span controlling the size does not expand its parent (which controls the color). Applying the formatting in reverse (color then size) does not have this issue.

**Comment by EricGrange** [comment]
A possible fix is to specify "background-color: inherit" in the font-size span

**Comment by jhchen** [comment]
Excellent idea! Thanks!

**Comment by EricGrange** [comment]
The fix you committed only works in the editor, and not when the html is displayed afterwards.
The "background-color: inherit" should be applied alongside the font-size in the span's inline style, not in the CSS

**Comment by jhchen** [comment]
What do you mean when the html is displayed afterwards? The only difference between an inline style and css style is precedence.

**Comment by EricGrange** [comment]
By afterward I mean "once it has been edited", the purpose of the editor being to edit rich text as html, this html is also meant to be displayed after its edition, without no editor in sight.

The main difference between inline & css style is not precedence, it is that inline style is part of the html, so when you display the html, inline style is guaranteed to be there, while stylesheet css is not.

It would be different if the editor was doing its editing based on css classes rather than inline styles, then having an external stylesheet to go alongside the html would be expected. But given that the editor edits inline styles, IMHO it should maintain coherent inline styles, rather than require a specific css stylesheet for the html to be displayed "as edited".

**Comment by jhchen** [comment]
There are already several rules in the base Quill stylesheet that would have to be replicated to maintain visual correspondence with the editor. It's also not sufficient to just add the inherit rule to spans--it'd have to be added to all inline styles (otherwise color -> bold -> size would still trigger the bug) which is much messier markup. Fwiw Quill is moving away from inline styles by default in some future release.
