### ISSUE TITLE
change font color black din't work 

### ISSUE THREAD

**Issue by jiangli373** [quilljs/quill#642]
For example the font's color is red, when i change it color to black like below scrrenshot ,but it din't work

![image](https://cloud.githubusercontent.com/assets/1632862/15006340/6edbf7c6-1202-11e6-92df-67e2276712c6.png)

the demo is quilljs.com

**Comment by jhchen** [comment]
What browser + OS are you using?

**Comment by jiangli373** [comment]
sorry,  I forget to supply that

browser: chrome 50.0.2661.86 (64-bit)
os: mac  10.11.3

**Comment by jhchen** [comment]
When you create an issue, a template is provided requesting platform information. Please do not ignore this in the future as it wastes time back and forth.

I have tried your instructions on Mac 10.11.4 on Chrome 50.0.2661.94 (64-bit) and cannot reproduce. I doubt the patch version is the difference. To confirm, this happens repeatedly and consistently, and you have tried with all browser extensions disabled? Does it do this with any other format like bold or background color?

**Comment by jiangli373** [comment]
thank you for your reply.

I disable all browser extensions. 

in http://quilljs.com/ 

First i set body's color with red like below scrrenshot

![image](https://cloud.githubusercontent.com/assets/1632862/15007367/fc23ae14-120a-11e6-91a7-6197bc4dc8e7.png)

then i change word's color except black color all did work 

![image](https://cloud.githubusercontent.com/assets/1632862/15007445/9fbbea0a-120b-11e6-874f-25e48f0c7572.png)

when i click black color ,the 'built'  didn't change color ,open chrome dev tools, i found the element did't have color style

![image](https://cloud.githubusercontent.com/assets/1632862/15007468/e2dd20e2-120b-11e6-8a59-316dd1d2898b.png)

**Comment by jhchen** [comment]
Okay I was under the impression the text was red because you selected+all and clicked on red, not opened the inspector and set the default color to be red.

In the demo on quilljs.com the default color is black so when you click the black color icon, it's not actually setting it to black, it's removing any color value. If you want your editor to have the default be red, then you need to set up your toolbar to have red remove color, and black to set the color to black.

**Comment by adamtobey** [comment]
I ran into a similar issue with default font color using Bootstrap with a white font and dark background. Because the background of the editor was white, I wasn't able to see the text and thought it wasn't working initially. Once I realized the problem it was an easy fix of course. I understand this isn't technically a bug since it seems to be intended behavior, but I just thought I'd give my input. Maybe a little note in the basic documentation about this would be nice. 

Thanks!

**Comment by StormRaider2495** [comment]
Just need to setups the color array with the black(#000) value. In the default state, when not mentioned any values in the color array, the black is set to false.
`
{ color: [
      "#000000", "#e60000", "#ff9900", "#ffff00", "#008a00", "#0066cc", "#9933ff",
      "#ffffff", "#facccc", "#ffebcc", "#ffffcc", "#cce8cc", "#cce0f5", "#ebd6ff",
      "#bbbbbb", "#f06666", "#ffc266", "#ffff66", "#66b966", "#66a3e0", "#c285ff",
      "#888888", "#a10000", "#b26b00", "#b2b200", "#006100", "#0047b2", "#6b24b2",
      "#444444", "#5c0000", "#663d00", "#666600", "#003700", "#002966", "#3d1466",
  ] },
`
