### ISSUE TITLE
selections aren't changing on `<select>` toolbar items.

### ISSUE THREAD

**Issue by jonnolen** [quilljs/quill#674]
selects aren't working, drop down can be opened but selecting an option doesn't do antyhing

**Steps for Reproduction**

1. Visit http://codepen.io/jonnolen/pen/GZaaaX
2. try to select anything other than the selected option on any of the drop downs

**Expected behavior**:  selection changes.

**Actual behavior**: selection doesn't change

**Platforms**:  Chrome Version 50.0.2661.94 (64-bit), OS X 10.11.4

**Version**: //beta.quilljs.com/1.0.0-beta.2/quill.js

**Comment by jhchen** [comment]
They're all working for me on Mac 10.11 Chrome 50.0. Can anyone else reproduce?

**Comment by Joeao** [comment]
Cannot reproduce on OSX 10.11.3, Chrome 50.0.

**Comment by benbro** [comment]
Isn't it the same as https://github.com/quilljs/quill/issues/665?

**Comment by jhchen** [comment]
This is probably a duplicate but it was sufficiently ambiguous (technically selection is the user's highlighted text so that should not change, but the format of the highlighted text should) so if others could reproduce I was going to ask for clarification. But it seems like that is the most likely case and we can reopen if not.
