### ISSUE TITLE
Allow disabling the history module

### ISSUE THREAD

**Issue by emanuelbsilva** [quilljs/quill#691]
Right now, the quill constructor is automatically creating the history module. There is no way to bypass it.

**Comment by jhchen** [comment]
Some modules like History are required: http://beta.quilljs.com/docs/modules/.

**Comment by emanuelbsilva** [comment]
I understand that, but in that case there should be an option to disable the keyboard bindings for the history. Even if a user of the API wants to, there is no way to bypass the bindings, because quill, on the constructor is always the first to create them.

**Comment by jhchen** [comment]
It's possible, just not easy. You can replace required modules, in theory with no-op modules that do nothing but this is not a use case I will provide support for because I think it invites more questions and problems than it actually solves.

**Comment by chearon** [comment]
@jhchen our web application has its own undo stack, so we've had to modify Quill to take the `history` module out. Provided you preventDefault the undo/redo keyboard events in order to keep the browser from undoing the last non-quill-handled thing, and do your own `updateContents(delta)` from the stack, I haven't been able to find any bugs that it causes. Would be nice to have it supported with the caveats noted!

**Comment by babakhanov** [comment]
just specify `maxStack` to `0`
`
modules: {
  history: {
    maxStack: 0,
    userOnly: true,
  },
}
`

**Comment by michelcouto** [comment]
setting maxStack works great... BUT, I would like to disable only the user related history. And keep the api ones available. Setting maxStack 0, even using userOnly: true, disable history for users AND api.
