### ISSUE TITLE
Selected text with background color has confusing style

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#704]
[Describe the issue]
I see the same issue on Firefox when editing an email in GMail so it's a Firefox bug/feature and you'll might decide to ignore it.
Selected text with purple background looks like it is not selected on Firefox.
On Chrome it looks fine.

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/
2. Select the title 'Quill Rich Text Editor'.
3. Give it a purple background color - The color on the right of the first row. rgb(153, 51, 255)

**Expected behavior**: [expected]
The text should look like it has a background color and selected.

**Actual behavior**: [actual]
The text doesn't get a background color until we unselect it.
The text color looks blue.

**Platforms**: [ex. Chrome 48 on Mac 10.11]
Firefox 46 on Windows 7.

**Version**: [version]
1.0-Beta.3

![quilljs-background](https://cloud.githubusercontent.com/assets/75841/15530694/aacc7de8-225e-11e6-9229-acdc4448d1ca.png)

**Comment by jhchen** [comment]
Yes it does look like native behavior. If you double-click (to select the word) on the second "Test" on https://jsfiddle.net/Lo22dgaz/ before the 2.5s timeout it shows this with just a contenteditable. Since it's also only on Firefox on Windows (did not test on Linux but does not occur on Mac) I'm not sure it's worth adding a workaround within Quill. Thanks for the report though.
