### ISSUE TITLE
Superscript and Subscript Not Working

### ISSUE THREAD

**Issue by lance13c** [quilljs/quill#724]
When inserting or formatting the text with superscript and/or subscript. The text remains as normal characters. Is my syntax wrong?

Getting syntax from: https://github.com/quilljs/quill/blob/0cbc2db7860b9d1da3ba5f235f72164c0f662576/test/unit/formats/script.js

Example:
http://codepen.io/lance13c/pen/JKddWZ

I expected them to become superscript and subscript characters. 

On my screen they are remaining as normal characters.

Chrome 50
Version: latest

**Comment by jhchen** [comment]
Two problems:

1. You are using version 0.20.1 and superscript/subscript is a 1.0 feature. I would discourage using cdn.quilljs.com/latest/ for this reason that you don't precisely specify what version you are using. /latest does not (yet) point to 1.0 since 1.0 is still in beta. Use cdn.quilljs.com/1.0.0-beta.3/quill.min.js for example.

2. You are inserting text beyond the end of the document. `insertText(0, 'valid index', { script: 'super' })` works just fine.
