### ISSUE TITLE
Default toolbar values for dropdowns in the snow theme

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#727]
The toolbar docs says the snow theme has default values for dropdowns:
http://beta.quilljs.com/docs/modules/toolbar/

> Note Themes may also specify default values for dropdowns. For example, Snow provides a default list of 35 colors for the color and background formats if left unspecified.

The example in the docs use the default theme but it probably should use the snow theme.

In my test, dropdown buttons are hidden or missing the options.

**Steps for Reproduction**

``` javascript
var toolbarOptions = [['font', 'size'],
                      ['bold', 'italic', 'underline', 'strike'],
                      ['color', 'background'],
                      [{'script': 'sub'}, {'script': 'super'}],
                      [{'header': 1}, {'header': 2}, 'blockquote', 'code-block'],
                      [{'list': 'ordered'}, {'list': 'bullet'}, {'indent': '-1'}, {'indent': '+1'}],
                      [{'direction': 'rtl'}, 'align'],
                      ['link', 'image', 'video'],
                      ['clean']];

var quill = new Quill('#editor-container', {
  modules: {
    toolbar: toolbarOptions
  },
  placeholder: 'Compose an epic...',
  theme: 'snow'
});
```

**Actual behavior**:
font and size buttons are hidden.
color, background and align rendered as buttons instead of select box.

**Platforms**: 
Firefox 46 on Windows 7.

**Version**:
Quill 1.0-beta.4

**Comment by jhchen** [comment]
What's going on here is the toolbar options interpret a string to always mean making a button. Since there's no icon for a font or size button, they appear blank. There is an icon for align so it renders but as a button and not a dropdown. The left unspecified part was meant it is specified if the control should be a button or a dropdown, but not specified what the options for the dropdown is. So this would work:

```js
var toolbarOptions = [[{'font': [] }, {'size': [] }],
                      ['bold', 'italic', 'underline', 'strike'],
                      ['color', 'background'],
                      [{'script': 'sub'}, {'script': 'super'}],
                      [{'header': 1}, {'header': 2}, 'blockquote', 'code-block'],
                      [{'list': 'ordered'}, {'list': 'bullet'}, {'indent': '-1'}, {'indent': '+1'}],
                      [{'direction': 'rtl'}, {'align': [] }],
                      ['link', 'image', 'video'],
                      ['clean']];
```

I do think this is confusing and not the cleanest syntax. I do want to allow for use cases where formats may either be activated by a button or a dropdown so I'll have to think more about a better balance but open to suggestions in the meantime.

**Comment by benbro** [comment]
In the meantime, the docs could say:

> Snow provides a default list of 35 colors for the color and background formats **if set to an empty list**: [{'color': []}, {'background': []}]

instead of

> Snow provides a default list of 35 colors for the color and background formats **if left unspecified**.

**Comment by jhchen** [comment]
It seems like the decision is whether or not to whitelist font, color, size, background, and align to be initialized as a dropdown instead of a button.

In the normal case, if the toolbar option sees ['custom-font'], it cannot determine whether or not that format takes just boolean values or a whitelist of values, and even if so, what should be shown. Which is why I think the only option is either to whitelist font, color, size, background, and align, or leave things as is.

Thoughts?

**Comment by benbro** [comment]
Aren't font, color, size, background and align already [whitelisted](https://github.com/quilljs/quill/blob/develop/themes/base.js#L80) in a way?
The only problem with a whitelist is that it's less extendible and that it should 'know' about different formats.

I think that leaving things as is with an empty list is bit unintuitive but fine:
```javascript
{'font': []}
```

Another option is being able to import the default list of options from the theme.
```javascript
let fontColors = Quill.import("snow/colors");
{'font': fontColors}
```

**Comment by jhchen** [comment]
Okay I'll just leave things as is then thanks!
