### ISSUE TITLE
Bad video url produce blank space

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#804]
[Describe the issue]

**Steps for Reproduction**

1. Visit http://beta.quilljs.com/docs/formats/
2. Click on the video button
3. Enter a youtube url
https://youtu.be/QHH3iSeDBLo

**Expected behavior**: [expected]
Show error or at least ignore the bad url

**Actual behavior**: [actual]
CORS error is written to the console.
```
Load denied by X-Frame-Options: https://youtu.be/QHH3iSeDBLo&feature=youtu.be does not permit cross-origin framing.
```
A placeholder is created for the video but it is blank.

**Platforms**: 
Firefox 47 on Windows 7

**Version**: [version]
1.0-beta.9

**Comment by jhchen** [comment]
As you saw I added https://github.com/quilljs/quill/commit/b92b6f47fed3fa7c8763e58a79fc6b3c779827c1 to account for common video URLs that are not video files themselves. However for other less common URLs Quill will not actually know a link does not resolve to a Video until it tries to access it so I'm not sure a CORS error or other access errors are avoidable. There could be a heuristic to avoid requesting the Video but none will be perfect. For example there's no way to know if a file exists on a remote server without checking so 404 errors are never completely preventable.

Quill still inserts the embed in with a bad video URL because it seems easier to reason about this behavior than doing nothing. There might be a lot of reasons no action is taken but loading the VideoBlot with a bad URL results in errors in the console about the bad URL, with specific reasons like CORS or 404.
