### ISSUE TITLE
Max Height for Text Area

### ISSUE THREAD

**Issue by beeterry** [quilljs/quill#812]
Is there a way to set a "max-height" for the text area? For example, I want to be able to set a max-height of 300px on the text-area, so that when the user hits that 300px mark and they press the enter key, it won't let them drop down any below that height.

**Comment by jhchen** [comment]
You can just use the `max-height` css style if you want to allow scrolling. If you want enter to not do anything if that would exceeds the height then you'll have to combine some [API](http://beta.quilljs.com/docs/api/) listeners and calls. Note this is pretty brittle though since there are many ways for height to change such as applying formatting or text wrapping.
