### ISSUE TITLE
Custom formatting disappears in Chrome V 51

### ISSUE THREAD

**Issue by dritsher** [quilljs/quill#820]
____This turns out to be a Chrome issue_____

When I repeatedly insert words with custom formatting, after a certain number of words, the deltas change to line formatting and the custom formats are lost.

**Steps for Reproduction**

1. Visit http://codepen.io/dritsher/pen/OXkdPK
2. If you click on any number after 390, the console will report that the custom style is applied to the text.
3. If you click on any number before 389, the console will only report "bold" & "italic," the custom style will be removed.

**Expected behavior**: The custom style persists.

**Actual behavior**: The custom style disappears

**Platforms**: Mac 10.9.5 on Chrome Version 51.0.2704.103 (64-bit)  (This does not happen in Firefox or Safari...  and in the process of writing this up, I just determined that it does not happen in Chrome Version 52.0.2743.82 (64-bit), but since I've got this worked out, I'll post anyway.)

**Version**: beta.9

**Comment by jhchen** [comment]
I think you should use `Parchment.Attributor.Attribute('mycodeword', 'mycodeword', { scope: Parchment.Scope.INLINE });` instead of `Parchment.Attributor.Style`. There is no css style named mycodeword so what the browser does in this case is unreliable is but you can have arbitrarily named attributes.
