### ISSUE TITLE
Weird issues with formatted text deletion

### ISSUE THREAD

**Issue by cutteroid** [quilljs/quill#824]
Cursor position is incorrect when deleting formatted text.

**Steps for Reproduction**

1. Visit [beta.quill.js](http://beta.quilljs.com/)
2. put cursor at the beginnig of `open source` link in second paragraph and hit DEL.

 **Expected behavior**: first symbol of the link deleted, cursor position preserved

 **Actual behavior**: first symbol of the link deleted but cursor position changed

3. put cursor at the end of `open source` link in second paragraph and delete link with BACKSPACE.

 **Expected behavior**:  link deleted, cursor position preserved

 **Actual behavior**:  cursor position changing after last symbol of the link deleted (reproducible in all browsers except Chrome)

**Platforms**:  Firefox 49.0a2, Firefox 47.0.1, Chrome 52.0.2743.82 on OS X, IE 11, Edge on Windows 8

**Version**: 1.0.0-beta.9

**Comment by jhchen** [comment]
Thanks for the report! I think this commit https://github.com/quilljs/quill/commit/bfee0cbb979e83962c947a18f14bf323a23e3d60 also fixed this issue and should be in the next release.

**Comment by cutteroid** [comment]
In build from current `develop` branch step 2 fixed but step 3 is still reproducible

**Comment by jhchen** [comment]
Sorry I did not notice you had different expected behaviors for backspace and delete. I do not agree with this. Most rich text editors do not treat links to be atomic and non to my knowledge exhibit different behavior for backspace and delete.

The expected behavior for Quill is that links are not atomic and consistent between backspace and delete: delete removes the character after the cursor, backspace removes the character before the cursor. You may add a custom keybindings to [Keyboard](http://beta.quilljs.com/docs/modules/keyboard/) if you wish to modify this.

**Comment by cutteroid** [comment]
I'm totally agree with described expected Quill behavior.
Looks like my description of issue was not very clear, sorry,

Here i'm deleting link with backspace. Notice where cursor appears after deletion.
![bs](https://cloud.githubusercontent.com/assets/20125880/17269733/2d16f976-5659-11e6-9c4e-4ee8ccb7ca28.gif)

And i'm having this bug with all formatted text (links, bolds, italics etc)

**Comment by jhchen** [comment]
Ah I see thank you for the clarification.
