### ISSUE TITLE
Saving document to JSON

### ISSUE THREAD

**Issue by ccorcos** [quilljs/quill#83]
can I save this document to some sort of JSON format to save in Mongodb?

**Comment by chrisdone** [comment]
For future passers by, it outputs like this:

![Screenshot from 2021-12-14 17-00-57](https://user-images.githubusercontent.com/11019/146044473-adff0bf9-9075-409e-a9e8-6ec063dc05e7.png)

Which can be a little confusing because it's a set of commands rather than a tree. Note that the heading is "inserted" as text, and then the heading property is applied as a separate thing in the list, to the `"\n"`. This is might seem bizzare to some people. This is how Quill works internally, however. See [Delta](https://quilljs.com/docs/delta/).

**Comment by MelikaBrz** [comment]
......mmmmmmmmmmmmm
