### ISSUE TITLE
Formula module doesn't apear

### ISSUE THREAD

**Issue by yonathan06** [quilljs/quill#864]
I'm using quill beta 11 and trying to add the `formula` module.

```js
var quill = window.quill = new Quill('#discussionQuill', {
	theme: 'snow',
	placeholder: 'Your questing here...',
	modules: {
		'formula': true
	},
}); 
```

Everything appears fine, except the icon for the formula module does not show. I tried to use the `toolbar` module (perhaps it is related?), but the toolbar didn't appear at all. 

Is it a known issue?

Thanks!

**Comment by jhchen** [comment]
Adding the formula module does not automatically add it to the toolbar since some users want to use their own UI and the toolbar is an independent module. Take a look at [toolbar](http://beta.quilljs.com/docs/modules/toolbar/) for details on how to configure the buttons that show up. An example would be:

```js
var quill = new Quill('#discussionQuill', {
    theme: 'snow',
    placeholder: 'Your questing here...',
    modules: {
        'formula': true,
        'toolbar': [['formula']]
    },
}); 
```

**Comment by yonathan06** [comment]
Thanks! I believe it isn't written in the docs.
