### ISSUE TITLE
Multiline code from github is pasted as single line in quill

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#887]
[Describe the issue]
When I copy&paste code from github to quill, the indentation is lost and the text is on a single line.

**Steps for Reproduction**
1. Visit http://quilljs.com/playground/
2. Select and copy the javascript code from https://github.com/quilljs/quill/blob/develop/core.js
3. Paste the text in quill

**Expected behavior**: [expected]
Formatting should be preserved.

**Actual behavior**: [actual]
The text is pasted as one long line

**Platforms**:
Chrome 52 on Windows 7

**Version**: [version]
1.0.0-rc2

**Comment by jhchen** [comment]
This is difficult to fix since Github is not using semantic tags for their code so without targeting Github markup specifically (which they could change at any time), it's not possible to know what's being pasted is code.

**Comment by benbro** [comment]
I'm not expecting Quill to guess that this is a code block but if possible to preserve the line breaks and indentation.
I tried pasting the code to the following editors. All preserve line breaks and indentations:
Notepad on Windows 7
Notepad++ on Windows 7
Gedit on Ubuntu
Simple textarea on Firefox and Chrome

**Comment by jhchen** [comment]
I'm mostly commenting to document so I or others do not have to rediscover findings. Since the Github is using tables, pasting into a Quill with table support would preserve the indenting/lines but also act like a table with cell boundaries. For example pasting in Word shows the borders and it's not possible to outdent or change indentation, as you would expect for code.

**Comment by benbro** [comment]
Fixed in v2.0.0-rc.0
