### ISSUE TITLE
how to  quill.getHTML()

### ISSUE THREAD

**Issue by che3vinci** [quilljs/quill#903]
just as the title said

**Comment by TomCaserta** [comment]
Its no longer the concern of quill to provide HTML and the API has abstracted away from providing the HTML.

I'd argue that this library is fairly useless without this functionality as nothing else currently can parse the delta object and provide a html structure which is probably what most people want to use quill for. I understand why they wish to abstract away from providing HTML (and accepting HTML as its initial value) but I wish there was something in place before making this change in various languages to parse the delta objects and provide HTML so we can just store the delta object in our database and render it when necessary.

In the meantime you can use:

     quill.container.firstChild.innerHTML

To get the contents of the rendered HTML according to the browser you are currently on.

**Comment by jhchen** [comment]
Quill has always used Deltas as a more consistent and easier to use (no parsing) data structure. There's no reason for Quill to reimplement DOM APIs in addition to this. `quill.root.innerHTML` or `document.querySelector(".ql-editor").innerHTML` works just fine (`quill.container.firstChild.innerHTML` is a bit more brittle as it depends on child ordering) and the previous getHTML implementation did little more than this.

**Comment by TomCaserta** [comment]
Ah fair enough, assumed it used deltas but thought it was only internally previously, I've not followed the project for long. Just remember using it as a somewhat drop in replacement of TinyMCE etc. Thanks for the info regardubg quill.root.innerHTML.

**Comment by artaommahe** [comment]
@jhchen thx for `quill.root.innerHTML` but why no explicitly `getHtml()` method due to most apps stores result content in html format? it's necessary to get result html before saving

**Comment by f15gdsy** [comment]
I would like to use delta format, but for rendering the format, I have to include the whole editor, which is too heavy for me.

**Comment by fernandogmar** [comment]
Hi guys,

There is another concern, `quill.root.innerHTML` returns the html, right?

As I could check `.ql-editor`  class that use `white-space: pre-wrap;` so you can notice when you are typing multiple white spaces: `hello----there` (using dashes for better visualization of the spaces). But saving and showing later the html from `quill.root.innerHTML` will show just: `hello there`.

A similar problem already fixed on quilljs it is when you add break lines that creates a new line as follow `<p></br><p>` and when you get the text this is transformed to `\n`

Following this solution for break lines.... I think something similar should happen with white spaces
when you get the html it should be something as: `hello&nbsp;&nbsp;&nbsp;&nbsp;there` when you get the  text it should be something as:  `hello----there` (using dashes for better visualization of the spaces). Since you are editing WYSIWYG... so the user is adding 4 spaces conciously, so he wants 4 spaces no only one! :D

It is fair that quilljs don't want to face html transformation problems, but at least it should be worried about how these deltas can be consume as html...  some guides? a different tool? :D In other case this kind of problems would be a cons to adopt quilljs :'(

Thanks for all guys!

**Comment by ysyyork** [comment]
@fernandogmar Why not persist content using delta as json format? I tested and delta will retain multiple spaces.

**Comment by fernandogmar** [comment]
Because this data is used as html so the problem will be always there. From
my point of view deltas only make sense on editing, and always you use
quilljs

2017-02-26 23:31 GMT+01:00 York <notifications@github.com>:

**Comment by ysyyork** [comment]
@fernandogmar I see what you mean. Thanks for reminding. That's also my case.

**Comment by chris-hall-hu** [comment]
Just run into this issue, it took longer than it should to work out how to grab the HTML, now going to have to do some testing to ensure all the formatting in preserved. 

If you are using quill to edit and then simply presenting the edited data somewhere else (without the overhead of quill) this is a bit of a hiccough/potential headache in what otherwise was a very easy integration.

**Comment by fernandogmar** [comment]
[ROOKIE ERROR]
Just for fixing the issue... I decided replace ' ' (character space)  by `&nbsp;` so having two spaces '  ' --> `&nbsp;&nbsp;` , awesome.... but the problem came `&nbsp;` doesn't follow the same rules as ' ' (space character)...

that means the line wouldn't be broken in case it were needed... as (his name shows up Non breaking space)

Searching about this kind of problems it looks like there are more space characters that I already knew: https://en.wikipedia.org/wiki/Whitespace_character

alternative workarounds:
- use EN SPACE &ensp;
- mix NBSP and ' ' character spaces
- mix NBSP with [<wbr>]( http://www.quirksmode.org/oddsandends/wbr.html) (the zero width space)
- using padding with a custom tag

some detailed white spaces:
- [NBSP](https://en.wikipedia.org/wiki/Non-breaking_space)
- [Zero width Space]( https://en.wikipedia.org/wiki/Zero-width_space)

**Comment by danrichards** [comment]
This works.

```
Quill.prototype.getHtml = function() {
    return this.container.firstChild.innerHTML;
};
```

**Comment by Hainesy** [comment]
@danrichards, as @jhchen mentioned, that depends on the order of child elements. A less brittle implementation would be:

```
Quill.prototype.getHtml = function() {
    return this.container.querySelector('.ql-editor').innerHTML;
};
```

**Comment by danrichards** [comment]
Thanks @Hainesy and @jhchen !

**Comment by samgan-khan** [comment]
Hi,
I faced the same issue with quill js. I found a solution. I solved the above problem with the help of a hidden input and a little js in the following way.


 <div id="post-editor" ></div>
  <input type="hidden" name="post" id="post" />

/** 
* js part
**/
var quill = new Quill('#post-editor', {
    theme: 'snow'
  });

var fetch_post_content = function () {
      $('#post').val($('.ql-editor').html());
    }
    $('#post-editor')
    .keyup(fetch_post_content)
    .blur(fetch_post_content);

**Comment by hrrhrst** [comment]
this library is so useless when you can't get inner html properly. as stated above there is no workaround for these stupid ql-cursor tags. please bury yourself retards.

**Comment by markadrake** [comment]
How are any of you integrating QuillJS into a CMS environment? I need the HTML stored. Now I need to store both the `delta objects` and the `HTML` and be cognizant of what I'm sending to the editor. It would be nice to have the getters and setters for HTML content back.

**Comment by isaaclyman** [comment]
I've been using the [quill-delta-to-html](https://github.com/nozer/quill-delta-to-html) NPM package in my webapp, [Edward](https://github.com/isaaclyman/Edward-the-App), and so far it works great. Not an official library, but since insert-only deltas are mostly straightforward to parse, it's not a difficult operation.

**Comment by rengelking** [comment]
I ended up storing the delta, and reconstituting using this function:
`function quillGetHTML(inputDelta) {
        var tempQuill=new Quill(document.createElement("div"));
        tempQuill.setContents(inputDelta);
        return tempQuill.root.innerHTML;
    }`

**Comment by Promotools** [comment]
`$("#myForm").find('#quillEditor .ql-editor').html()`
works for me.
- `#quillEditor`: is the ID of div where editor is loaded

**Comment by sourcegr** [comment]
A little late to the party, but here goes anyway :) 

In order to get any extra spaces the user has inserted, I use

`this.editor.root.innerHTML.split('  ').join(' &nbsp;')`

(note, there are two spaces in the `split` and one space in the `join`!)

**Comment by thenikso** [comment]
the problem with getting the `innerHTML` is that if the cursor is in a "styled" position, something like this is added:

`<span class="ql-something..."><span class="ql-cursor">`:question:`</span></span>`

**Comment by mrspeaker** [comment]
This thread has me a bit worried about using Quill for our project. I chose it because I am big fan of the Delta format - but we have several third-party integrations and they only understand, and will be displaying, plain-old-HTML. Due to some legacy integration, we need to store the text editor data as HTML and reconstitute it each time. We are doing additional transformations on the Delta format after reconstituting it.

Is this unsafe? Pulling the HTML from the browser-rendered output sounds like we are dependent on browser implementations, and discrepancies could occur moving between the two formats. But at some point the Delta must be transformed into HTML to display the HTML in the first place - is there any way to hook into that?

**Comment by fibigerg** [comment]
Is there an official skeleton project to implement our custom Delta to HTML transformations on frontend part of our webapps? Eg. bold could be <b> or <span class="b"> etc.

**Comment by dvtan** [comment]
> There's no reason for Quill to reimplement DOM APIs in addition to this. `quill.root.innerHTML` or `document.querySelector(".ql-editor").innerHTML` works just fine

Won't work for nested lists. Instead of nesting HTML tags like a normal person would, Quill uses... classes. Like `ql-indent-1`, `ql-indent-2`, etc. So basically, the innerHTML is not self-contained, you still have to include the Quill CSS... and at that point, it defeats the purpose of outputting raw HTML.

**Comment by sourcegr** [comment]
@dvtan this is a serious problem... 
I guess not a lot of people cares, because I have it in many projects and nobody ever complained to me.
Don't get me wrong, I don't ike it either! 

Is there any more cases where quill behaves in such an unexpected way?

**Comment by PrasadChinthala** [comment]
> Quill has always used Deltas as a more consistent and easier to use (no parsing) data structure. There's no reason for Quill to reimplement DOM APIs in addition to this. `quill.root.innerHTML` or `document.querySelector(".ql-editor").innerHTML` works just fine (`quill.container.firstChild.innerHTML` is a bit more brittle as it depends on child ordering) and the previous getHTML implementation did little more than this.

Thanks a tone, it has solved the problem. This `document.querySelector(".ql-editor").innerHTML` works just fine

**Comment by n3omaster** [comment]
This worked for me:

`
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>


<script>
    var quill = new Quill('#editor', {
        modules: {
            toolbar: [
                ['bold', 'italic'],
                ['link', 'blockquote', 'code-block', 'image'],
                [{
                    list: 'ordered'
                }, {
                    list: 'bullet'
                }]
            ]
        },
        placeholder: 'Compose an epic...',
        theme: 'snow'
    });

    $("#form").submit(function() {
        $("#description").val(quill.getContents());
    });
</script>`

**Comment by boomanaiden154** [comment]
I recently created a library that adds this functionality to quill. It transforms the delta objects into raw HTML that can be stored in a database, or rendered on the page. It supports formulas, and if you wuld like anything else to be supported, issues/PRs are welcomed. [quillgethtml](https://github.com/boomanaiden154/quillgethtml)

**Comment by aacassandra** [comment]
@boomanaiden154 not work if image has resized

**Comment by boomanaiden154** [comment]
@aacassandra Quill doesn't provide the ability to resize images by default. Could you give more specifics on what library you are using to provide this functionality?

**Comment by aacassandra** [comment]
while this is @Hainesy's answer that I can use. sorry I forgot to tell you about the image resize library. [kensnyder/quill-image-resize-module](https://github.com/kensnyder/quill-image-resize-module)

**Comment by josduj** [comment]
Possible downside of using `innerHTML` is that it can contain 
```html
<span class="ql-cursor">﻿</span>
```

**Comment by pengliheng** [comment]
you are fun.

**Comment by RyanEwen** [comment]
I wish I realized this wasn't meant to work with HTML before I put in all the work to use it. 

I was simply looking for a small/light/easy email composer/editor which means using HTML.

I have this working using myEditor.dangerouslyPastHTML(html) to set and myEditor.root.innerHTML to get.. but it seems super sketchy!

Anyone have any suggestions regardly alternatives meant to work this way? I am trying to leave TinyMCE and CKEditor.

**Comment by AndiLeni** [comment]
I can't believe that after four years this problem has still not been solved.

For all those who are looking for an alternative that supports html export, tiptap on vue basis is the right choice.
Nexcloud is now using this for its text-editor addon.

https://tiptap.scrumpy.io/export

**Comment by lebesnec** [comment]
Wait, does that mean that there is no possibility to display the data created with the quill editor ???
Without embedding the whole editor I mean.

**Comment by firanto** [comment]
Getting the html through `quill.root.innerHTML` only get standard tags. Styles like text alignment, etc are provided through css class. It is fine if we can wrap this html with:
```
<link href="https://cdn.quilljs.com/1.3.6/quill.core.css" rel="stylesheet">
<div class="ql-editor">
    [any html retrieved from quill.root.innerHTML]
</div>
```
This, by itself, is fine. If you want to show this on your own page, no problem. But when this wrapped html sent through email (as email body), as in using rich text editor to compose email, that css reference and those custom classes are removed at receiver end (which is for security reason, because it is unsafe to reference to an unknown sources).

**Comment by claytongulick** [comment]
Another good option is editorjs: https://editorjs.io/ 

Pretty nice unobtrusive UI concept, and very advanced block based plugin architecture.

**Comment by jeevatrippy** [comment]
just do this
```var myEditor = document.querySelector('#editor')
var html = myEditor.children[0].innerHTML```

**Comment by xaddict** [comment]
It seems like Quill/Delta should have an official parser that takes into account the plugins added to the original instance. That way it is lightweight to recreate document contents and show them instead of editing them.

It should be possible to easily build this on Delta or extract only the HTML building from Quill and use it with Delta. Would make for a nicely tree-shakeable all in one package where Quill is just the editor, Delta is just the contents and "Build" is just a parser for Delta objects that build html/markdown/docx etc.

**Comment by spacegangster** [comment]
> just do this
> 
> ```
>    var myEditor = document.querySelector('#editor')
>    var html = myEditor.children[0].innerHTML
> ```

Lists lose indent.

**Comment by vivekm-testpoint** [comment]
> Getting the html through `quill.root.innerHTML` only get standard tags. Styles like text alignment, etc are provided through css class. It is fine if we can wrap this html with:
> 
> ```
> <link href="https://cdn.quilljs.com/1.3.6/quill.core.css" rel="stylesheet">
> <div class="ql-editor">
>     [any html retrieved from quill.root.innerHTML]
> </div>
> ```
> 

this worked for me

**Comment by firanto** [comment]
> 

As long as we didn't use this to send emails. Any reference to external sources (like cdn) are denied by email client. Other than that, we're good with this solution.

**Comment by maitrungduc1410** [comment]
> very interesting that such a library has no HTML output option... `ops` object is good, easier to store but what if the renderer platform has no quill support...

agree, that means, quill output can only be used inside Quill editor in a reliable way. but an editor usually is more than that, for example: sending email, generate blog post,...

**Comment by medi6** [comment]
There is a method that is doing what you wan't I think : getSemanticHTML()

**Comment by vegerot** [comment]
Today I began a project to transform quill delta into static HTML https://github.com/vegerot/quill-static-render
