### ISSUE TITLE
autoheight for the content area

### ISSUE THREAD

**Issue by dohomi** [quilljs/quill#95]
Hello,

does quill supports autoheight? Currently the height seems to be fixed, I would like that the content area is not restricted in the height.

Thanks,
Dominic

**Comment by gotibhai** [comment]
I'm sorry, I've been fiddling with this problem for a long while. Can someone explain the proper usage to obtain autosize? Right now I have a Container div which gives the margins for my editor and no height property specified. I'm using the bubble theme where the ql-container class and ql-editor have height set to 100% ( by default).

Right now, After reaching about the 100% which is ~ 979px the scrollbar appears. I think this is because the container div isn't expanding. Any help would be appreciated! Thanks! @jhchen

**Comment by djl132** [comment]
wait, so how do i set and make it grow, then. I've been trying to do that for DAYS.

**Comment by benbro** [comment]
[auto-grow example](https://quilljs.com/playground/#autogrow-height) in the docs.

**Comment by Vandana1992** [comment]
Can we have editor to behave like textarea so that there would be draggable feature.
