### ISSUE TITLE
Multiple spaces collapse to one space in paste

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#996]
When pasting text with multiple spaces, we only get one space.
In addition, when pasting HTML, multiple `&nbsp;` work but `&nbsp;` with a space produces one space.

I ran into it when trying to copy the output of "iostat -x" from linux terminal to quill.
When collapsing the spaces, the columns of iostat are not aligned.

**Steps for Reproduction**
1. Visit http://codepen.io/anon/pen/ozYayG

**Expected behavior**:
Three spaces between the letters: "a   b   c"

**Actual behavior**:
Only one space between the letters: "a b c"

**Platforms**:
Firefox 49 on Windows 7
Chrome 53 on Windows 7

**Version**:
1.0.4

**Comment by jhchen** [comment]
When initializing the editor the white-space rules are normal, so adjacent spaces are collapsed. This is done because most people writing normal markup with indents are doing so for code readability rather than to actually insert the indents. For example:

```html
<p>
  <strong>
    Text
  </strong>
<p>
```

Most people writing this would not intend for spaces to precede "Text", nor the bolding. So the codepen example is behaving as intended.

However pasting is different, and I think the pasting from iostat you are seeing is not due to the lack of spaces, but rather the font not being monospace. I pasted an output from iostat into the codepen but used the inspector to change the font to monospace and it does align.
